/* Living Town presentation-only state.
 * Reads simulation state and returns deterministic visual positions/poses.
 * It never awards resources, XP, changes jobs, advances farms, or construction.
 */
Settlement.LivingTownSystem=class{
 constructor(game){this.game=game;this.T=Settlement.Config.TILE||64;this._sitePool=[];this._sites=[];this._workPoints={quarry:[[-.34,.04],[-.18,.28],[.12,.3],[.34,.05]],ironMine:[[-.34,.04],[-.18,.28],[.12,.3],[.34,.05]],lumber:[[-.35,.12],[-.22,.32],[.22,.32],[.35,.12]],mason:[[-.32,.18],[.3,.18],[-.18,.34],[.18,.34]],mill:[[-.3,.24],[.3,.24],[-.18,.36],[.18,.36]],bakery:[[-.28,.26],[.28,.26],[-.14,.38],[.14,.38]],smelter:[[-.3,.22],[.3,.2],[-.18,.36],[.18,.36]],blacksmith:[[-.3,.22],[.3,.22],[-.15,.36],[.15,.36]],archery:[[0,-.05],[.08,.08],[-.08,.08],[0,.14]],training:[[-.26,.22],[.26,.22],[-.12,.38],[.12,.38]],default:[[-.25,.25],[.25,.25],[-.15,.38],[.15,.38]]}}
 hour(){return(this.game.clock.t/Settlement.Config.DAY_SECONDS)*24}
 workHours(){let h=this.hour();return h>=8&&h<17}
 buildingFor(c){return c?.workplace?this.game.buildings.byId(c.workplace):null}
 phase(id=0,scale=1){return(performance.now()/1000*scale+(id||0)*.731)}
 workPoint(b,c,out){if(!b)return null;out=out||{};let T=this.T,i=((c?.id||0)%4),cx=(b.x+b.w*.5)*T,cy=(b.y+b.h*.5)*T,p=(this._workPoints[b.type]||this._workPoints.default)[i];out.x=cx+p[0]*b.w*T;out.y=cy+p[1]*b.h*T;return out}
 workKind(c,b){if(!b)return null;if(b.type==="quarry"||b.type==="ironMine")return"mining";if(b.type==="lumber")return"chopping";if(b.type==="mason")return b.production?.active?"masonry":null;if(b.type==="mill")return"milling";if(b.type==="bakery")return"baking";if(b.type==="smelter")return"smelting";if(b.type==="blacksmith")return"forging";if(b.type==="archery")return"guarding";if(b.type==="training")return"training";return"working"}
 carryKind(c){if(!c)return null;if(c.job==="Stonecutter")return"stone";if(c.job==="Miner")return"ironOre";if(c.job==="Lumberjack")return"wood";if(c.job==="Smelter Worker")return"ironBar";if(c.job==="Blacksmith")return"tool";if(c.job==="Stonemason")return"tool";if(c.job==="Miller"||c.job==="Baker")return"basket";return null}
 citizenPresentation(c,out={}){let b=this.buildingFor(c),guard=c.job==="Guard",kind=!guard&&c.state==="WORKING"?this.workKind(c,b):null,p=kind?this.workPoint(b,c,out):null,t=this.phase(c.id,kind?3.2:1.8);out.x=p?.x??c.x;out.y=p?.y??c.y;out.bob=kind?Math.sin(t*2)*1.7:Math.sin(t)*.45;out.swing=kind?Math.sin(t*2.4):0;out.kind=kind;out.carry=!guard&&c.state==="TRAVEL_HOME"?this.carryKind(c):null;out.building=b;return out}
 _site(i){let s=this._sitePool[i];if(!s)this._sitePool[i]=s={};return s}
 ambientSites(){let n=0,T=this.T,dayWork=this.workHours();for(const b of this.game.buildings.list){let type=null,id=b.id,x=0,y=0,state=null,tended=false;if(!b.complete&&dayWork){type="construction";x=(b.x+.2+b.w*.14)*T;y=(b.y+b.h-.18)*T}else if(b.upgrading&&dayWork){type="construction";id=b.id+9000;x=(b.x+b.w-.25)*T;y=(b.y+b.h-.2)*T}else if(b.type==="farm"&&dayWork){let p=this.game.farms.plots.get(b.id);if(p&&p.state!=="empty"){type="farm";id=b.id+18000;let row=((b.id%3)+1)/4;x=(b.x+.25+b.w*.48)*T;y=(b.y+.18+b.h*row)*T;state=p.state;tended=!!p.tended}}else if(b.type==="market"&&b.complete&&dayWork){type="market";id=b.id+26000;x=(b.x+b.w*.35)*T;y=(b.y+b.h*.66)*T}if(!type)continue;let s=this._site(n++),t=this.phase(id,type==="farm"?1.8:2.2);s.type=type;s.x=x;s.y=y;s.bob=Math.sin(t*2)*(type==="farm"?.9:1.2);s.swing=Math.sin(t*(type==="farm"?1.8:2.6));s.id=id;s.state=state;s.tended=tended}this._sites.length=n;for(let i=0;i<n;i++)this._sites[i]=this._sitePool[i];return this._sites}
};
