/* City Era Foundation — informational progression + named districts only.
 * No unlocks, economy modifiers, placement rules, citizen AI or SaveSchema changes.
 */
Settlement.CityEraSystem=class{
 constructor(game){this.game=game;this.tick=.2;this._stage=null;this._districts=[];this.ensure();this.rebuild();for(const ev of["building:complete","building:removed","building:moved","building:upgraded","citizens:changed","territory:claimed","xp:changed"])game.bus.on(ev,()=>{this.tick=0})}
 ensure(){let s=this.game.stats||(this.game.stats={});if(!s.cityEra||typeof s.cityEra!=="object")s.cityEra={};if(!s.districtNames||typeof s.districtNames!=="object")s.districtNames={};return s}
 stages(){return[
  {id:"settlement",name:"Settlement",icon:"🔥",minLevel:1,minPop:0,test:g=>true},
  {id:"hamlet",name:"Hamlet",icon:"🏠",minLevel:3,minPop:6,test:g=>g.xp.level>=3&&g.citizens.list.length>=6},
  {id:"village",name:"Village",icon:"🏘️",minLevel:5,minPop:12,test:g=>g.xp.level>=5&&g.citizens.list.length>=12&&g.buildings.list.some(b=>b.complete&&b.type==="market")},
  {id:"town",name:"Town",icon:"🏛️",minLevel:7,minPop:18,test:g=>g.xp.level>=7&&g.citizens.list.length>=18&&g.buildings.list.some(b=>b.complete&&b.type==="mainHall")},
  {id:"walledTown",name:"Walled Town",icon:"🏰",minLevel:9,minPop:22,test:g=>g.xp.level>=9&&g.citizens.list.length>=22&&g.buildings.count("wall")>=8&&g.buildings.count("gate")>=1},
  {id:"city",name:"City",icon:"👑",minLevel:12,minPop:25,test:g=>g.xp.level>=12&&g.citizens.list.length>=25&&g.buildings.list.some(b=>b.complete&&b.type==="hallOfLegends")&&g.buildings.list.filter(b=>b.complete&&["blacksmith","smelter","bakery","mill","mason"].includes(b.type)).length>=3},
  {id:"greatCity",name:"Great City",icon:"⚜️",minLevel:15,minPop:45,test:g=>g.xp.level>=15&&g.citizens.list.length>=45&&g.expansion.totalTiles()>=350&&g.buildings.count("wall")>=20&&g.buildings.count("gate")>=2&&g.buildings.list.some(b=>b.complete&&b.type==="hallOfLegends")}
 ]}
 current(){let out=this.stages()[0];for(const s of this.stages())if(s.test(this.game))out=s;return out}
 next(){let ss=this.stages(),cur=this.current(),i=ss.findIndex(s=>s.id===cur.id);return ss[i+1]||null}
 progress(){let g=this.game,n=this.next();if(!n)return[];let req=[{label:`Town Level ${n.minLevel}`,ok:g.xp.level>=n.minLevel,value:`${g.xp.level}/${n.minLevel}`},{label:`Population ${n.minPop}`,ok:g.citizens.list.length>=n.minPop,value:`${g.citizens.list.length}/${n.minPop}`}];if(n.id==="village")req.push({label:"Market",ok:g.buildings.list.some(b=>b.complete&&b.type==="market")});if(n.id==="town")req.push({label:"Main Hall",ok:g.buildings.list.some(b=>b.complete&&b.type==="mainHall")});if(n.id==="walledTown")req.push({label:"8 Walls",ok:g.buildings.count("wall")>=8,value:`${g.buildings.count("wall")}/8`},{label:"Gate",ok:g.buildings.count("gate")>=1});if(n.id==="city")req.push({label:"Hall of Legends",ok:g.buildings.list.some(b=>b.complete&&b.type==="hallOfLegends")},{label:"3 Advanced Industries",ok:g.buildings.list.filter(b=>b.complete&&["blacksmith","smelter","bakery","mill","mason"].includes(b.type)).length>=3});if(n.id==="greatCity")req.push({label:"350 Land Tiles",ok:g.expansion.totalTiles()>=350,value:`${g.expansion.totalTiles()}/350`},{label:"20 Walls",ok:g.buildings.count("wall")>=20,value:`${g.buildings.count("wall")}/20`},{label:"2 Gates",ok:g.buildings.count("gate")>=2,value:`${g.buildings.count("gate")}/2`});return req}
 districtType(buildings){let c={};for(const b of buildings){let d=Settlement.BuildingDefs[b.type],k=d?.category||"Other";c[k]=(c[k]||0)+1}let types=buildings.map(b=>b.type);if(types.includes("hallOfLegends"))return["Legend Ward","👑"];if(types.includes("market")||types.includes("tradingPost")||types.includes("tavern"))return["Market Quarter","🪙"];if(c.Military>=Math.max(2,buildings.length*.35))return["Military Quarter","⚔️"];if(c.Farming>=Math.max(2,buildings.length*.4))return["Farmstead","🌾"];if(c.Production>=Math.max(2,buildings.length*.35))return["Iron Quarter","⚒️"];if(c.Civic>=Math.max(2,buildings.length*.35))return["Civic Ward","🏛️"];if(c.Residential>=Math.max(2,buildings.length*.45))return["Old Town","🏘️"];return["Town Ward","🛡️"]}
 rebuild(){let stats=this.ensure(),T=12,sectors=new Map;for(const b of this.game.buildings.list){let d=Settlement.BuildingDefs[b.type];if(!b.complete||d?.road||d?.wall||d?.amenity||["road","wall","gate","farm"].includes(b.type))continue;let sx=Math.floor((b.x+b.w/2)/T),sy=Math.floor((b.y+b.h/2)/T),id=`${sx},${sy}`;if(!sectors.has(id))sectors.set(id,[]);sectors.get(id).push(b)}let out=[];for(const[id,bs]of sectors){if(bs.length<2)continue;let[base,icon]=this.districtType(bs),cx=bs.reduce((n,b)=>n+b.x+b.w/2,0)/bs.length,cy=bs.reduce((n,b)=>n+b.y+b.h/2,0)/bs.length,name=stats.districtNames[id]||base;out.push({id,name,baseName:base,icon,x:cx,y:cy,buildingCount:bs.length,buildings:bs.map(b=>b.id)})}this._districts=out.sort((a,b)=>b.buildingCount-a.buildingCount);let stage=this.current(),persisted=stats.cityEra.currentStage;if(this._stage&&this._stage.id!==stage.id&&persisted!==stage.id){stats.cityEra.highestStage=stage.id;this.game.bus.emit("toast",`${stage.icon} Your settlement is now recognized as a ${stage.name}!`);this.game.legends?.record?.(`The settlement entered the ${stage.name} era.`,"cityEra")}this._stage=stage;stats.cityEra.currentStage=stage.id;this.game.bus.emit("cityEra:changed",{stage,districts:out})}
 districts(){return this._districts}
 rename(id,name){let stats=this.ensure(),d=this._districts.find(x=>x.id===id);if(!d)return false;name=String(name||"").trim().slice(0,32);if(!name)return false;stats.districtNames[id]=name;d.name=name;this.game.bus.emit("cityEra:changed",{stage:this.current(),districts:this._districts});this.game.bus.emit("toast",`🏘️ District renamed ${name}.`);return true}
 resetName(id){let stats=this.ensure();delete stats.districtNames[id];this.rebuild()}
 update(dt){this.tick-=dt;if(this.tick>0)return;this.tick=3;this.rebuild()}
 summary(){return{stage:this.current(),next:this.next(),progress:this.progress(),districts:this.districts()}}
};
