Settlement.WonderSystem=class{
 constructor(game){this.game=game;game.stats.enemiesDefeated=game.stats.enemiesDefeated||0;game.bus.on("enemy:defeated",()=>{game.stats.enemiesDefeated=(game.stats.enemiesDefeated||0)+1;game.bus.emit("wonders:changed")});game.bus.on("building:complete",b=>this.completed(b))}
 def(id){return Settlement.WonderDefs[id]||null}
 building(id){return this.game.buildings.list.find(b=>b.type===id)||null}
 value(r){let g=this.game;switch(r.type){case"townLevel":return g.xp.level;case"population":return g.citizens.list.length;case"gold":return Math.floor(g.resources.v.gold||0);case"resource":return Math.floor(g.resources.v[r.id]||0);case"building":return g.buildings.count(r.id);case"militaryBuildings":return g.buildings.list.filter(b=>b.complete&&Settlement.BuildingDefs[b.type]?.category==="Military").length;case"advancedMilitary":return g.buildings.count("barracks");case"territory":return g.expansion.totalTiles();case"totalBuildings":return g.buildings.list.filter(b=>b.complete).length;case"civicBuildings":return g.buildings.list.filter(b=>b.complete&&["Civic","Amenities"].includes(Settlement.BuildingDefs[b.type]?.category)).length;case"completedWonders":return g.buildings.list.filter(b=>b.complete&&Settlement.BuildingDefs[b.type]?.wonder).length;case"secret":return r.check?.(g)?r.target:0;default:return r.check?.(g)?r.target:0}}
 requirement(r){let value=this.value(r),complete=value>=r.target;return{...r,value,complete,revealed:!r.hidden||complete}}
 requirements(id){let d=this.def(id);return(d?.requirements||[]).map(r=>this.requirement(r))}
 unlocked(id){let d=this.def(id);return!!d&&!d.future&&this.requirements(id).every(r=>r.complete)}
 status(id){let d=this.def(id),b=this.building(id);if(d?.future)return"LOCKED";if(b?.complete)return"COMPLETED";if(b)return"UNDER CONSTRUCTION";return this.unlocked(id)?"AVAILABLE":"LOCKED"}
 stage(b){let stages=Settlement.BuildingDefs[b.type]?.constructionStages||[];if(b.complete)return{index:stages.length-1,label:stages.at(-1)||"Complete"};let index=Math.min(stages.length-2,Math.floor(Math.max(0,b.progress||0)*(stages.length-1)));return{index,label:stages[index]||"Construction"}}
 canPlace(id,notify=true){let d=this.def(id);if(!d||d.future)return false;if(this.building(id)){if(notify)this.game.bus.emit("toast",d.name+" is unique and already stands in this settlement.");return false}if(!this.unlocked(id)){if(notify)this.game.bus.emit("toast","🔒 Complete the Wonder requirements first.");return false}return true}
 completed(b){if(!Settlement.BuildingDefs[b.type]?.wonder)return;let d=this.def(b.type);this.game.bus.emit("celebration",{icon:d.icon,text:`WONDER COMPLETED — ${d.name.toUpperCase()}`});this.game.bus.emit("toast",`✨ ${d.name} now watches over your settlement.`);this.game.bus.emit("wonders:changed");this.game.save?.save()}
};
(()=>{let P=Settlement.PlacementSystem?.prototype,B=Settlement.BuildingManager?.prototype;if(P&&!P.__wondersPatched){P.__wondersPatched=true;let start=P.start,move=P.startMove;P.start=function(type){if(Settlement.BuildingDefs[type]?.wonder&&!this.game.wonders?.canPlace(type))return false;return start.call(this,type)};P.startMove=function(b){if(Settlement.BuildingDefs[b?.type]?.wonder){this.game.bus.emit("toast","Wonders are permanent monuments and cannot be relocated.");return false}return move.call(this,b)}}if(B&&!B.__wondersPatched){B.__wondersPatched=true;let demolish=B.demolish;B.demolish=function(id){let b=this.byId(id);if(Settlement.BuildingDefs[b?.type]?.wonder){this.game.bus.emit("toast","Wonders are permanent and cannot be demolished.");return false}return demolish.call(this,id)}}})();
