Settlement.CitizenManager=class{
 constructor(game){this.game=game;this.list=[];this.names=["Mara","Edwin","Tomas","Elena","Rowan","Bea","Alden","Nora","Giles","Lina","Hugh","Mira"];this.next=1;this.seed(2)}
 seed(n){while(this.list.length<n)this.add()}
 pickClaimedRect(){let rects=this.game?.expansion?.claimedRects||[];if(!rects.length){let C=Settlement.Config;return{x:C.START_X,y:C.START_Y,w:C.START_W,h:C.START_H}}let total=rects.reduce((n,r)=>n+r.w*r.h,0),roll=Math.random()*total;for(const r of rects){roll-=r.w*r.h;if(roll<=0)return r}return rects[rects.length-1]}
 add(){let r=this.pickClaimedRect(),T=Settlement.Config.TILE;this.list.push({id:this.next++,name:this.names[(this.next*7)%this.names.length],age:"Adult",home:null,job:"Unassigned",workplace:null,skill:1,morale:80,health:100,x:(r.x+1+Math.random()*Math.max(1,r.w-2))*T,y:(r.y+1+Math.random()*Math.max(1,r.h-2))*T,tx:0,ty:0,speed:20+Math.random()*8,state:"wandering"});this.game?.bus?.emit("citizens:changed")}
 capacity(){return this.game.buildings.list.filter(b=>b.complete).reduce((n,b)=>n+(Settlement.BuildingDefs[b.type].populationCapacity||0),0)}
 syncPopulation(){let cap=this.capacity();while(this.list.length<cap)this.add()}
 assign(building){let def=Settlement.BuildingDefs[building.type];if(!def?.workers||((building.workers||0)>=def.workers))return false;let c=this.list.find(c=>c.job==="Unassigned");if(!c)return false;c.job=building.type==="archery"?"Archer":building.type==="lumber"?"Lumberjack":"Trainee";c.workplace=building.id;building.workers=(building.workers||0)+1;this.game.bus.emit("citizens:changed");return true}
 update(dt){let T=Settlement.Config.TILE;for(let c of this.list){if(!c.tx||Math.hypot(c.tx-c.x,c.ty-c.y)<8){let wp=c.workplace&&this.game.buildings.byId(c.workplace);if(wp&&Math.random()<.7){c.tx=(wp.x+wp.w/2)*T;c.ty=(wp.y+wp.h/2)*T}else{let r=this.pickClaimedRect();c.tx=(r.x+.5+Math.random()*Math.max(.5,r.w-1))*T;c.ty=(r.y+.5+Math.random()*Math.max(.5,r.h-1))*T}}let dx=c.tx-c.x,dy=c.ty-c.y,d=Math.hypot(dx,dy)||1;c.x+=dx/d*c.speed*dt;c.y+=dy/d*c.speed*dt}}
};
