(()=>{
 const p=Settlement.UIManager?.prototype;if(!p||p.__cityEraUI)return;p.__cityEraUI=true;
 const baseNav=p.nav,baseAction=p.action;
 const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]||m));
 p.cityEraPanel=function(){let s=this.game.cityEra?.summary?.();if(!s)return"<p>City Era data is still initializing.</p>";let req=s.progress.map(r=>`<div class="hall-row"><span>${r.ok?"✓":"○"} ${esc(r.label)}</span><b>${esc(r.value||"")}</b></div>`).join("")||"<p>Maximum city stage reached.</p>",districts=s.districts.map(d=>`<div class="build-card"><div class="build-icon">${d.icon}</div><div><b>${esc(d.name)}</b><small>${d.buildingCount} major buildings · ${esc(d.baseName)}</small></div><div><button class="wood-button" data-act="renameDistrict:${esc(d.id)}">Rename</button></div></div>`).join("")||"<p>Build a few structures near one another and districts will begin to emerge.</p>";let roadmap=Object.entries(Settlement.CityEraRoadmap||{}).map(([lv,name])=>`<div class="hall-row"><span>${this.game.xp.level>=+lv?"✓":"○"} Level ${lv}</span><b>${esc(name)}</b></div>`).join("");return `<p class="hall-title">${s.stage.icon} ${esc(s.stage.name)}</p><p class="frontier-hint">City Era recognition does not alter existing production, prices, immigration, combat or placement.</p>${s.next?`<h3>Next: ${s.next.icon} ${esc(s.next.name)}</h3><div class="hall-grid">${req}</div>`:`<h3>⚜️ Great City</h3><p>Your settlement has reached the highest current civic stage.</p>`}${roadmap?`<h3>Town Level 16–50 Roadmap</h3><div class="hall-grid">${roadmap}</div>`:""}<h3>Named Districts</h3>${districts}`};
 p.districtMapPanel=function(){let s=this.game.cityEra?.summary?.();if(!s)return"<p>District map unavailable.</p>";return `<p class="hall-title">${s.stage.icon} ${esc(s.stage.name)} District Map</p><p class="frontier-hint">Districts are descriptive only. Rename them freely; no economic or citizen behavior depends on the name.</p>${s.districts.map(d=>`<button class="build-card" data-act="focusDistrict:${esc(d.id)}"><div class="build-icon">${d.icon}</div><div><b>${esc(d.name)}</b><small>${d.buildingCount} buildings · tap to focus</small></div></button>`).join("")||"<p>No established districts yet.</p>"}`};
 p.nav=function(n){if(n==="MAP"){baseNav.call(this,n);this.panel("City & District Map",this.districtMapPanel());return}baseNav.call(this,n);if(n==="TOWN"){let box=document.querySelector("#panel .panel-scroll");if(box&&!box.querySelector("[data-city-era]")){let d=document.createElement("div");d.dataset.cityEra="1";d.innerHTML=`<h3>🏙️ City Era</h3>${this.cityEraPanel()}`;box.appendChild(d)}}};
 p.action=function(a,id){a=String(a||"");if(a.startsWith("renameDistrict:")){let did=a.slice("renameDistrict:".length),d=this.game.cityEra?.districts().find(x=>x.id===did);if(!d)return;let name=prompt("Rename district",d.name);if(name!==null)this.game.cityEra.rename(did,name);this.panel("City & District Map",this.districtMapPanel());return}if(a.startsWith("focusDistrict:")){let did=a.slice("focusDistrict:".length),d=this.game.cityEra?.districts().find(x=>x.id===did);if(d){let T=Settlement.Config.TILE;this.game.camera.tx=d.x*T;this.game.camera.ty=d.y*T;this.game.camera.tzoom=Math.max(this.game.camera.tzoom,.65);this.game.camera.clamp();this.closePanels();this.toast(`🏘️ ${d.name}`)}return}return baseAction.call(this,a,id)};
})();
