(()=>{
 const proto=Settlement.UIManager?.prototype;if(!proto||proto.__commercePatched)return;proto.__commercePatched=true;
 const baseBind=proto.bind,baseNav=proto.nav,baseAction=proto.action,baseInspect=proto.inspect;
 proto.bind=function(){baseBind.call(this);this.game.bus.on("commerce:changed",()=>{if(this._commerceOpen)this.renderCommerce()})};
 proto.tradeRows=function(obj){return Object.entries(obj||{}).map(([k,v])=>`${Settlement.ResourceDefs[k]?.icon||""} ${v} ${Settlement.ResourceDefs[k]?.name||k}`).join(" • ")};
 proto.renderCommerce=function(){let c=this.game.commerce,s=c.state,market=c.market(),html="";if(!market){html=`<div class="production-mode">🏪 MEDIEVAL COMMERCE</div><p>Build a <b>Market</b> to attract traveling merchants and trade settlement surplus.</p><p class="production-help">Trades are always optional. Nothing is sold automatically.</p>`}else if(!s.active){let mins=s.nextAt?Math.max(1,Math.ceil((s.nextAt-Date.now())/60000)):1;html=`<div class="production-mode">🏪 MARKET OPEN</div><p>The stalls are ready. A traveling merchant is expected in about <b>${mins} min</b>.</p><p class="production-help">Merchants stay long enough to inspect and complete several voluntary orders.</p>`}else{let mins=Math.max(0,Math.ceil(c.remaining()/60000));html=`<div class="production-mode">🔔 MERCHANT IN TOWN</div><h3>${s.merchant}</h3><p>Departing in about <b>${mins} min</b>.</p><div class="trade-orders">${s.orders.map(o=>`<div class="build-card"><div><b>${o.label}</b><small>Requires: ${this.tradeRows(o.requires)}</small><small>Reward: ${this.tradeRows(o.reward)}</small></div><div>${o.completed?`<b>✓ TRADED</b>`:`<button class="wood-button" data-act="trade" data-id="${o.id}">Complete Trade</button>`}</div></div>`).join("")}</div><p class="production-help">Goods are removed only when you press Complete Trade. Each order can pay out once.</p>`}this.panel("Trade & Market",html)};
 proto.nav=function(n){this._commerceOpen=n==="TRADE";if(n==="TRADE"){document.querySelectorAll(".navbtn").forEach(b=>b.classList.toggle("active",b.dataset.nav===n));this.closePanels();this.renderCommerce();return}return baseNav.call(this,n)};
 proto.action=function(act,id){if(act==="trade"){this.game.commerce.complete(id);this._commerceOpen=true;this.renderCommerce();return}return baseAction.call(this,act,id)};
 proto.inspect=function(b){if(b?.type==="market"){let s=this.game.commerce.state,status=s.active?`<b>${s.merchant}</b> is trading now.`:`Market stalls are open; the next merchant will arrive periodically.`;this.panel("Market",`<div class="production-mode">🏪 SETTLEMENT MARKET</div><p>${status}</p><button class="wood-button" data-act="openTrade">Open Trade Board</button>`+(this.upgradePanel?this.upgradePanel(b):"")+(this.managePanel?this.managePanel(b):""));return}return baseInspect.call(this,b)};
 const oldAction=proto.action;proto.action=function(act,id){if(act==="openTrade"){this._commerceOpen=true;this.renderCommerce();return}return oldAction.call(this,act,id)};
})();
