(()=>{
 const p=Settlement.UIManager?.prototype;if(!p||p.__guardGarrisonPatched)return;p.__guardGarrisonPatched=true;
 const baseNav=p.nav,baseInspect=p.inspect,baseAction=p.action;
 p.securityPanel=function(){let s=this.game.security?.summary?.();if(!s)return"";let rows=s.breakdown.map(x=>`<div class="hall-row"><span>${x.label}</span><b>+${x.value}</b></div>`).join("");return `<h3>🛡️ Security — ${s.value}/100 <span class="band">${s.tier}</span></h3><p class="frontier-hint">Security measures how prepared the settlement is to detect and respond to Raiders. It never changes production or the economy.</p><div class="hall-grid">${rows}</div>`};
 p.barracksGuardPanel=function(b){let g=this.game.guards,cap=g.capacity(b),assigned=g.assigned(b),free=this.game.citizens.list.filter(c=>c.job==="Unassigned").length;return `<div class="production-mode">🛡️ ACTIVE WATCH</div><p class="production-help">Guards patrol important buildings and player-defined Defense Zones, then intercept nearby Raiders using the same authoritative enemy reward path as towers.</p><div class="hall-grid"><div class="hall-row"><span>Guards</span><b>${assigned.length}/${cap}</b></div><div class="hall-row"><span>Unassigned citizens</span><b>${free}</b></div></div>${assigned.map(c=>`<div class="build-card"><div class="build-icon">🛡️</div><div><b>${c.name}</b><small>${g.presentation(c)?.mode||"muster"} · ${this.game.legends?.rank?.(c)||"Recruit"} · ${c.combatKills||0} kills</small></div><button class="wood-button" data-act="guardUnassign" data-id="${c.id}">Unassign</button></div>`).join("")}${assigned.length<cap?`<button class="wood-button" data-act="guardAssign" data-id="${b.id}"${free?"":" disabled"}>Assign Guard</button>`:"<p class='production-help'>Guard capacity reached. Upgrade the Barracks to expand the watch.</p>"}`};
 p.frontierPanel=function(){let f=this.game.frontier,s=f?.summary?.()||{},zones=f?.zones?.()||[];return `<h3>⚔️ Frontier Warfare</h3><p class="frontier-hint">Named factions probe valuable weak points. Rare sieges bring heavier troops and commanders; legendary captains carry permanent trophy relics.</p><div class="hall-grid"><div class="hall-row"><span>Alert</span><b>${s.alert?"RAID ACTIVE":"Clear"}</b></div><div class="hall-row"><span>Raids seen</span><b>${s.raids||0}</b></div><div class="hall-row"><span>Bosses defeated</span><b>${s.bosses||0}</b></div><div class="hall-row"><span>Sieges broken</span><b>${this.game.stats.siegesWon||0}</b></div><div class="hall-row"><span>Defense zones</span><b>${s.zones||0}</b></div></div><h3>Defense Zones</h3><p class="frontier-hint">Center the camera over an area, then establish a zone. Guards add those points to their patrol route.</p><button class="wood-button" data-act="frontierZone" data-id="HOLD">Hold Zone</button> <button class="wood-button" data-act="frontierZone" data-id="PATROL">Patrol Zone</button> <button class="wood-button" data-act="frontierZone" data-id="PROTECT">Protect Zone</button>${zones.map(z=>`<div class="build-card"><div class="build-icon">🛡️</div><div><b>${z.mode}</b><small>Tile ${z.x}, ${z.y} · radius ${z.radius}</small></div><button class="wood-button" data-act="frontierZoneRemove" data-id="${z.id}">Remove</button></div>`).join("")}<h3>Debug</h3><button class="wood-button" data-act="frontierRaid">Spawn Test Raid</button> <button class="wood-button" data-act="frontierBoss">Spawn Test Boss</button> <button class="wood-button" data-act="frontierSiege">Spawn Test Siege</button>`};
 p.nav=function(n){baseNav.call(this,n);if(n==="ARMY"){this.panel("Army & Frontier Defense",this.securityPanel()+this.frontierPanel()+`<h3>Guard Watch</h3><p>Build a <b>Barracks</b> to assign Guards. Surviving defenders earn combat experience and can become Veterans, Elites and Champions.</p>`)}else if(n==="TOWN"){let box=document.querySelector("#panel .panel-scroll");if(box&&!box.querySelector("[data-security-panel]")){let d=document.createElement("div");d.dataset.securityPanel="1";d.innerHTML=this.securityPanel();box.appendChild(d)}}};
 p.inspect=function(b){baseInspect.call(this,b);if(b?.type==="barracks"&&b.complete){let box=document.querySelector("#panel .panel-scroll");if(box){let d=document.createElement("div");d.dataset.guardPanel="1";d.innerHTML=this.barracksGuardPanel(b);box.prepend(d)}}};
 p.action=function(a,id){if(a==="guardAssign"){let b=this.game.buildings.byId(Number(id)),c=this.game.guards.assign(b);this.toast(c?`🛡️ ${c.name} joined the Watch.`:"No eligible citizen or Guard slot available.");if(b)this.inspect(b);return}if(a==="guardUnassign"){let c=this.game.citizens.list.find(x=>x.id===Number(id)),bid=c?.workplace,b=this.game.buildings.byId(bid);if(this.game.guards.unassign(c))this.toast(`🛡️ ${c.name} returned to civilian duty.`);if(b)this.inspect(b);return}if(a==="frontierZone"){this.game.frontier?.addZone(String(id||"HOLD"));this.nav("ARMY");return}if(a==="frontierZoneRemove"){this.game.frontier?.removeZone(Number(id));this.nav("ARMY");return}if(a==="frontierRaid"){this.game.enemies.spawnRaid();this.nav("ARMY");return}if(a==="frontierBoss"){this.game.enemies.spawn("raiderCaptain");this.nav("ARMY");return}return baseAction.call(this,a,id)};
})();
