(()=>{
 const p=Settlement.UIManager?.prototype;if(!p||p.__guardGarrisonPatched)return;p.__guardGarrisonPatched=true;
 const baseNav=p.nav,baseInspect=p.inspect,baseAction=p.action;
 p.securityPanel=function(){let s=this.game.security?.summary?.();if(!s)return"";let rows=s.breakdown.map(x=>`<div class="hall-row"><span>${x.label}</span><b>+${x.value}</b></div>`).join("");return `<h3>🛡️ Security — ${s.value}/100 <span class="band">${s.tier}</span></h3><p class="frontier-hint">Security measures how prepared the settlement is to detect and respond to Raiders. It never changes production or the economy.</p><div class="hall-grid">${rows}</div><p class="frontier-hint">Higher Security modestly improves how far Guards can coordinate a response. Raider frequency and rewards remain unchanged.</p>`};
 p.barracksGuardPanel=function(b){let g=this.game.guards,cap=g.capacity(b),assigned=g.assigned(b),free=this.game.citizens.list.filter(c=>c.job==="Unassigned").length;return `<div class="production-mode">🛡️ NIGHT WATCH</div><p class="production-help">Guards remain normal citizens. They patrol roads and important buildings, then intercept nearby Raiders using the same authoritative enemy death/reward path as towers.</p><div class="hall-grid"><div class="hall-row"><span>Guards</span><b>${assigned.length}/${cap}</b></div><div class="hall-row"><span>Unassigned citizens</span><b>${free}</b></div></div>${assigned.map(c=>`<div class="build-card"><div class="build-icon">🛡️</div><div><b>${c.name}</b><small>${g.presentation(c)?.mode||"muster"}</small></div><button class="wood-button" data-act="guardUnassign" data-id="${c.id}">Unassign</button></div>`).join("")}${assigned.length<cap?`<button class="wood-button" data-act="guardAssign" data-id="${b.id}"${free?"":" disabled"}>Assign Guard</button>`:"<p class='production-help'>Guard capacity reached. Upgrade the Barracks to expand the watch.</p>"}`};
 p.nav=function(n){baseNav.call(this,n);if(n==="ARMY"){this.panel("Army & Security",this.securityPanel()+`<h3>Night Watch</h3><p>Build a <b>Barracks</b> to assign citizens as Guards. Guards patrol the town and respond to Raiders; Archery Towers remain the primary ranged defence.</p><button class="wood-button" data-act="spawn">Spawn Debug Bandit</button>`)}else if(n==="TOWN"){let box=document.querySelector("#panel .panel-scroll");if(box&&!box.querySelector("[data-security-panel]")){let d=document.createElement("div");d.dataset.securityPanel="1";d.innerHTML=this.securityPanel();box.appendChild(d)}}};
 p.inspect=function(b){baseInspect.call(this,b);if(b?.type==="barracks"&&b.complete){let box=document.querySelector("#panel .panel-scroll");if(box){let d=document.createElement("div");d.dataset.guardPanel="1";d.innerHTML=this.barracksGuardPanel(b);box.prepend(d)}}};
 p.action=function(a,id){if(a==="guardAssign"){let b=this.game.buildings.byId(Number(id)),c=this.game.guards.assign(b);this.toast(c?`🛡️ ${c.name} joined the Night Watch.`:"No eligible citizen or Guard slot available.");if(b)this.inspect(b);return}if(a==="guardUnassign"){let c=this.game.citizens.list.find(x=>x.id===Number(id)),bid=c?.workplace,b=this.game.buildings.byId(bid);if(this.game.guards.unassign(c))this.toast(`🛡️ ${c.name} returned to civilian duty.`);if(b)this.inspect(b);return}return baseAction.call(this,a,id)};
})();
