(()=>{
 const p=Settlement.UIManager?.prototype;if(!p||p.__legendsUI)return;p.__legendsUI=true;
 const baseNav=p.nav,baseInspect=p.inspect,baseAction=p.action;
 const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]||m));
 p.frontierPanel=function(){let ex=this.game.expansion,towers=this.game.buildings.list.filter(b=>b.type==="archery"),levels=Settlement.BuildingDefs.archery?.levels||[],at=lv=>levels.find(x=>x.level===lv)?.claim||"?";return `<h3>Territory</h3><p class="frontier-hint">Build an <b>Archery Tower</b> near your border. When it finishes, it claims a square of land around itself. The <b>Hall of Legends</b> may establish one remote 17×17 stronghold.</p><div class="hall-grid"><div class="hall-row"><span>Land held</span><b>${ex.totalTiles()} tiles</b></div><div class="hall-row"><span>Territory claims</span><b>${ex.claimed}</b></div><div class="hall-row"><span>Archery Towers</span><b>${towers.length}</b></div></div><p class="frontier-hint">Tower claims: ${at(1)}×${at(1)} at Lv1 · ${at(5)}×${at(5)} at Lv5 · ${at(10)}×${at(10)} at Lv10 · ${at(15)}×${at(15)} at Lv15.</p>`};
 p.legendsPanel=function(){let l=this.game.legends?.summary?.();if(!l)return"<p>The chronicles are unavailable.</p>";let heroes=l.heroes.map(c=>{let r=this.game.legends.relicFor(c);return `<div class="hall-row"><span>⚔️ ${esc(c.name)}</span><b>${esc(this.game.legends.rank(c))} · ${c.combatKills||0} kills${r?` · 🏆 ${esc(r.name)}`:""}</b></div>`}).join("")||"<p>No veteran defenders yet.</p>",bosses=l.bosses.slice(0,8).map(b=>`<div class="build-card"><div class="build-icon">☠️</div><div><b>${esc(b.name)}</b><small>${esc(b.trait)} · ${esc(b.faction)} · Day ${b.day}<br>🏆 ${esc(b.relic)}</small></div></div>`).join("")||"<p>No named captains have fallen yet.</p>",relics=l.relics.slice(0,10).map((r,i)=>{let owner=r.equippedTo&&this.game.citizens.list.find(c=>c.id===r.equippedTo),buttons=owner?`<button class="wood-button" data-act="unequipRelic:${i}">Unequip</button>`:l.heroes.length?l.heroes.slice(0,4).map(c=>`<button class="wood-button" data-act="equipRelic:${i}:${c.id}">${esc(c.name)}</button>`).join(" "):"<small>Earn a Veteran defender to equip.</small>";return `<div class="build-card"><div class="build-icon">🏆</div><div><b>${esc(r.name)}</b><small>${esc(r.rarity||"Relic")} · ${esc(r.bonus||this.game.legends.relicDefs?.[r.name]?.label||"Legendary trophy")}<br>${owner?`Equipped: ${esc(owner.name)}`:"Unequipped"}</small><div>${buttons}</div></div></div>`}).join("")||"<p>No trophies yet.</p>",mem=l.memorials.slice(0,8).map(m=>`<div class="hall-row"><span>🕯️ ${esc(m.name)}</span><b>${esc(m.job)} · Day ${m.day}</b></div>`).join("")||"<p>No names have been entered in the memorial book.</p>",chron=l.chronicle.slice(0,12).map(e=>`<div class="hall-row"><span>Day ${e.day} · ${esc(e.season)}</span><b>${esc(e.text)}</b></div>`).join("")||"<p>The first page is waiting to be written.</p>";return `<p class="hall-title">👑 ${esc(l.title)}</p><div class="hall-grid"><div class="hall-row"><span>Bosses slain</span><b>${l.bosses.length}</b></div><div class="hall-row"><span>Sieges broken</span><b>${l.siegesWon}</b></div><div class="hall-row"><span>Greatest raid</span><b>${l.greatestRaid} attackers</b></div><div class="hall-row"><span>Population record</span><b>${l.highestPopulation}</b></div><div class="hall-row"><span>Gold record</span><b>${l.goldRecord}</b></div><div class="hall-row"><span>Land held</span><b>${this.game.expansion.totalTiles()} tiles</b></div></div><h3>Heroes</h3><div class="hall-grid">${heroes}</div><h3>Bosses Slain</h3>${bosses}<h3>Relics & Equipment</h3>${relics}<h3>Memorial Book</h3><div class="hall-grid">${mem}</div><h3>Settlement Chronicle</h3><div class="hall-grid">${chron}</div>`};
 p.wantedPanel=function(){let w=this.game.legends?.wanted?.();return w?`<div class="production-mode">📜 WANTED — ${esc(w.name)}</div><p><b>${esc(w.trait)}</b> commander of the <b>${esc(w.faction)}</b>. Scouts whisper that this captain may carry a trophy like the <b>${esc(w.rewardHint)}</b>. The captain can appear naturally in a future raid.</p>`:"<p>No active wanted notice.</p>"};
 p.nav=function(n){baseNav.call(this,n);if(n==="TOWN"){let box=document.querySelector("#panel .panel-scroll");if(box&&!box.querySelector("[data-legends-summary]")){let d=document.createElement("div");d.dataset.legendsSummary="1";let hall=this.game.buildings.list.find(b=>b.type==="hallOfLegends"&&b.complete);d.innerHTML=`<h3>👑 Legends</h3><p>${hall?`The <b>Hall of Legends</b> stands as a fortified archive and distant stronghold.`:`Build the <b>Hall of Legends</b> at Town Level 10 to create a fortified distant holding.`}</p><button class="wood-button" data-act="openLegends">Open Chronicle</button>`;box.appendChild(d)}}};
 p.inspect=function(b){baseInspect.call(this,b);let box=document.querySelector("#panel .panel-scroll");if(!box)return;if(b?.type==="hallOfLegends"&&b.complete){let d=document.createElement("div");d.dataset.legendsHall="1";d.innerHTML=`<h3>👑 Hall of Legends</h3><p>Fortified 5×5 civic stronghold · claims a 17×17 holding · two permanent archers · long-range defense.</p>${this.legendsPanel()}`;box.prepend(d)}else if(b?.type==="noticeBoard"&&b.complete){let d=document.createElement("div");d.dataset.wantedBoard="1";d.innerHTML=`<h3>Wanted Board</h3>${this.wantedPanel()}`;box.prepend(d)}else if(b?.type==="memorialGarden"&&b.complete){let d=document.createElement("div");d.dataset.memorialBook="1";let ms=this.game.legends?.summary?.().memorials||[];d.innerHTML=`<h3>🕯️ Memorial Garden</h3>${ms.length?ms.slice(0,8).map(m=>`<p><b>${esc(m.name)}</b> — ${esc(m.job)}, Day ${m.day}</p>`).join(""):"<p>The stones are quiet. No fallen citizens are recorded.</p>"}`;box.prepend(d)}};
 p.action=function(a,id){if(a==="openLegends"){this.panel("Hall of Legends — Chronicle",this.legendsPanel());return}if(a==="frontierSiege"){this.game.enemies.spawnRaid(true);this.nav("ARMY");return}if(String(a).startsWith("equipRelic:")){let[,i,cid]=a.split(":");this.game.legends.equipRelic(i,cid);this.panel("Hall of Legends — Chronicle",this.legendsPanel());return}if(String(a).startsWith("unequipRelic:")){let i=a.split(":")[1];this.game.legends.unequipRelic(i);this.panel("Hall of Legends — Chronicle",this.legendsPanel());return}return baseAction.call(this,a,id)};
})();
document.write('<script src="src/ui/WondersUI.js?v=0.18.0-wonders"><\/script>');
