(()=>{
 const p=Settlement.UIManager?.prototype;if(!p||p.__legendsUI)return;p.__legendsUI=true;
 const baseNav=p.nav,baseInspect=p.inspect,baseAction=p.action;
 const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
 p.legendsPanel=function(){let l=this.game.legends?.summary?.();if(!l)return"<p>The chronicles are unavailable.</p>";let heroes=l.heroes.map(c=>`<div class="hall-row"><span>⚔️ ${esc(c.name)}</span><b>${esc(this.game.legends.rank(c))} · ${c.combatKills||0} kills</b></div>`).join("")||"<p>No veteran defenders yet.</p>",bosses=l.bosses.slice(0,8).map(b=>`<div class="build-card"><div class="build-icon">☠️</div><div><b>${esc(b.name)}</b><small>${esc(b.trait)} · ${esc(b.faction)} · Day ${b.day}<br>🏆 ${esc(b.relic)}</small></div></div>`).join("")||"<p>No named captains have fallen yet.</p>",relics=l.relics.slice(0,10).map(r=>`<div class="hall-row"><span>🏆 ${esc(r.name)}</span><b>${esc(r.rarity||"Relic")}</b></div>`).join("")||"<p>No trophies yet.</p>",chron=l.chronicle.slice(0,12).map(e=>`<div class="hall-row"><span>Day ${e.day} · ${esc(e.season)}</span><b>${esc(e.text)}</b></div>`).join("")||"<p>The first page is waiting to be written.</p>";return `<p class="hall-title">👑 ${esc(l.title)}</p><div class="hall-grid"><div class="hall-row"><span>Bosses slain</span><b>${l.bosses.length}</b></div><div class="hall-row"><span>Sieges broken</span><b>${l.siegesWon}</b></div><div class="hall-row"><span>Greatest raid</span><b>${l.greatestRaid} attackers</b></div><div class="hall-row"><span>Population record</span><b>${l.highestPopulation}</b></div><div class="hall-row"><span>Gold record</span><b>${l.goldRecord}</b></div><div class="hall-row"><span>Land held</span><b>${this.game.expansion.totalTiles()} tiles</b></div></div><h3>Heroes</h3><div class="hall-grid">${heroes}</div><h3>Bosses Slain</h3>${bosses}<h3>Trophy Gallery</h3><div class="hall-grid">${relics}</div><h3>Settlement Chronicle</h3><div class="hall-grid">${chron}</div>`};
 p.nav=function(n){baseNav.call(this,n);if(n==="TOWN"){let box=document.querySelector("#panel .panel-scroll");if(box&&!box.querySelector("[data-legends-summary]")){let d=document.createElement("div");d.dataset.legendsSummary="1";let hall=this.game.buildings.list.find(b=>b.type==="hallOfLegends"&&b.complete);d.innerHTML=`<h3>👑 Legends</h3><p>${hall?`The <b>Hall of Legends</b> stands as a fortified archive and distant stronghold.`:`Build the <b>Hall of Legends</b> at Town Level 10 to create a fortified distant holding.`}</p><button class="wood-button" data-act="openLegends">Open Chronicle</button>`;box.appendChild(d)}}};
 p.inspect=function(b){baseInspect.call(this,b);if(b?.type==="hallOfLegends"&&b.complete){let box=document.querySelector("#panel .panel-scroll");if(box){let d=document.createElement("div");d.dataset.legendsHall="1";d.innerHTML=`<h3>👑 Hall of Legends</h3><p>Fortified 5×5 civic stronghold · claims a 17×17 holding · two permanent archers · long-range defense.</p>${this.legendsPanel()}`;box.prepend(d)}}};
 p.action=function(a,id){if(a==="openLegends"){this.panel("Hall of Legends — Chronicle",this.legendsPanel());return}if(a==="frontierSiege"){this.game.enemies.spawnRaid(true);this.nav("ARMY");return}return baseAction.call(this,a,id)};
})();
