Settlement.PlacementUI=class{
 constructor(game,root){this.game=game;this.root=root;this.el=document.createElement("div");this.el.id="placement-toolbar";this.el.className="hidden";this.el.setAttribute("aria-live","polite");this._touchActivatedAt=0;root.appendChild(this.el);this.bind()}
 bind(){let b=this.game.bus;b.on("placement:start",()=>{let h=document.querySelector("#placement-help");if(h)h.textContent="Tap map to position • drag to pan • pinch to zoom • ✓ BUILD to confirm";this.render()});b.on("placement:moved",()=>this.render());b.on("placement:validity",()=>this.render());b.on("placement:end",()=>this.hide());b.on("resources:changed",()=>{if(this.game.placement.type)this.render()});
  const activate=a=>{if(a==="confirm"){this.game.audio?.play("tap");this.game.placement.confirm();return true}if(a==="cancel"){this.game.audio?.play("tap");this.game.placement.cancel("user");return true}return false};
  this.el.addEventListener("pointerdown",e=>{e.stopPropagation();if(e.pointerType==="touch")e.currentTarget.__placeDown={id:e.pointerId,x:e.clientX,y:e.clientY,act:e.target.closest("[data-place-act]")?.dataset.placeAct||null}},{passive:true});
  this.el.addEventListener("pointerup",e=>{e.stopPropagation();if(e.pointerType!=="touch")return;let s=e.currentTarget.__placeDown;e.currentTarget.__placeDown=null;if(!s||s.id!==e.pointerId||!s.act||Math.hypot(e.clientX-s.x,e.clientY-s.y)>14)return;let now=e.target.closest("[data-place-act]")?.dataset.placeAct;if(now!==s.act)return;e.preventDefault();this._touchActivatedAt=performance.now();activate(now)},{passive:false});
  this.el.addEventListener("pointercancel",e=>{e.currentTarget.__placeDown=null;e.stopPropagation()},{passive:true});
  this.el.addEventListener("click",e=>{e.stopPropagation();if(performance.now()-this._touchActivatedAt<750){e.preventDefault();return}let a=e.target.closest("[data-place-act]")?.dataset.placeAct;activate(a)})
 }
 hide(){this.el.classList.add("hidden");this.el.innerHTML=""}
 costHTML(d){return Object.entries(d.cost||{}).map(([k,v])=>{let have=Math.floor(this.game.resources.v[k]||0),ok=have>=v;return `<span class="placement-cost ${ok?"ok":"short"}">${Settlement.ResourceDefs[k]?.icon||k} ${have}/${v}</span>`}).join("")}
 render(){let p=this.game.placement;if(!p.type){this.hide();return}let d=Settlement.BuildingDefs[p.type],mv=!!p.moving,v=p.hover?p.validate(p.type,p.hover.x,p.hover.y):null,ready=!!v?.ok,reason=p.hover?(v.reason||""):`Tap the map to choose a ${d.footprint.join("×")} location`,road=v?.roadAccess,roadText=road==null?"":`<span class="road-access ${road?"yes":"no"}">ROAD ACCESS ${road?"✓":"○"}</span>`;this.el.innerHTML=`<div class="placement-info"><div class="placement-title"><span>${d.icon}</span><b>${mv?"Move "+d.name:d.name}</b><small>${d.footprint.join("×")} tiles${d.workers?` • ${d.workers} worker`:""}</small></div><div class="placement-costs">${mv?`<span class="placement-cost ok">Relocating — no additional cost</span>`:this.costHTML(d)}</div><div class="placement-status ${ready?"valid":p.hover?"invalid":"waiting"}">${p.hover?(ready?"✓ ":"✕ "):""}${reason}</div>${roadText}</div><div class="placement-actions"><button type="button" class="placement-cancel" data-place-act="cancel">✕ CANCEL</button><button type="button" class="placement-confirm" data-place-act="confirm" ${ready&&!p.committing?"":"disabled"}>${mv?"✓ MOVE HERE":"✓ BUILD"}</button></div>`;this.el.classList.remove("hidden")}
};
