Settlement.UIManager=class{
 constructor(game,root){this.game=game;this.root=root;this.category="Residential";this.renderShell();this.bind()}
 renderShell(){this.root.innerHTML=`<div id="welcome"><div class="scene"></div><div class="smoke"></div><div id="welcome-card" class="medieval-panel"><div style="font-size:14px;letter-spacing:3px">A LIVING MEDIEVAL SETTLEMENT</div><h1>THE SETTLEMENT</h1><p>From one hearth, raise a town that remembers every choice.</p><button id="start" class="wood-button startbtn">START TO ENTER</button></div></div>
 <div id="topbar" class="hidden"></div><div id="questbox" class="medieval-panel hidden"></div><div id="toast-stack"></div><div id="debug" class="hidden"></div>
 <div id="buildmenu" class="medieval-panel hidden"></div><div id="panel" class="medieval-panel hidden"></div><div id="placement-help" class="hidden">Tap a valid tile to place • drag to pan • pinch/wheel to zoom</div>
 <div id="bottomnav" class="hidden">${["BUILD","CITIZENS","QUESTS","TRADE","ARMY","TOWN","MAP","SETTINGS"].map(x=>`<button class="navbtn" data-nav="${x}">${x}</button>`).join("")}</div>`}
 bind(){this.root.querySelector("#start").onclick=()=>this.start();this.root.addEventListener("click",e=>{let n=e.target.closest("[data-nav]");if(n)this.nav(n.dataset.nav);let b=e.target.closest("[data-build]");if(b)this.game.placement.start(b.dataset.build);let a=e.target.closest("[data-act]");if(a)this.action(a.dataset.act,a.dataset.id)}) ;this.game.bus.on("toast",t=>this.toast(t));["resources:changed","xp:changed","day:changed","quest:changed","citizens:changed"].forEach(n=>this.game.bus.on(n,()=>this.refresh()));this.game.bus.on("placement:start",()=>document.querySelector("#placement-help").classList.remove("hidden"));this.game.bus.on("placement:end",()=>document.querySelector("#placement-help").classList.add("hidden"));this.game.bus.on("territory:claimed",()=>{this.toast("🏰 Territory secured! New construction space is now available.");this.game.xp.add(180)})}
 start(){document.querySelector("#welcome").classList.add("hidden");["#topbar","#questbox","#bottomnav"].forEach(s=>document.querySelector(s).classList.remove("hidden"));this.refresh();let save=this.game.save.load();if(save){this.game.save.apply(save);this.toast("Welcome back to your settlement.");this.refresh()}else{this.toast("Welcome, Steward. Begin with a home.");setTimeout(()=>this.toast("Tap BUILD, then choose Cottage."),700)}}
 refresh(){if(!document.querySelector("#topbar")||!document.querySelector("#welcome").classList.contains("hidden"))return;let g=this.game,r=g.resources.v,nxt=g.xp.next(),pct=Math.min(100,g.xp.xp/nxt*100);document.querySelector("#topbar").innerHTML=`${["gold","wood","stone","food"].map(k=>`<div class="resource-pill">${Settlement.ResourceDefs[k].icon} <b>${Math.floor(r[k])}</b></div>`).join("")}<div class="resource-pill">👥 <b>${g.citizens.list.length}/${g.citizens.capacity()}</b></div><div class="resource-pill xp-wrap">Town Lv. <b>${g.xp.level}</b><div class="xpbar"><i style="width:${pct}%"></i></div><small>${g.xp.xp}/${nxt} XP</small></div><div class="day-pill">Day ${g.clock.day} — ${g.clock.season}</div>`;let q=g.quests.current();document.querySelector("#questbox").innerHTML=q?`<h3>📜 ${q.title}</h3><div class="quest-step">${q.text}</div>`:`<h3>📜 Homestead Established</h3><div class="quest-step">Keep expanding your living town.</div>`;if(!document.querySelector("#buildmenu").classList.contains("hidden"))this.renderBuild()}
 nav(n){document.querySelectorAll(".navbtn").forEach(b=>b.classList.toggle("active",b.dataset.nav===n));this.closePanels();if(n==="BUILD"){document.querySelector("#buildmenu").classList.remove("hidden");this.renderBuild()}else if(n==="CITIZENS"){this.panel("Citizens",this.game.citizens.list.map(c=>`<div class="build-card"><div class="build-icon">👤</div><div><b>${c.name}</b><small>${c.job} • Morale ${c.morale}%</small></div></div>`).join("")||"No citizens.")}else if(n==="QUESTS"){let q=this.game.quests.current();this.panel("Quest Journal",q?`<h3>${q.title}</h3><p>${q.text}</p><p>Quests guide growth without locking normal play.</p>`:"All vertical-slice quests complete.")}else if(n==="ARMY"){this.panel("Army & Security",`<p>Archery towers operate at <b>25%</b> without an assigned Archer and full effectiveness with one.</p><p>Bandit scouts appear naturally in the persistent world. There are no waves.</p><button class="wood-button" data-act="spawn">Spawn Debug Bandit</button>`)}else if(n==="TOWN"){this.panel("Town Hall",`<p>Settlement Level <b>${this.game.xp.level}</b></p><p>Population ${this.game.citizens.list.length}/${this.game.citizens.capacity()}</p><p>Claimed expansions: ${this.game.expansion.claimed}</p><button class="wood-button" data-act="save">Save Now</button>`)}else if(n==="MAP"){this.game.camera.tzoom=.42;this.game.camera.clamp();this.toast("Map view: zoomed out.")}else if(n==="SETTINGS"){this.panel("Settings & Development",`<button class="wood-button" data-act="debug">Toggle Debug HUD</button> <button class="wood-button" data-act="save">Save Now</button><p style="margin-top:14px"><button class="wood-button" data-act="reset">Reset Save</button></p>`)}else this.panel(n.charAt(0)+n.slice(1).toLowerCase(),"<p>This system is wired into the production architecture and is scheduled for the next roadmap phase.</p>")}
 renderBuild(){let cats=["Residential","Farming","Production","Military","Civic","Roads"],defs=Object.values(Settlement.BuildingDefs).filter(d=>d.category===this.category&&(!d.requiredTownLevel||this.game.xp.level>=d.requiredTownLevel));document.querySelector("#buildmenu").innerHTML=`<h2>Build</h2><div class="category-tabs">${cats.map(c=>`<button data-act="cat:${c}">${c}</button>`).join("")}</div>${defs.map(d=>`<div class="build-card"><div class="build-icon">${d.icon}</div><div><b>${d.name}</b><small>${d.footprint.join("×")} tiles • ${d.buildTime}s build${d.workers?` • ${d.workers} worker`:""}</small></div><div class="cost">${Object.entries(d.cost).map(([k,v])=>`${Settlement.ResourceDefs[k]?.icon||k} ${v}`).join("<br>")}<br><button class="wood-button" data-build="${d.id}">Place</button></div></div>`).join("")||"<p>Nothing unlocked here yet.</p>"}`}
 inspect(b){let d=Settlement.BuildingDefs[b.type],extra="";if(b.type==="farm"){let p=this.game.farms.plots.get(b.id);extra=p?.state==="ready"?`<button class="wood-button" data-act="harvest" data-id="${b.id}">Harvest Wheat</button>`:p?.state==="growing"?`<p>Wheat growth: ${Math.floor(p.progress*100)}%</p>`:`<button class="wood-button" data-act="plant" data-id="${b.id}">Plant Wheat</button>`}if(d.workers)extra+=`<p>Workers: ${b.workers||0}/${d.workers}</p>${(b.workers||0)<d.workers?`<button class="wood-button" data-act="assign" data-id="${b.id}">Assign Citizen</button>`:""}`;if(b.type==="cottage"&&b.level===1)extra+=`<h3>Upgrade Preview</h3><p>Level 2 • Capacity 4</p><p>${Object.entries(d.upgrade.cost).map(([k,v])=>`${Settlement.ResourceDefs[k]?.icon||k} ${Math.floor(this.game.resources.v[k]||0)}/${v}`).join(" • ")}</p>`;this.panel(d.name,`<p>Level ${b.level} • ${b.complete?"Complete":"Under construction"}</p>${extra}`)}
 panel(title,html){let p=document.querySelector("#panel");p.innerHTML=`<h2>${title}</h2>${html}`;p.classList.remove("hidden")}
 closePanels(){document.querySelector("#buildmenu")?.classList.add("hidden");document.querySelector("#panel")?.classList.add("hidden")}
 action(a,id){if(a.startsWith("cat:")){this.category=a.slice(4);this.renderBuild();return}let b=id?this.game.buildings.byId(+id):null;if(a==="plant")this.game.farms.plant(b);if(a==="harvest")this.game.farms.harvest(b);if(a==="assign"){if(this.game.citizens.assign(b))this.toast("Citizen assigned.");else this.toast("No unassigned adult is available.")}if(a==="spawn")this.game.enemies.spawn();if(a==="save"){this.game.save.save();this.toast("Game saved.")}if(a==="debug"){document.querySelector("#debug").classList.toggle("hidden")}if(a==="reset"&&confirm("Reset this prototype save?"))this.game.save.reset();this.refresh();if(b)this.inspect(b)}
 toast(t){let s=document.querySelector("#toast-stack"),d=document.createElement("div");d.className="toast";d.textContent=t;s.appendChild(d);setTimeout(()=>d.remove(),3300)}
 showOffline(off){let gain=Object.entries(off.gain).filter(([,v])=>v>0).map(([k,v])=>`+${v} ${Settlement.ResourceDefs[k]?.name||k}`).join("<br>")||"The town rested quietly.";let d=document.createElement("div");d.className="modal-backdrop";d.innerHTML=`<div class="modal medieval-panel"><h2>WELCOME BACK</h2><p>While you were away:</p><p>${gain}</p><button class="wood-button">Return to Town</button></div>`;d.querySelector("button").onclick=()=>d.remove();this.root.appendChild(d)}
 updateDebug(){let el=document.querySelector("#debug");if(el.classList.contains("hidden"))return;el.textContent=`FPS ${this.game.fps.toFixed(0)}\nBuildings ${this.game.buildings.list.length}\nCitizens ${this.game.citizens.list.length}\nEnemies ${this.game.enemies.list.length}\nChunks ${this.game.chunks.active.length}\nSave ${this.game.save.status}`;}
};
