/* Dedicated, always-visible Wonder catalogue. Locked monuments are motivation, not hidden content. */
if(!document.querySelector('link[href*="wonders.css"]')){let wonderCSS=document.createElement("link");wonderCSS.rel="stylesheet";wonderCSS.href="styles/wonders.css?v=0.18.0-wonders";document.head.appendChild(wonderCSS)}
(()=>{let P=Settlement.UIManager?.prototype;if(!P||P.__wondersUIPatched)return;P.__wondersUIPatched=true;let baseRender=P.renderBuild,baseSig=P.buildSignature,baseInspect=P.inspect;
 const fmt=n=>Math.floor(Number(n)||0).toLocaleString();
 P.wonderCard=function(d){let g=this.game,status=g.wonders.status(d.id),b=g.wonders.building(d.id),req=g.wonders.requirements(d.id),cost=Object.entries(d.cost||{}).map(([k,v])=>`${Settlement.ResourceDefs[k]?.icon||k} ${fmt(v)}`).join(" • "),stage=b&&!b.complete?g.wonders.stage(b):null,button=status==="AVAILABLE"?`<button class="wood-button wonder-build" data-build="${d.id}">BUILD WONDER</button>`:"";return `<article class="wonder-card ${status.toLowerCase().replace(" ","-")}"><div class="wonder-preview wonder-${d.visualType||"future"}"><span>${d.icon||"✦"}</span></div><div class="wonder-copy"><div class="wonder-head"><div><h3>${d.name}</h3><small>${d.theme}</small></div><b class="wonder-status">${status}</b></div><p>${d.description}</p>${stage?`<div class="wonder-progress"><i style="width:${Math.floor((b.progress||0)*100)}%"></i></div><small>${stage.label} • ${Math.floor((b.progress||0)*100)}%</small>`:""}<div class="wonder-reqs">${req.map(r=>`<div class="${r.complete?"done":""}"><span>${r.complete?"✓":"○"} ${r.revealed?r.label:"??? Secret Requirement"}</span><b>${r.revealed?`${fmt(r.value)} / ${fmt(r.target)}`:"???"}</b></div>`).join("")}</div>${d.future?`<p class="wonder-cost">Requirements Unknown</p>`:`<p class="wonder-cost"><b>Cost:</b> ${cost}<br><b>Footprint:</b> ${d.footprint[0]}×${d.footprint[1]} • <b>Project:</b> ${Math.round(d.buildTime/60)} min</p>${button}`}</div></article>`};
 P.renderBuild=function(){if(this.category!=="Wonders")return baseRender.call(this);let menu=document.querySelector("#buildmenu"),cats=["Residential","Farming","Production","Military","Civic","Roads","Wonders"];menu.innerHTML=`<div class="panel-header"><h2>Wonders of the Gods</h2><button class="panel-close" data-act="close" aria-label="Close">×</button></div><div class="panel-scroll"><div class="category-tabs">${cats.map(c=>`<button data-act="cat:${c}">${c}</button>`).join("")}</div><p class="wonder-intro">Monumental, unique projects. Unlock them through the settlement you build.</p>${Object.values(Settlement.WonderDefs).map(d=>this.wonderCard(d)).join("")}</div>`;this.buildSig=this.buildSignature()};
 P.buildSignature=function(){if(this.category!=="Wonders")return baseSig.call(this);return"Wonders|"+Object.keys(Settlement.WonderDefs).map(id=>{let b=this.game.wonders.building(id);return id+":"+this.game.wonders.status(id)+":"+Math.floor((b?.progress||0)*100)}).join(",")};
 P.inspect=function(b){let out=baseInspect.call(this,b);if(Settlement.BuildingDefs[b?.type]?.wonder){let panel=document.querySelector("#panel"),d=Settlement.WonderDefs[b.type],s=this.game.wonders.stage(b);if(panel)panel.innerHTML=`<div class="panel-header"><h2>${d.icon} ${d.name}</h2><button class="panel-close" data-act="close">×</button></div><div class="panel-scroll"><p>${d.description}</p><h3>${b.complete?"COMPLETED":s.label}</h3>${b.complete?"":`<div class="wonder-progress"><i style="width:${Math.floor((b.progress||0)*100)}%"></i></div><p>${Math.floor((b.progress||0)*100)}% complete</p>`}<p>Unique permanent Wonder • ${d.footprint[0]}×${d.footprint[1]} tiles</p></div>`}return out};
})();
(()=>{let P=Settlement.UIManager?.prototype;if(!P||P.__wonderTabPatched)return;P.__wonderTabPatched=true;let render=P.renderBuild;P.renderBuild=function(){let out=render.call(this),tabs=document.querySelector("#buildmenu .category-tabs");if(tabs&&!tabs.querySelector('[data-act="cat:Wonders"]'))tabs.insertAdjacentHTML("beforeend",'<button data-act="cat:Wonders">Wonders</button>');return out}})();
