/* Blood & Plunder Gothic World Identity — Three.js presentation only. */
import * as THREE from "../../vendor/three/three.module.min.js";
import { IndustryWorld3D } from "./IndustryWorld3D.js";

export class BloodWorld3D extends IndustryWorld3D{
 constructor(game,canvas){super(game,canvas);this._bloodGroundKey=null;this._bloodTmp=new THREE.Color()}
 init(){let ok=super.init();if(!ok)return false;this.applyBloodScene();this.applyBloodMaterials();return true}
 applyBloodScene(){this.scene.background.setHex(0x14121a);if(this.scene.fog)this.scene.fog.color.setHex(0x1b1822);if(this.hemi){this.hemi.color.setHex(0x9aa3b2);this.hemi.groundColor.setHex(0x211b24)}if(this.sun)this.sun.color.setHex(0xd6d2dc);if(this.fill)this.fill.color.setHex(0x66577c);if(this.border?.material)this.border.material.color.setHex(0xb1a6bb);if(this.gwTree?.material)this.gwTree.material.color.setHex(0x29362f);if(this.gwStone?.material)this.gwStone.material.color.setHex(0x626872);if(this.gwWood?.material)this.gwWood.material.color.setHex(0x3b3033);if(this.gwFoliage?.material)this.gwFoliage.material.color.setHex(0x39463d);if(this.gwPulseMat)this.gwPulseMat.color.setHex(0x88709b);if(this.gwCompleteMat)this.gwCompleteMat.color.setHex(0xb5a8bd)}
 colorForKey(key){key=String(key||"").toLowerCase();if(key.includes("glow"))return null;if(key.includes("hay")||key.includes("crop"))return null;if(key.includes("burg")||key.includes("cloth")||key.includes("mkt-a"))return 0x64253a;if(key.includes("mkt-c"))return 0x4b3c62;if(key.includes("gold"))return 0x9e8b73;if(key.includes("stone"))return 0x6f747d;if(key.includes("slate")||key.includes("dark")||key.includes("roof"))return 0x292932;if(key.includes("wood")||key.includes("timber")||key.includes("cart"))return 0x3c3033;if(key.includes("iron")||key.includes("metal"))return 0x484b53;if(key.includes("plaster"))return 0xb8b4ae;if(key.includes("fol"))return 0x39463d;if(key.includes("rut")||key.includes("dirt"))return 0x454044;return null}
 applyBloodMaterials(){for(const [key,m] of this.matCache||[]){let hex=this.colorForKey(key);if(hex!=null&&m?.color)m.color.setHex(hex)}this.applyBloodScene()}
 buildStructure(b){let g=super.buildStructure(b);this.applyBloodMaterials();return g}
 refreshGround(){super.refreshGround();if(this._bloodGroundKey===this.groundKey)return;this._bloodGroundKey=this.groundKey;let d=this.groundTex?.image?.data;if(!d)return;for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2],avg=(r+g+b)/3;d[i]=Math.max(0,Math.min(255,avg*.34+r*.48+10));d[i+1]=Math.max(0,Math.min(255,avg*.38+g*.43+6));d[i+2]=Math.max(0,Math.min(255,avg*.39+b*.42+14))}this.groundTex.needsUpdate=true}
 syncTime(){super.syncTime();let n=this.game.gothicWorld?.nightFactor()||0;this._bloodTmp.setHex(0x23242a).lerp(new THREE.Color(0x121019),n*.78);this.scene.background.copy(this._bloodTmp);if(this.scene.fog){this._bloodTmp.setHex(0x2b2b32).lerp(new THREE.Color(0x1b1624),n*.72);this.scene.fog.color.copy(this._bloodTmp)}if(this.hemi){this.hemi.color.setHex(n>.45?0x77839a:0xa7acb5);this.hemi.groundColor.setHex(n>.45?0x211b28:0x343239)}if(this.sun){this.sun.color.setHex(n>.5?0xb7bfd1:0xd7d2d6)}if(this.fill)this.fill.color.setHex(0x66577c)}
 render(){if(!this.ok)return;this.applyBloodMaterials();super.render()}
}
