/* Gothic Civic & Commerce 3D presentation. Simulation remains authoritative. */
import * as THREE from "../../vendor/three/three.module.min.js";
import {MilitaryFortificationWorld3D} from "./MilitaryFortificationWorld3D.js";
import {civicVariantFor} from "./CivicCommerceVisualDefs.js";
const T=64,CIVIC=new Set(["warehouse","mainHall","market"]);
export class CivicCommerceWorld3D extends MilitaryFortificationWorld3D{
 constructor(game,canvas){super(game,canvas);this._commerceDecorDirty=true;this._commerceSig=""}
 init(){const ok=super.init();if(!ok)return false;this.commerceDecorRoot=new THREE.Group();this.scene.add(this.commerceDecorRoot);for(const ev of["commerce:changed","building:created","building:removed","building:complete","building:upgraded"])this.game.bus.on(ev,()=>{this._commerceDecorDirty=true});return true}
 civicMaterials(){return{
  stone:this.mat("civic-stone",0x66666b,{roughness:.96}),dark:this.mat("civic-dark",0x30343b,{roughness:.96}),timber:this.mat("civic-timber",0x49352d,{roughness:.96}),
  timber2:this.mat("civic-timber-worn",0x604536,{roughness:.98}),iron:this.mat("civic-iron",0x3e4248,{metalness:.46,roughness:.68}),slate:this.mat("civic-slate",0x343946,{roughness:.94}),
  burg:this.mat("civic-burgundy",0x5c2538,{roughness:.9}),gold:this.mat("civic-gold",0x9a7d4b,{metalness:.3,roughness:.7}),soil:this.mat("civic-yard",0x413832,{roughness:1}),
  glow:this.mat("civic-glow",0xd79345,{emissive:0xc87432,ei:.8,roughness:.8}),cloth:this.mat("civic-cloth",0x62404a,{roughness:1}),sack:this.mat("civic-sack",0x88755d,{roughness:1})}}
 buildStructure(b){if(!b?.complete||!CIVIC.has(b.type))return super.buildStructure(b);const v=civicVariantFor(b);if(!v)return super.buildStructure(b);const g=new THREE.Group(),m=this.civicMaterials(),t=this.tierOf(b.level||1);if(b.type==="warehouse")this.buildWarehouse(g,b,t,m,v);else if(b.type==="mainHall")this.buildMainHall(g,b,t,m,v);else this.buildMarket(g,b,t,m,v);g.position.set((b.x+b.w/2)*T,0,(b.y+b.h/2)*T);return g}
 buildWarehouse(g,b,t,m,v){const w=b.w*T,d=b.h*T,h=52+t*5;this.part(this.box(w*.94,8,d*.9),m.dark,0,4,0,g);this.part(this.box(w*.78,h*.64,d*.68),m.stone,0,10+h*.32,0,g);for(const x of[-w*.34,w*.34])this.part(this.box(8,h*.7,8),m.timber,x,12+h*.35,d*.28,g);this.part(this.prism(w*.86,h*.3,d*.76),m.slate,0,h*.77,0,g);const dx=v.mirror?-w*.19:w*.19;this.part(this.box(34,42,7),m.timber2,dx,27,d*.35,g);this.part(this.box(52,5,22),m.timber,dx,49,d*.43,g);for(let i=0;i<Math.min(6,v.clutter+2);i++){const x=-w*.32+(i%3)*22,z=d*.34-Math.floor(i/3)*18;this.part(this.box(15,15,15),i%2?m.timber2:m.sack,x,8,z,g)}this.part(this.box(5,14,5),m.glow,-dx,25,d*.37,g);if(t>=3)this.part(this.box(w*.7,5,d*.7),m.iron,0,h*.56,0,g)}
 buildMainHall(g,b,t,m,v){const w=b.w*T,d=b.h*T,h=96+t*8;this.part(this.box(w*.96,13,d*.92),m.dark,0,6.5,0,g);this.part(this.box(w*.72,h*.54,d*.62),m.stone,0,14+h*.27,0,g);this.part(this.prism(w*.8,h*.3,d*.7),m.slate,0,h*.73,0,g);for(const s of[-1,1]){this.part(this.box(w*.15,h*.72,d*.16),m.stone,s*w*.39,h*.36,-d*.26,g);this.part(this.cone(w*.11,h*.22,4),m.slate,s*w*.39,h*.83,-d*.26,g);this.part(this.box(5,40,12),m.burg,s*w*.29,58,d*.34,g)}this.part(this.box(34,50,7),m.timber2,0,31,d*.32,g);for(const x of[-w*.22,0,w*.22]){this.part(this.box(17,24,5),m.dark,x,49,d*.32,g);this.part(this.box(12,19,4),m.glow,x,49,d*.33,g)}this.part(this.box(w*.42,5,20),m.stone,0,4,d*.44,g);this.part(this.box(26,24,5),m.timber2,v.bannerSide*w*.31,18,d*.43,g);if(t>=3)for(const s of[-1,1])this.part(this.box(8,18,8),m.gold,s*w*.2,h*.84,0,g)}
 buildMarket(g,b,t,m,v){const w=b.w*T,d=b.h*T;this.part(this.box(w*.94,3,d*.92),m.stone,0,1.7,0,g);for(let i=0;i<3;i++){const x=-w*.27+i*w*.27,z=(i%2?-.08:.12)*d;this.part(this.box(w*.2,20,d*.26),m.timber2,x,10,z,g);for(const sx of[-1,1])this.part(this.box(4,28,4),m.timber,x+sx*w*.09,14,z-d*.13,g);this.part(this.box(w*.23,4,d*.3),i%2?m.burg:m.cloth,x,29,z,g);for(let c=0;c<2;c++)this.part(this.box(11,11,11),m.timber,-w*.32+i*w*.29+c*13,6,d*.35,g)}for(const s of[-1,1])this.part(this.box(5,15,5),m.glow,s*w*.36,16,-d*.31,g);if(t>=2)this.part(this.box(5,38,12),m.burg,v.bannerSide*w*.4,38,d*.25,g)}
 syncCommerceDecor(){const market=this.game.buildings.list.find(b=>b?.complete&&b.type==="market"),active=!!this.game.commerce?.state?.active,sig=(market?market.id+":"+market.x+","+market.y:"none")+"|"+(active?1:0);if(sig===this._commerceSig&&!this._commerceDecorDirty)return;this._commerceSig=sig;this._commerceDecorDirty=false;while(this.commerceDecorRoot.children.length)this.commerceDecorRoot.remove(this.commerceDecorRoot.children[this.commerceDecorRoot.children.length-1]);if(!market||!active)return;const m=this.civicMaterials(),g=new THREE.Group();g.position.set((market.x+market.w/2)*T,0,(market.y+market.h/2)*T);for(let i=0;i<4;i++){this.part(this.box(12,12,12),i%2?m.sack:m.timber2,-55+i*26,7,72-(i%2)*14,g)}this.part(this.box(70,5,5),m.burg,0,43,-70,g);for(const x of[-32,32])this.part(this.box(5,44,5),m.timber,x,22,-70,g);this.commerceDecorRoot.add(g)}
 render(){if(!this.ok)return;this.syncCommerceDecor();super.render()}
}
