/* Gothic World Evolution 3D presentation.
 * Extends the stable mirror only; gameplay remains owned by the existing simulation.
 */
import * as THREE from "../../vendor/three/three.module.min.js";
import { StableWorld3D } from "./World3DStability.js";

const T=64,MAX_TREES=1800,MAX_STONE=900,MAX_WOOD=900,MAX_FOLIAGE=700,MAX_LIFE=48;

export class GothicWorld3D extends StableWorld3D{
 constructor(game,canvas){super(game,canvas);this._gothicDirty=true;this._gothicM4=new THREE.Matrix4();this._gothicColor=new THREE.Color()}
 init(){let ok=super.init();if(!ok)return false;this.buildGothicDressing();this.buildGothicEffects();for(const ev of["building:created","building:removed","building:complete","building:upgraded","building:moved","territory:claimed"])this.game.bus.on(ev,()=>{this._gothicDirty=true});return true}
 tierOf(level){return this.game.gothicWorld?.tierNumber(level)||super.tierOf(level)}
 signature(b){let sig=super.signature(b);if(b.type==="road")sig+="|r"+(this.game.gothicWorld?.roadMask(b.x,b.y)||0);sig+="|g"+this.tierOf(b.level||1);if(b.upgrading)sig+="|u"+Math.round((b.upgrading.progress||0)*4);return sig}
 buildStructure(b){let g=super.buildStructure(b),gw=this.game.gothicWorld,tier=this.tierOf(b.level||1);if(!gw)return g;let w=b.w*T,d=b.h*T,stone=this.mat("gw-stone",0x77766f),wood=this.mat("gw-wood",0x6b4a30),dark=this.mat("gw-dark",0x303239),burg=this.mat("gw-burg",0x5b252b),gold=this.mat("gw-gold",0x9c8042,{metalness:.35,roughness:.5}),glow=this.mat("gw-glow",0xf1b85a,{emissive:0xf1a744,ei:1.15}),fol=this.mat("gw-fol",0x445c38);
 if(!b.complete||b.upgrading){let st=gw.constructionStage(b);if(st>=1){for(const sx of[-1,1])this.part(this.box(4,44,4),wood,sx*w*.34,24,d*.34,g);this.part(this.box(w*.72,4,4),wood,0,30,d*.34,g)}if(st>=2)this.part(this.prism(w*.68,18,d*.6),dark,0,54,0,g);if(st>=3){this.part(this.box(18,10,14),wood,-w*.3,5,d*.38,g);this.part(this.box(13,8,13),stone,-w*.15,4,d*.38,g)}if(!b.complete)return g}
 if(b.type==="road"){let m=gw.roadMask(b.x,b.y),rut=this.mat("gw-rut",0x352f27);if(m&1||m&4||(!m)){this.part(this.box(3,.8,T*.9),rut,-7,2,0,g);this.part(this.box(3,.8,T*.9),rut,7,2,0,g)}if(m&2||m&8){this.part(this.box(T*.9,.8,3),rut,0,2,-7,g);this.part(this.box(T*.9,.8,3),rut,0,2,7,g)}return g}
 if(tier>=2&&b.type==="cottage"){for(const x of[-w*.38,w*.38])this.part(this.box(3,12,d*.65),wood,x,6,d*.05,g);if(tier>=3){this.part(this.box(w*.54,10,d*.45),stone,0,5,0,g);this.part(this.prism(w*.56,18,d*.48),dark,0,68,0,g)}if(tier>=4)this.part(this.box(6,12,4),glow,w*.3,24,d*.37,g)}
 if(b.type==="quarry"){for(let i=0;i<tier+1;i++)this.part(this.box(13+i*2,7+i,12),stone,-w*.3+i*17,4,d*.28,g);if(tier>=2){this.part(this.box(5,46,5),wood,-w*.28,23,-d*.15,g);this.part(this.box(w*.48,5,5),wood,-w*.05,44,-d*.15,g)}if(tier>=3){this.part(this.box(4,38,4),wood,w*.24,20,-d*.24,g);this.part(this.box(4,4,d*.42),wood,w*.24,39,-d*.06,g)}if(tier>=4)this.part(this.box(w*.7,4,d*.12),gold,0,10,d*.34,g)}
 if(b.type==="lumber"){for(let i=0;i<tier+1;i++)this.part(this.box(w*.5,7,7),wood,-w*.06,5+i*8,d*.34-i*2,g);if(tier>=3){for(const x of[-w*.3,w*.3])this.part(this.box(5,34,5),wood,x,17,-d*.2,g);this.part(this.box(w*.68,5,5),wood,0,32,-d*.2,g)}}
 if(b.type==="warehouse"){for(let i=0;i<Math.min(6,tier*2);i++)this.part(this.box(13,13,13),wood,-w*.3+(i%3)*15,6.5,d*.36-Math.floor(i/3)*15,g);if(tier>=3){this.part(this.box(5,46,5),wood,w*.33,23,-d*.2,g);this.part(this.box(w*.38,5,5),wood,w*.15,43,-d*.2,g)}if(tier>=4)this.part(this.box(5,20,12),burg,-w*.34,48,d*.22,g)}
 if(b.type==="archery"){if(tier>=2){for(const x of[-w*.31,w*.31])this.part(this.box(5,18,5),glow,x,80,d*.31,g)}if(tier>=3)for(const x of[-w*.28,w*.28])this.part(this.box(10,16,10),stone,x,72,-d*.3,g);if(tier>=4)this.part(this.box(5,34,14),burg,0,108,d*.32,g)}
 if(b.type==="mainHall"){if(tier>=2){for(const x of[-w*.3,w*.3])this.part(this.box(6,18,6),glow,x,20,d*.4,g);this.part(this.box(w*.62,5,d*.12),stone,0,4,d*.43,g)}if(tier>=3){for(const x of[-w*.34,w*.34]){this.part(this.box(10,20,10),stone,x,10,d*.36,g);this.part(this.cone(8,10,6),stone,x,25,d*.36,g)}}if(tier>=4){for(const x of[-w*.2,w*.2])this.part(this.box(5,34,14),burg,x,82,d*.38,g);this.part(this.box(w*.5,4,d*.5),gold,0,8,0,g)}}
 if(b.type==="farm"&&tier>=2){this.part(this.box(4,26,4),wood,w*.28,13,d*.25,g);this.part(this.box(22,4,4),wood,w*.28,18,d*.25,g);if(tier>=3)this.part(this.cone(9,14,4),this.mat("gw-hay",0x9a8046),-w*.28,7,d*.3,g)}
 if(b.type==="mason"){for(let i=0;i<tier;i++)this.part(this.box(14,7,12),stone,-w*.25+i*15,4,d*.34,g);if(tier>=3)this.part(this.box(w*.52,4,4),wood,0,36,-d*.28,g)}
 if(b.type==="training"){this.part(this.box(5,28,5),wood,w*.25,14,d*.22,g);this.part(this.box(18,4,4),wood,w*.25,22,d*.22,g);if(tier>=3)this.part(this.box(5,24,12),burg,-w*.3,24,d*.28,g)}
 if((b.type==="bakery"||b.type==="mill")&&tier>=2)this.part(this.box(6,12,4),glow,-w*.25,25,d*.36,g);
 if(tier>=3&&["cottage","mainHall","warehouse","bakery"].includes(b.type)){for(const x of[-w*.28,w*.28])this.part(this.box(8,5,8),fol,x,3,d*.42,g)}return g}
 buildGothicDressing(){let mk=(geo,mat,cap)=>{let m=new THREE.InstancedMesh(geo,mat,cap);m.count=0;m.frustumCulled=false;m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.scene.add(m);return m};this.gwTree=mk(new THREE.ConeGeometry(13,32,6),new THREE.MeshLambertMaterial({color:0x30452f}),MAX_TREES);this.gwStone=mk(new THREE.DodecahedronGeometry(8,0),new THREE.MeshLambertMaterial({color:0x686962}),MAX_STONE);this.gwWood=mk(new THREE.BoxGeometry(12,6,8),new THREE.MeshLambertMaterial({color:0x68482e}),MAX_WOOD);this.gwFoliage=mk(new THREE.SphereGeometry(7,5,4),new THREE.MeshLambertMaterial({color:0x455d38}),MAX_FOLIAGE)}
 syncGothicDressing(){if(!this._gothicDirty)return;this._gothicDirty=false;let gw=this.game.gothicWorld,ex=this.game.expansion;if(!gw)return;let minx=Settlement.Config.WORLD_W,maxx=0,miny=Settlement.Config.WORLD_H,maxy=0;for(const r of ex.claimedRects){minx=Math.min(minx,r.x);miny=Math.min(miny,r.y);maxx=Math.max(maxx,r.x+r.w);maxy=Math.max(maxy,r.y+r.h)}minx=Math.max(0,minx-24);miny=Math.max(0,miny-24);maxx=Math.min(Settlement.Config.WORLD_W,maxx+24);maxy=Math.min(Settlement.Config.WORLD_H,maxy+24);let nt=0,ns=0,nw=0,nf=0;for(let y=miny;y<maxy;y++)for(let x=minx;x<maxx;x++){let claimed=ex.isClaimed(x,y),k=gw.wildernessKind(x,y,claimed);if(!k)continue;let px=x*T+T*(.2+.6*gw.hash(x,y,21)),pz=y*T+T*(.2+.6*gw.hash(x,y,22)),sc=claimed?.72:1;if((k==="tree"||k==="deadTree")&&nt<MAX_TREES){this._gothicM4.makeScale(sc,sc,sc);this._gothicM4.setPosition(px,16*sc,pz);this.gwTree.setMatrixAt(nt++,this._gothicM4)}else if((k==="rock"||k==="gravestone"||k==="ruin")&&ns<MAX_STONE){this._gothicM4.makeScale(sc,sc,sc);this._gothicM4.setPosition(px,5*sc,pz);this.gwStone.setMatrixAt(ns++,this._gothicM4)}else if((k==="stump")&&nw<MAX_WOOD){this._gothicM4.makeTranslation(px,3,pz);this.gwWood.setMatrixAt(nw++,this._gothicM4)}else if(nf<MAX_FOLIAGE){this._gothicM4.makeScale(sc,sc*.7,sc);this._gothicM4.setPosition(px,5*sc,pz);this.gwFoliage.setMatrixAt(nf++,this._gothicM4)}}for(const b of this.game.buildings.list){if(!b.complete||b.type==="road")continue;let kinds=gw.propKinds(b);for(let i=0;i<kinds.length;i++){let p=gw.propPoint(b,i),k=kinds[i],mesh=null,idx=0;if(["stonePile","rubble","cutStone","statue"].includes(k)&&ns<MAX_STONE){mesh=this.gwStone;idx=ns++}else if(["firewood","logs","timberRack","barrel","barrels","crates","sawhorse","workbench","weaponRack","scaffold","hoist","cart"].includes(k)&&nw<MAX_WOOD){mesh=this.gwWood;idx=nw++}else if(["garden","planter","hay","basket","sacks","grain"].includes(k)&&nf<MAX_FOLIAGE){mesh=this.gwFoliage;idx=nf++}if(mesh){this._gothicM4.makeTranslation(p.x,mesh===this.gwStone?6:mesh===this.gwFoliage?5:4,p.y);mesh.setMatrixAt(idx,this._gothicM4)}}}this.gwTree.count=nt;this.gwStone.count=ns;this.gwWood.count=nw;this.gwFoliage.count=nf;for(const m of[this.gwTree,this.gwStone,this.gwWood,this.gwFoliage])m.instanceMatrix.needsUpdate=true}
 buildGothicEffects(){this.gwPulseMat=new THREE.MeshBasicMaterial({color:0xd9b765,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false});this.gwPulse=new THREE.Mesh(new THREE.RingGeometry(18,24,48).rotateX(-Math.PI/2),this.gwPulseMat);this.gwPulse.visible=false;this.scene.add(this.gwPulse);this.gwCompleteMat=new THREE.MeshBasicMaterial({color:0xe5d19a,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false});this.gwComplete=new THREE.Mesh(new THREE.RingGeometry(10,14,32).rotateX(-Math.PI/2),this.gwCompleteMat);this.gwComplete.visible=false;this.scene.add(this.gwComplete);this.gwLifeGeo=new THREE.BoxGeometry(2.5,2.5,2.5);this.gwLifeMat=new THREE.MeshBasicMaterial({vertexColors:true});this.gwLife=new THREE.InstancedMesh(this.gwLifeGeo,this.gwLifeMat,MAX_LIFE);this.gwLife.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.gwLife.frustumCulled=false;this.scene.add(this.gwLife)}
 syncGothicEffects(){let gw=this.game.gothicWorld,p=gw?.claimPulseState();if(p){let cx=(p.rect.x+p.rect.w/2)*T,cz=(p.rect.y+p.rect.h/2)*T,scale=1+(p.rect.w*T/45)*p.t;this.gwPulse.visible=true;this.gwPulse.position.set(cx,2.6,cz);this.gwPulse.scale.setScalar(scale);this.gwPulseMat.opacity=(1-p.t)*.65}else this.gwPulse.visible=false;let cp=gw?.completionPulseState();if(cp){this.gwComplete.visible=true;this.gwComplete.position.set((cp.x+cp.w/2)*T,3,(cp.y+cp.h/2)*T);this.gwComplete.scale.setScalar(1+4*cp.t);this.gwCompleteMat.opacity=(1-cp.t)*.55}else this.gwComplete.visible=false;let night=gw?.nightFactor()||0,now=performance.now()/1000,n=0,cam=this.game.camera;this.gwLifeMat.color.setHex(night>.5?0xd8d27a:0x242724);for(let i=0;i<MAX_LIFE;i++){let a=i*.618*6.283+now*(night>.5?.17:.1),rad=120+(i%8)*55,x=cam.x+Math.cos(a)*rad,z=cam.y+Math.sin(a*.83)*rad,y=night>.5?6+Math.sin(now*1.7+i)*5:75+Math.sin(now*.8+i)*18;this._gothicM4.makeTranslation(x,y,z);this.gwLife.setMatrixAt(n++,this._gothicM4)}this.gwLife.count=n;this.gwLife.instanceMatrix.needsUpdate=true}
 syncTime(){super.syncTime();let n=this.game.gothicWorld?.nightFactor()||0;this.renderer.toneMappingExposure=1.06-.08*n;let m=this.matCache.get("gw-glow:15841370:15836996");if(m&&"emissiveIntensity" in m)m.emissiveIntensity=.35+1.25*n}
 applyQuality(){super.applyQuality();for(const m of[this.gwTree,this.gwStone,this.gwWood,this.gwFoliage])if(m)m.castShadow=this.rich}
 render(){if(!this.ok)return;this.syncGothicDressing();this.syncGothicEffects();super.render()}
}
