/* Guard & Garrison 3D presentation. Simulation remains in GuardSystem/SecuritySystem. */
import * as THREE from "../../vendor/three/three.module.min.js";
import { BloodWorld3D } from "./BloodWorld3D.js";
const T=64,MAX_GUARD_PROPS=64;
export class GuardWorld3D extends BloodWorld3D{
 constructor(game,canvas){super(game,canvas);this._jobColor.Guard=0x6b3048;this._guardM4=new THREE.Matrix4()}
 init(){let ok=super.init();if(!ok)return false;this.buildGuardProps();return true}
 buildStructure(b){let g=super.buildStructure(b);if(!b.complete||b.type!=="barracks")return g;let w=b.w*T,d=b.h*T,t=this.tierOf(b.level||1),stone=this.mat("guard-stone",0x666a73),dark=this.mat("guard-dark",0x25252d),wood=this.mat("guard-wood",0x352b2f),burg=this.mat("guard-burgundy",0x65283e),metal=this.mat("guard-metal",0x898792,{metalness:.45,roughness:.48}),glow=this.mat("guard-glow",0xe0a153,{emissive:0xc9783f,ei:.75});this.part(this.box(w*.76,42,d*.64),stone,0,21,0,g);this.part(this.prism(w*.84,24,d*.72),dark,0,55,0,g);for(const x of[-w*.31,w*.31])this.part(this.box(6,44,6),wood,x,22,d*.3,g);this.part(this.box(w*.52,5,5),wood,0,43,d*.3,g);for(let i=0;i<Math.min(4,t+1);i++){this.part(this.box(13,3,13),metal,-w*.24+i*16,13,d*.36,g);this.part(this.box(3,22,3),metal,-w*.24+i*16,20,d*.36,g)}this.part(this.box(5,30,14),burg,w*.34,43,d*.28,g);if(t>=3)this.part(this.box(5,30,14),burg,-w*.34,43,d*.28,g);if(t>=2)for(const x of[-w*.28,w*.28])this.part(this.box(6,10,6),glow,x,20,d*.39,g);return g}
 buildGuardProps(){let swordGeo=new THREE.BoxGeometry(2,15,2),swordMat=new THREE.MeshLambertMaterial({color:0xb7b3bd}),lanternGeo=new THREE.SphereGeometry(3.5,6,4),lanternMat=new THREE.MeshBasicMaterial({color:0xe2a65a});this.guardSwords=new THREE.InstancedMesh(swordGeo,swordMat,MAX_GUARD_PROPS);this.guardLanterns=new THREE.InstancedMesh(lanternGeo,lanternMat,MAX_GUARD_PROPS);for(const m of[this.guardSwords,this.guardLanterns]){m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);m.frustumCulled=false;this.scene.add(m)}}
 syncGuardProps(){let n=0,l=0;for(const c of this.game.guards?.guards?.()||[]){if(n>=MAX_GUARD_PROPS)break;this._guardM4.makeTranslation(c.x+6,15,c.y);this.guardSwords.setMatrixAt(n++,this._guardM4);let p=this.game.guards.presentation(c);if(p?.mode==="night-watch"&&l<MAX_GUARD_PROPS){this._guardM4.makeTranslation(c.x-6,14,c.y);this.guardLanterns.setMatrixAt(l++,this._guardM4)}}this.guardSwords.count=n;this.guardLanterns.count=l;this.guardSwords.instanceMatrix.needsUpdate=true;this.guardLanterns.instanceMatrix.needsUpdate=true}
 render(){if(!this.ok)return;this.syncGuardProps();super.render()}
}
