/* First Living World checkpoint. Presentation only; simulation remains authoritative. */
import * as THREE from "../../vendor/three/three.module.min.js";
import {LumberQuarryShowcaseWorld3D} from "./LumberQuarryShowcaseWorld3D.js";
import {LivingWorldPresentationState} from "../presentation/LivingWorldPresentationState.js";
import {EnvironmentalLifeManager} from "./EnvironmentalLifeManager.js";
const T=64,MAX_SPRITES=96,MAX_DOORS=40,MAX_BUBBLES=3;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class LivingWorldAtmosphereWorld3D extends LumberQuarryShowcaseWorld3D{
 constructor(game,canvas){super(game,canvas);this.live=new LivingWorldPresentationState(game);this.livingSprites=new Map();this.livingTextures=new Map();this.doors=new Map();this.smoke=[];this.fx=[];this.lastBubbleAt=0;this.bubbles=[];this._tapStart=null;this._audioNext={}}
 init(){const ok=super.init();if(!ok)return false;this.buildLivingCitizens();this.buildLivingDoors();this.buildLivingEffects();this.environment=new EnvironmentalLifeManager(this).init();this.installOverlay();this.installCitizenTap();if(this.citizenMesh)this.citizenMesh.visible=false;if(this.heroCitizenRoot)this.heroCitizenRoot.visible=false;return true}
 buildLivingCitizens(){this.livingCitizenRoot=new THREE.Group();this.scene.add(this.livingCitizenRoot)}
 texture(path){if(!path)return null;if(this.livingTextures.has(path))return this.livingTextures.get(path);const t=new THREE.TextureLoader().load(path);t.colorSpace=THREE.SRGBColorSpace;t.magFilter=THREE.LinearFilter;t.minFilter=THREE.LinearFilter;this.livingTextures.set(path,t);return t}
 ensureCitizen(s){let e=this.livingSprites.get(s.id);if(e)return e;const def=Settlement.CitizenSpriteManifest?.[s.job]||Settlement.CitizenSpriteManifest?.default,path=def?.idle?.[0],mat=new THREE.SpriteMaterial({map:this.texture(path),color:0xffffff,transparent:true,depthWrite:false}),sprite=new THREE.Sprite(mat),group=new THREE.Group();sprite.center.set(.5,.08);sprite.scale.set(40,57,1);sprite.position.y=28;group.add(sprite);const sh=new THREE.Mesh(new THREE.CircleGeometry(10,16).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color:0x090b10,transparent:true,opacity:.2,depthWrite:false}));sh.position.y=.45;group.add(sh);const toolMat=new THREE.MeshBasicMaterial({color:0x8a795f});const tool=new THREE.Mesh(new THREE.BoxGeometry(2.5,19,2.5),toolMat);tool.position.set(12,27,2);tool.visible=false;group.add(tool);this.livingCitizenRoot.add(group);e={group,sprite,mat,tool};this.livingSprites.set(s.id,e);return e}
 syncLivingCitizens(now){const all=this.live.citizens(),cam=this.game.camera,ordered=all.map(s=>({s,d:(s.x-cam.x)**2+(s.y-cam.y)**2})).sort((a,b)=>a.d-b.d).slice(0,MAX_SPRITES),seen=new Set();for(const{ s,d }of ordered){const e=this.ensureCitizen(s);seen.add(s.id);e.group.visible=!s.sleeping&&d<1500*1500;if(!e.group.visible)continue;e.group.position.set(s.x,0,s.y);const work=s.workVisualEligible,phase=now*.006+s.id;e.sprite.position.y=28+(work?Math.sin(phase)*1.6:(s.moving?Math.sin(phase*.7)*.8:0));e.sprite.rotation.z=work?Math.sin(phase)*.035:0;e.tool.visible=!!work&&["lumber","quarry","blacksmith","mason","farm"].includes(s.workVisual);if(e.tool.visible){e.tool.rotation.z=-.55+Math.sin(phase)*.42;e.tool.position.y=27+Math.cos(phase)*2}}
 for(const[id,e]of this.livingSprites)e.group.visible=seen.has(id)&&e.group.visible}
 buildLivingDoors(){this.doorRoot=new THREE.Group();this.scene.add(this.doorRoot);this.doorMat=this.mat("living-door",0x5b3f2d,{roughness:.94});this.doorGlow=this.mat("living-door-glow",0x8b5b32,{emissive:0xffb35b,ei:.35})}
 ensureDoor(b){let e=this.doors.get(b.id);if(e)return e;const g=new THREE.Group(),slab=new THREE.Mesh(this.box(Math.min(28,b.w*T*.22),36,4),this.doorMat),glow=new THREE.Mesh(this.box(Math.min(24,b.w*T*.19),31,2),this.doorGlow);slab.position.set(0,18,0);glow.position.set(0,18,-2);g.add(glow,slab);g.position.set((b.x+b.w/2)*T,0,(b.y+b.h)*T-2);this.doorRoot.add(g);e={g,slab,open:0};this.doors.set(b.id,e);return e}
 syncDoors(dt,phase){const eligible=this.game.buildings.list.filter(b=>this.live.buildingState(b).doorVisualEligible).slice(0,MAX_DOORS),seen=new Set();for(const b of eligible){const e=this.ensureDoor(b);seen.add(b.id);e.g.position.set((b.x+b.w/2)*T,0,(b.y+b.h)*T-2);const demand=this.live.doorDemand(b.id),target=demand?1:0;e.open+=(target-e.open)*Math.min(1,dt*5);e.slab.rotation.y=-e.open*1.12;e.g.visible=Math.hypot(e.g.position.x-this.game.camera.x,e.g.position.z-this.game.camera.y)<1100}for(const[id,e]of this.doors)e.g.visible=seen.has(id)&&e.g.visible;this.doorGlow.emissiveIntensity=(phase==="NIGHT"||phase==="DUSK")?1.1:.16}
 buildLivingEffects(){this.fxRoot=new THREE.Group();this.scene.add(this.fxRoot);for(let i=0;i<48;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(1.6,5,4),new THREE.MeshBasicMaterial({color:i%2?0xcaa56c:0x8f8a7c,transparent:true,opacity:0,depthWrite:false}));m.visible=false;this.fxRoot.add(m);this.fx.push({o:m,life:0,kind:""})}for(let i=0;i<24;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(4+i%2*2,6,5),new THREE.MeshBasicMaterial({color:0x77756f,transparent:true,opacity:0,depthWrite:false}));m.visible=false;this.fxRoot.add(m);this.smoke.push({o:m,seed:i})}}
 emitWorkFx(now){const states=this.live.citizens().filter(s=>s.workVisualEligible);let slot=0;for(const s of states){if(slot>=this.fx.length)break;if(!["quarry","blacksmith","lumber","mason"].includes(s.workVisual))continue;if(((Math.floor(now/180)+s.id)%8)!==0)continue;for(let j=0;j<2&&slot<this.fx.length;j++,slot++){const f=this.fx[slot];f.o.visible=true;f.life=1;f.kind=s.workVisual;f.o.position.set(s.x+(j?5:-4),20+j*5,s.y);f.o.material.color.setHex(s.workVisual==="blacksmith"?0xffa148:(s.workVisual==="lumber"?0xb08b57:0xb4afa0));f.o.material.opacity=.75}}
 for(let i=slot;i<this.fx.length;i++){const f=this.fx[i];if(!f.o.visible)continue;f.life-=.06;f.o.position.y+=.9;f.o.position.x+=i%2?.25:-.18;f.o.material.opacity=Math.max(0,f.life*.65);if(f.life<=0)f.o.visible=false}}
 syncSmoke(now,phase){const active=this.game.buildings.list.filter(b=>{const s=this.live.buildingState(b);return s.chimneyVisualEligible&&(b.type==="cottage"?phase==="NIGHT"||phase==="DUSK":s.workEffectEligible)}).slice(0,this.smoke.length);for(let i=0;i<this.smoke.length;i++){const f=this.smoke[i],b=active[i];if(!b){f.o.visible=false;continue}f.o.visible=true;const age=(now*.00018+f.seed*.23)%1,x=(b.x+b.w*.72)*T,z=(b.y+b.h*.34)*T;f.o.position.set(x+Math.sin(now*.001+f.seed)*4,70+age*55,z);f.o.scale.setScalar(.5+age*1.4);f.o.material.opacity=(1-age)*.14}}
 installOverlay(){const root=document.querySelector("#game-shell")||document.body,layer=document.createElement("div");layer.id="living-world-overlay";layer.style.cssText="position:absolute;inset:0;pointer-events:none;overflow:hidden;z-index:7";root.appendChild(layer);this.overlay=layer}
 maybeBubble(now){if(now-this.lastBubbleAt<8500||this.game.placement?.type)return;const candidates=this.live.citizens().filter(s=>!s.sleeping&&this.live.contextLine(s));if(!candidates.length)return;const s=candidates[Math.floor(now/8500)%candidates.length],p=this.worldToScreen(s.x,s.y);if(p.x<20||p.y<80||p.x>innerWidth-20||p.y>innerHeight-100)return;this.lastBubbleAt=now;const d=document.createElement("div");d.textContent=this.live.contextLine(s);d.style.cssText=`position:absolute;left:${p.x}px;top:${p.y-58}px;transform:translate(-50%,-100%);max-width:170px;padding:6px 9px;border:1px solid rgba(211,184,132,.55);border-radius:10px;background:rgba(20,18,18,.82);color:#efe3cb;font:12px Georgia,serif;text-align:center;box-shadow:0 4px 14px rgba(0,0,0,.28)`;this.overlay.appendChild(d);this.bubbles.push({el:d,born:now,s});while(this.bubbles.length>MAX_BUBBLES)this.bubbles.shift().el.remove()}
 syncBubbles(now){for(let i=this.bubbles.length-1;i>=0;i--){const b=this.bubbles[i];if(now-b.born>3300){b.el.remove();this.bubbles.splice(i,1);continue}const p=this.worldToScreen(b.s.x,b.s.y);b.el.style.left=p.x+"px";b.el.style.top=(p.y-58)+"px"}}
 installCitizenTap(){const down=e=>{if(this.game.placement?.type)return;this._tapStart={x:e.clientX,y:e.clientY,t:performance.now()}};const up=e=>{const s=this._tapStart;this._tapStart=null;if(!s||this.game.placement?.type||Math.hypot(e.clientX-s.x,e.clientY-s.y)>9||performance.now()-s.t>450)return;const w=this.screenToWorld(e.clientX,e.clientY),c=this.game.citizens.list.map(c=>({c,d:(c.x-w.x)**2+(c.y-w.y)**2})).sort((a,b)=>a.d-b.d)[0];if(c&&c.d<28*28)this.game.ui?.citizenPanel?.(c.c)};this._pointerDown=down;this._pointerUp=up;this.canvas.addEventListener("pointerdown",down,{passive:true});this.canvas.addEventListener("pointerup",up,{passive:true})}
 syncAudio(now){const a=this.game.audio;if(!a?.ctx||a.ctx.state!=="running")return;const zones=this.game.buildings.list.filter(b=>b.complete&&["blacksmith","lumber","quarry","mill","bakery","market","training","barracks"].includes(b.type));let best=null,bd=Infinity;for(const b of zones){const d=Math.hypot((b.x+b.w/2)*T-this.game.camera.x,(b.y+b.h/2)*T-this.game.camera.y);if(d<bd){bd=d;best=b}}if(!best||bd>720)return;const key=best.type,interval=key==="market"?5200:2200;if(now<(this._audioNext[key]||0))return;this._audioNext[key]=now+interval;const sound=(key==="quarry")?"stone":(key==="blacksmith"||key==="lumber")?"produce":"tap";a.play(sound)}
 syncTime(){super.syncTime();const h=this.live.hour(),phase=this.live.phase(),dawn=clamp(1-Math.abs(h-7)/2,0,1),dusk=clamp(1-Math.abs(h-19)/2,0,1),night=phase==="NIGHT"?1:(phase==="DUSK"?dusk:0);this.hemi.intensity=1.85-night*.38+dawn*.12;this.fill.intensity=.95-night*.14;this.sun.intensity=phase==="DAY"?1.75:(phase==="DAWN"||phase==="DUSK"?1.18:.72);this.sun.color.setHex(phase==="NIGHT"?0x92a9d2:(phase==="DAWN"||phase==="DUSK"?0xe6b27f:0xe8dfca));this.scene.background.setHex(phase==="NIGHT"?0x2c3542:(phase==="DUSK"?0x41433f:0x465044));this.scene.fog.color.copy(this.scene.background);for(const m of this.districtWindowMats||[])m.emissiveIntensity=.18+night*1.5}
 render(){if(!this.ok)return;const now=performance.now(),dt=Math.min(.05,Math.max(.001,(now-(this._lastLivingNow||now))/1000));this._lastLivingNow=now;const phase=this.live.phase();this.syncLivingCitizens(now);this.syncDoors(dt,phase);this.emitWorkFx(now);this.syncSmoke(now,phase);this.environment?.update(now,phase);this.maybeBubble(now);this.syncBubbles(now);this.syncAudio(now);super.render()}
 dispose(){this.canvas.removeEventListener("pointerdown",this._pointerDown);this.canvas.removeEventListener("pointerup",this._pointerUp);this.overlay?.remove();this.environment?.dispose();for(const t of this.livingTextures.values())t.dispose?.();this.livingCitizenRoot?.traverse(o=>{o.geometry?.dispose?.();o.material?.dispose?.()})}
}
