/* Finished residential district + continuous gothic terrain foundation.
 * Presentation only; unsupported buildings retain the existing fallback.
 */
import * as THREE from "../../vendor/three/three.module.min.js";
import {HeroSliceWorld3D} from "./HeroSliceWorld3D.js";
import {variantFor} from "./ResidentialVisualDefs.js";
import {GothicTerrainFoundation} from "./GothicTerrainFoundation.js";
const T=64,MAX_DISTRICT_HOMES=12,MAX_REAL_LANTERNS=4;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class ResidentialDistrictWorld3D extends HeroSliceWorld3D{
 constructor(game,canvas){super(game,canvas);this.districtLights=[];this.districtGroups=[];this.districtWindowMats=new Set();this._districtSig=""}
 init(){const ok=super.init();if(!ok)return false;this.districtDecorRoot=new THREE.Group();this.scene.add(this.districtDecorRoot);this.buildDistrictTextures();this.terrainFoundation=new GothicTerrainFoundation(this).init();if(this.heroGround)this.heroGround.visible=false;if(this.heroRoad)this.heroRoad.visible=false;return true}
 districtCottages(){const homes=this.game.buildings.list.filter(b=>b?.type==="cottage"&&b.complete);if(!homes.length)return[];const hero=homes[0],hx=(hero.x+hero.w/2)*T,hz=(hero.y+hero.h/2)*T;return homes.map(b=>({b,d:Math.hypot((b.x+b.w/2)*T-hx,(b.y+b.h/2)*T-hz)})).filter(x=>x.d<=T*11||x.b.id===hero.id).sort((a,b)=>a.d-b.d).slice(0,MAX_DISTRICT_HOMES).map(x=>x.b)}
 isFinishedResidential(b){return!!(b&&this.districtCottages().some(x=>x.id===b.id))}
 buildStructure(b){if(!this.isFinishedResidential(b))return super.buildStructure(b);const v=variantFor(b);if(!v)return super.buildStructure(b);const g=new THREE.Group(),w=b.w*T,d=b.h*T,tier=this.tierOf(b.level||1),stone=this.heroMat("district-stone-"+v.stone,v.stone,{roughness:.96}),plaster=this.heroMat("district-plaster-"+v.plaster,v.plaster,{roughness:.98}),timber=this.heroMat("district-timber-"+v.timber,v.timber,{roughness:.9}),roof=this.heroMat("district-roof-"+v.roof,v.roof,{roughness:.92}),edge=this.heroMat("district-edge",0x343a45,{roughness:.95}),iron=this.heroMat("district-iron",0x62656b,{metalness:.38,roughness:.64}),door=this.heroMat("district-door-"+v.door,v.door,{roughness:.92}),window=this.heroMat("district-window",0x8a6039,{emissive:0xffbd6a,ei:.3});this.districtWindowMats.add(window);const boost=1+Math.min(3,Math.max(0,(b.level||1)-1))*.035;this.part(this.box(w*.92,11,d*.84),stone,0,5.5,0,g);this.part(this.box(w*.72,52*boost,d*.64),plaster,0,36*boost,0,g);for(const x of[-w*.34,w*.34])this.part(this.box(7,56*boost,7),timber,x,38*boost,d*.31,g);this.part(this.box(w*.7,7,7),timber,0,58*boost,d*.31,g);this.part(this.box(w*.7,6,7),timber,0,24,d*.315,g);if(v.crossBrace)for(const s of[-1,1]){const beam=this.part(this.box(6,48,7),timber,s*w*.18,38,d*.318,g);beam.rotation.z=s*.58}const roofY=68*boost;this.part(this.prism(w*(.91+(v.seed%4)*.01),45+(v.seed%5),d*.84),roof,0,roofY,0,g);this.part(this.box(w*.98,5,8),edge,0,roofY-6,d*.405,g);this.part(this.box(w*.98,5,8),edge,0,roofY-6,-d*.405,g);this.part(this.box(w*.72,4,5),iron,0,roofY+25,0,g);const cx=(v.chimneyRight?1:-1)*w*.27;this.part(this.box(13,56,13),stone,cx,94,-d*.18,g);this.part(this.box(18,5,18),edge,cx,123,-d*.18,g);this.part(this.box(34,42,6),edge,0,29,d*.319,g);this.part(this.box(28,39,5),door,0,27,d*.335,g);if(v.porch||tier>=2){this.part(this.box(42,4,24),stone,0,2,d*.49,g);for(const x of[-w*.27,w*.27])this.part(this.box(5,24,5),timber,x,14,d*.43,g)}const xs=v.doubleWindow?[-w*.22,w*.22]:[(v.seed&16?-1:1)*w*.22];for(const x of xs){this.part(this.box(19,23,5),edge,x,41,d*.327,g);this.part(this.box(15,19,4),window,x,41,d*.337,g);this.part(this.box(3,21,5),timber,x,41,d*.344,g);this.part(this.box(17,3,5),timber,x,41,d*.345,g)}g.position.set((b.x+b.w/2)*T,0,(b.y+b.h/2)*T);return g}
 buildDistrictTextures(){this.districtPoolTex=this.textureFromCanvas(128,(x,s)=>{const g=x.createRadialGradient(s/2,s/2,2,s/2,s/2,s*.48);g.addColorStop(0,"rgba(255,185,96,.34)");g.addColorStop(.28,"rgba(240,154,70,.17)");g.addColorStop(.7,"rgba(221,119,48,.04)");g.addColorStop(1,"rgba(221,119,48,0)");x.fillStyle=g;x.fillRect(0,0,s,s)})}
 clearGroup(root){while(root.children.length)root.remove(root.children[root.children.length-1])}
 addCottageProps(group,v){const wood=this.heroMat("district-prop-wood",0x674b36,{roughness:.96}),dark=this.heroMat("district-prop-dark",0x40312a,{roughness:.97}),weed=this.heroMat("district-weed",0x53664a,{roughness:1});if(v.prop==="firewood")for(let i=0;i<4;i++)this.part(this.box(25,5,5),wood,-62,5+i*5,54-i*2,group);else if(v.prop==="fence"){for(const x of[-28,0,28])this.part(this.box(5,25,5),dark,x,12,-72,group);this.part(this.box(65,5,5),wood,0,17,-72,group)}else this.part(this.box(22,18,22),wood,58,9,48,group);for(let i=0;i<2;i++){const blade=this.part(this.box(3,13,3),weed,-45+i*82,6,68-i*12,group);blade.rotation.z=i?-.35:.28}}
 addLantern(group,b,index){const iron=this.heroMat("district-lamp-iron",0x626061,{metalness:.45,roughness:.64}),glow=this.heroMat("district-lamp-glow",0x8b5a30,{emissive:0xffb35b,ei:.3}),lx=b.w*T*.34,lz=b.h*T*.42;this.part(this.box(4,42,4),iron,lx,21,lz,group);this.part(this.box(18,4,4),iron,lx+7,42,lz,group);this.part(new THREE.SphereGeometry(4.5,8,6),glow,lx+14,36,lz,group);const pool=new THREE.Mesh(new THREE.PlaneGeometry(T*2.35,T*1.75).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({map:this.districtPoolTex,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));pool.position.set(lx+14,.72,lz);pool.rotation.y=((index%3)-1)*.2;group.add(pool);let light=null;if(index<MAX_REAL_LANTERNS){light=new THREE.PointLight(0xffad59,0,185,2.3);light.position.set(lx+14,37,lz);group.add(light);this.districtLights.push(light)}this.districtGroups.push({pool,glow,light})}
 syncDistrictDecor(){const homes=this.districtCottages(),sig=homes.map(b=>b.id+":"+b.x+","+b.y+":"+(b.level||1)).join("|");this.terrainFoundation?.update();if(sig===this._districtSig)return;this._districtSig=sig;this.clearGroup(this.districtDecorRoot);this.districtLights.length=0;this.districtGroups.length=0;homes.forEach((b,index)=>{const v=variantFor(b),g=new THREE.Group();g.position.set((b.x+b.w/2)*T,0,(b.y+b.h/2)*T);this.addCottageProps(g,v);this.addLantern(g,b,index);this.districtDecorRoot.add(g)})}
 syncHeroCitizens(center,night){const homes=this.districtCottages();if(!homes.length)return super.syncHeroCitizens(center,night);const cx=homes.reduce((s,b)=>s+(b.x+b.w/2)*T,0)/homes.length,cz=homes.reduce((s,b)=>s+(b.y+b.h/2)*T,0)/homes.length,list=this.game.citizens.list.filter(c=>c?.state!=="SLEEPING").map(c=>({c,d:(c.x-cx)**2+(c.y-cz)**2})).sort((a,b)=>a.d-b.d).slice(0,18),live=new Set();for(const{c}of list){live.add(c.id);const e=this.ensureHeroCitizen(c);e.group.visible=true;e.group.position.set(c.x,0,c.y);let nearest=9999;for(const h of homes)nearest=Math.min(nearest,Math.hypot(c.x-(h.x+h.w*.82)*T,c.y-(h.y+h.h*.9)*T));const warm=clamp(1-nearest/190,0,1)*night;e.mat.color.setRGB(1,clamp(1-.04*warm,.94,1),clamp(1-.1*warm,.88,1))}for(const[id,e]of this.heroCitizenSprites)e.group.visible=live.has(id)}
 syncTime(){super.syncTime();const hour=(this.game.clock.t/Settlement.Config.DAY_SECONDS)*24,night=clamp(this.game.renderer?.nightFactor?this.game.renderer.nightFactor(hour):(hour>=20||hour<5?1:0),0,1);for(const m of this.districtWindowMats)m.emissiveIntensity=.16+night*1.42;for(const d of this.districtGroups){d.glow.emissiveIntensity=.2+night*1.6;d.pool.material.opacity=night*.18;if(d.light)d.light.intensity=night*1.5}}
 render(){if(!this.ok)return;this.syncDistrictDecor();super.render()}
}
