/* Surgical stability layer for the optional 3D renderer.
 * Keeps World3D presentation-only and overrides only confirmed hot/sync paths.
 */
import * as THREE from "../../vendor/three/three.module.min.js";
import { World3D } from "./World3D.js";

const T=64,MAX_VISIBLE_CITIZENS=4096,MAX_VISIBLE_ENEMIES=512;

export class StableWorld3D extends World3D {
 constructor(game,canvas){super(game,canvas);this.citizenCapacity=0;this.enemyCapacity=0;this._qualityRich=null;this._territoryKey=null;this._placementKey=null}
 init(){let ok=super.init();if(!ok)return false;this.buildEnemies();this.buildFeedback();this.applyQuality();this.game.bus.on("tower:fired",ev=>{if(ev?.target)this._hitEnemy={id:ev.target.id,until:performance.now()+110}});return true}

 /* Explicit territory revision invalidates World3D even when rect count is unchanged. */
 refreshGround(){let ex=this.game.expansion,season=this.game.clock?.seasonIndex||0,key=season+":"+(ex.revision||0);if(key===this._territoryKey)return;this._territoryKey=key;this.groundKey=null;super.refreshGround()}

 /* Instanced placement preview: no per-frame Mesh construction/destruction. */
 buildPlacement(){this.placeGroup=new THREE.Group();this.scene.add(this.placeGroup);this.tileGeo=new THREE.PlaneGeometry(T*.94,T*.94).rotateX(-Math.PI/2);this.matOK=new THREE.MeshBasicMaterial({color:0x8fd06b,transparent:true,opacity:.34});this.matBad=new THREE.MeshBasicMaterial({color:0xc4463a,transparent:true,opacity:.34});this.matClaim=new THREE.MeshBasicMaterial({color:0xd9c46b,transparent:true,opacity:.16});this.placeClaim=new THREE.InstancedMesh(this.tileGeo,this.matClaim,256);this.placeOK=new THREE.InstancedMesh(this.tileGeo,this.matOK,256);this.placeBad=new THREE.InstancedMesh(this.tileGeo,this.matBad,256);for(const m of[this.placeClaim,this.placeOK,this.placeBad]){m.count=0;m.frustumCulled=false;m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.placeGroup.add(m)}this._placeM4=new THREE.Matrix4()}
 syncPlacement(){let p=this.game.placement;if(!p||!p.type||!p.hover){this.placeClaim.count=this.placeOK.count=this.placeBad.count=0;this._placementKey=null;return}let v=p.validate(p.type,p.hover.x,p.hover.y),cells=v.cells||[],rev=this.game.expansion.revision||0,sig=p.type+"|"+p.hover.x+","+p.hover.y+"|"+(p.moving?.id||0)+"|"+(p.moving?.level||1)+"|"+rev+"|"+v.ok+"|"+cells.map(c=>c.ok?1:0).join("");if(sig===this._placementKey)return;this._placementKey=sig;let nc=0,no=0,nb=0;if(p.type==="archery"){let lvl=p.moving?(p.moving.level||1):1,r=this.game.expansion.claimRectFor("archery",p.hover.x,p.hover.y,lvl);if(r)for(let y=r.y;y<r.y+r.h;y++)for(let x=r.x;x<r.x+r.w;x++){if(this.game.expansion.isClaimed(x,y)||nc>=256)continue;this._placeM4.makeTranslation(x*T+T/2,1.6,y*T+T/2);this.placeClaim.setMatrixAt(nc++,this._placeM4)}}for(const c of cells){let mesh=c.ok?this.placeOK:this.placeBad,idx=c.ok?no:nb;if(idx>=256)continue;this._placeM4.makeTranslation(c.x*T+T/2,2.2,c.y*T+T/2);mesh.setMatrixAt(idx,this._placeM4);if(c.ok)no++;else nb++}this.placeClaim.count=nc;this.placeOK.count=no;this.placeBad.count=nb;for(const m of[this.placeClaim,this.placeOK,this.placeBad])m.instanceMatrix.needsUpdate=true}

 /* Citizens grow in 256-instance chunks with a hard presentation ceiling. */
 buildCitizens(){this.citizenGeo=new THREE.CapsuleGeometry(6,12,3,6);this.citizenMat=new THREE.MeshLambertMaterial({vertexColors:true});this._m4=new THREE.Matrix4();this._c=new THREE.Color();this.ensureCitizenCapacity(256)}
 ensureCitizenCapacity(needed){let cap=Math.min(MAX_VISIBLE_CITIZENS,Math.max(256,Math.ceil(needed/256)*256));if(this.citizenMesh&&cap<=this.citizenCapacity)return;if(this.citizenMesh)this.scene.remove(this.citizenMesh);this.citizenCapacity=cap;this.citizenMesh=new THREE.InstancedMesh(this.citizenGeo,this.citizenMat,cap);this.citizenMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.citizenMesh.count=0;this.citizenMesh.frustumCulled=false;this.citizenMesh.castShadow=this.rich;this.scene.add(this.citizenMesh)}
 syncCitizens(){let list=this.game.citizens.list,visible=Math.min(MAX_VISIBLE_CITIZENS,list.reduce((n,c)=>n+(c.state!=="SLEEPING"),0));this.ensureCitizenCapacity(visible);let mesh=this.citizenMesh,jobColor={Archer:0x46543a,Lumberjack:0x4a3524,Stonecutter:0x55565a,Stonemason:0x5e564a,Miller:0x4f4a58,Baker:0x6a4c33,Farmer:0x47512f},n=0;for(const c of list){if(c.state==="SLEEPING")continue;if(n>=this.citizenCapacity)break;this._m4.makeTranslation(c.x,14,c.y);mesh.setMatrixAt(n,this._m4);this._c.setHex(jobColor[c.job]||0x584a3e);mesh.setColorAt(n,this._c);n++}mesh.count=n;mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true}

 /* Lightweight enemy mirror; simulation remains entirely in EnemyDirector. */
 buildEnemies(){this.enemyGeo=new THREE.CapsuleGeometry(8,18,3,6);this.enemyMat=new THREE.MeshLambertMaterial({vertexColors:true});this._enemyM4=new THREE.Matrix4();this._enemyColor=new THREE.Color();this.ensureEnemyCapacity(32)}
 ensureEnemyCapacity(needed){let cap=Math.min(MAX_VISIBLE_ENEMIES,Math.max(32,Math.ceil(needed/32)*32));if(this.enemyMesh&&cap<=this.enemyCapacity)return;if(this.enemyMesh)this.scene.remove(this.enemyMesh);this.enemyCapacity=cap;this.enemyMesh=new THREE.InstancedMesh(this.enemyGeo,this.enemyMat,cap);this.enemyMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.enemyMesh.count=0;this.enemyMesh.frustumCulled=false;this.enemyMesh.castShadow=this.rich;this.scene.add(this.enemyMesh)}
 syncEnemies(){let list=this.game.enemies?.list||[];this.ensureEnemyCapacity(Math.min(MAX_VISIBLE_ENEMIES,list.length));let n=0,now=performance.now();for(const e of list){if(e.hp<=0||n>=this.enemyCapacity)continue;this._enemyM4.makeTranslation(e.x,16,e.y);this.enemyMesh.setMatrixAt(n,this._enemyM4);this._enemyColor.setHex(this._hitEnemy?.id===e.id&&this._hitEnemy.until>now?0xe06a55:0x642b2b);this.enemyMesh.setColorAt(n,this._enemyColor);n++}this.enemyMesh.count=n;this.enemyMesh.instanceMatrix.needsUpdate=true;if(this.enemyMesh.instanceColor)this.enemyMesh.instanceColor.needsUpdate=true}

 /* Reusable projectile geometry + pooled DOM floaters for gameplay feedback. */
 buildFeedback(){this.shotPositions=new Float32Array(24*6);this.shotGeo=new THREE.BufferGeometry();this.shotGeo.setAttribute("position",new THREE.BufferAttribute(this.shotPositions,3));this.shotGeo.setDrawRange(0,0);this.shotLines=new THREE.LineSegments(this.shotGeo,new THREE.LineBasicMaterial({color:0xd8c690}));this.shotLines.frustumCulled=false;this.scene.add(this.shotLines);let shell=document.querySelector("#game-shell");this.feedbackRoot=document.createElement("div");Object.assign(this.feedbackRoot.style,{position:"absolute",inset:"0",pointerEvents:"none",overflow:"hidden",zIndex:"3"});this.feedbackEls=[];for(let i=0;i<24;i++){let el=document.createElement("span");Object.assign(el.style,{position:"absolute",display:"none",transform:"translate(-50%,-50%)",fontWeight:"800",fontSize:"14px",textShadow:"0 1px 3px #000",color:"#f3dfad",whiteSpace:"nowrap"});this.feedbackRoot.appendChild(el);this.feedbackEls.push(el)}shell?.appendChild(this.feedbackRoot)}
 syncShots(){let shots=this.game.effects?.shots||[],n=Math.min(24,shots.length);for(let i=0;i<n;i++){let s=shots[i],o=i*6;this.shotPositions[o]=s.x1;this.shotPositions[o+1]=28;this.shotPositions[o+2]=s.y1;this.shotPositions[o+3]=s.x2;this.shotPositions[o+4]=20;this.shotPositions[o+5]=s.y2}this.shotGeo.setDrawRange(0,n*2);this.shotGeo.attributes.position.needsUpdate=true}
 syncFloaters(){let fs=this.game.effects?.floaters||[],n=Math.min(this.feedbackEls.length,fs.length);for(let i=0;i<this.feedbackEls.length;i++){let el=this.feedbackEls[i];if(i>=n){el.style.display="none";continue}let f=fs[i],p=this.worldToScreen(f.x,f.y),life=Math.max(0,Math.min(1,f.t/1.4));el.textContent=f.text;el.style.display="block";el.style.left=p.x+"px";el.style.top=(p.y-18*(1-life))+"px";el.style.opacity=String(Math.min(1,life*1.5))}}

 /* Apply runtime quality changes to all mutable 3D presentation state. */
 applyQuality(){let tier=this.game.quality?.tier||"MEDIUM",rich=tier==="HIGH"||tier==="ULTRA",changed=this._qualityRich!==null&&this._qualityRich!==rich;this._qualityRich=rich;this.rich=rich;if(!this.renderer)return;this.renderer.shadowMap.enabled=rich;if(this.sun){this.sun.castShadow=rich;if(rich){this.sun.shadow.mapSize.set(2048,2048);let s=1400,c=this.sun.shadow.camera;c.left=-s;c.right=s;c.top=s;c.bottom=-s;c.near=1;c.far=4000;c.updateProjectionMatrix();this.sun.shadow.bias=-.0012}}if(this.ground)this.ground.receiveShadow=rich;if(this.citizenMesh)this.citizenMesh.castShadow=rich;if(this.enemyMesh)this.enemyMesh.castShadow=rich;if(changed){for(const mesh of this.meshes.values())this.scene.remove(mesh);this.meshes.clear();this.sig.clear();for(const m of this.matCache.values())m.dispose?.();this.matCache.clear()}this.resize()}

 render(){if(!this.ok)return;this.syncEnemies();this.syncShots();super.render();this.syncFloaters()}
}
