Settlement.PlacementSystem=class{
 constructor(game){this.game=game;this.type=null;this.hover=null;this.committing=false;this.lastValidation=null;this.moving=null}
 start(type){if(!Settlement.BuildingDefs[type])return false;this.type=type;this.moving=null;this.hover=null;this.committing=false;this.lastValidation=null;this.game.ui.closePanels();this.game.bus.emit("placement:start",{type,definition:Settlement.BuildingDefs[type]});return true}
 startMove(b){if(!b||!Settlement.BuildingDefs[b.type])return false;this.type=b.type;this.moving=b;this.hover=null;this.committing=false;this.lastValidation=null;this.game.ui.closePanels();this.game.bus.emit("placement:start",{type:b.type,definition:Settlement.BuildingDefs[b.type],moving:b});return true}
 setPreviewTile(x,y){if(!this.type)return;let next={x,y};if(this.hover&&this.hover.x===x&&this.hover.y===y)return;this.hover=next;this.lastValidation=this.validate(this.type,x,y);this.game.bus.emit("placement:moved",{type:this.type,hover:this.hover,validation:this.lastValidation})}
 cancel(reason="cancelled"){if(!this.type)return;let previous={type:this.type,hover:this.hover};this.type=null;this.moving=null;this.hover=null;this.lastValidation=null;this.committing=false;this.game.bus.emit("placement:cancelled",{...previous,reason});this.game.bus.emit("placement:end")}
 footprint(type,x,y){let d=Settlement.BuildingDefs[type],cells=[];for(let yy=y;yy<y+d.footprint[1];yy++)for(let xx=x;xx<x+d.footprint[0];xx++){let owner=this.game.grid.occupied.get(xx+","+yy),occupied=owner!==undefined&&owner!==this.moving?.id,territory=this.game.expansion.canBuild(type,xx,yy,1,1);cells.push({x:xx,y:yy,occupied,territory,ok:!occupied&&territory})}return cells}
 entrance(type,x,y){let d=Settlement.BuildingDefs[type];if(d.road||d.wall||d.gate||type==="farm"||type==="archery"||d.remoteClaim)return null;let candidates=[{x:x+Math.floor(d.footprint[0]/2),y:y+d.footprint[1]},{x:x+d.footprint[0],y:y+Math.floor(d.footprint[1]/2)},{x:x-1,y:y+Math.floor(d.footprint[1]/2)},{x:x+Math.floor(d.footprint[0]/2),y:y-1}];return candidates.find(p=>this.game.grid.inBounds(p.x,p.y))||candidates[0]}
 roadAccess(type,x,y){let e=this.entrance(type,x,y);if(!e)return null;return [[1,0],[-1,0],[0,1],[0,-1],[0,0]].some(([dx,dy])=>this.game.roads?.isRoad(e.x+dx,e.y+dy))}
 affordability(cost){let missing=[];for(const[k,v]of Object.entries(cost||{})){let have=Math.floor(this.game.resources.v[k]||0);if(have<v)missing.push({resource:k,have,need:v,short:v-have})}return{ok:missing.length===0,missing}}
 validate(type,x,y){let d=Settlement.BuildingDefs[type];if(!d)return{ok:false,reason:"UNKNOWN STRUCTURE",cells:[]};if(d.unique&&!this.moving&&this.game.buildings.list.some(b=>b.type===type))return{ok:false,reason:"THE SETTLEMENT HAS ONE "+String(d.name||type).toUpperCase(),cells:this.footprint(type,x,y)};let cells=this.footprint(type,x,y);let outside=cells.find(c=>!c.territory);if(outside)return{ok:false,reason:(d.claimsTerritory||d.wall||d.gate||d.road)?"TOO FAR FROM YOUR BORDER":"OUTSIDE YOUR TERRITORY — BUILD AN ARCHERY TOWER",cells,entrance:this.entrance(type,x,y),roadAccess:this.roadAccess(type,x,y)};let blocked=cells.find(c=>c.occupied);if(blocked){let id=this.game.grid.occupied.get(blocked.x+","+blocked.y),b=id&&this.game.buildings.byId(id),name=b?Settlement.BuildingDefs[b.type]?.name:"structure";return{ok:false,reason:"BLOCKED BY "+String(name||"structure").toUpperCase(),cells,entrance:this.entrance(type,x,y),roadAccess:this.roadAccess(type,x,y)}}let money=this.moving?{ok:true,missing:[]}:this.affordability(d.cost);if(!money.ok){let m=money.missing[0],name=Settlement.ResourceDefs[m.resource]?.name||m.resource;return{ok:false,reason:"NEED "+m.short+" MORE "+name.toUpperCase(),cells,missing:money.missing,entrance:this.entrance(type,x,y),roadAccess:this.roadAccess(type,x,y)}}return{ok:true,reason:d.remoteClaim?"VALID DISTANT STRONGHOLD":"VALID LOCATION",cells,entrance:this.entrance(type,x,y),roadAccess:this.roadAccess(type,x,y)}}
 confirm(){if(!this.type||!this.hover||this.committing)return false;this.committing=true;let type=this.type,{x,y}=this.hover,v=this.validate(type,x,y);this.lastValidation=v;if(!v.ok){this.committing=false;this.game.bus.emit("placement:validity",{type,hover:this.hover,validation:v});this.game.bus.emit("toast","⛔ "+v.reason);return false}if(this.moving){let b=this.moving;this.game.grid.free(b.id);b.x=x;b.y=y;this.game.grid.occupy(b.id,b.x,b.y,b.w,b.h);this.type=null;this.moving=null;this.hover=null;this.lastValidation=null;this.committing=false;this.game.housing?.reconcile();this.game.bus.emit("building:moved",b);this.game.bus.emit("toast",Settlement.BuildingDefs[b.type].name+" relocated.");this.game.bus.emit("placement:end");return b}
  let d=Settlement.BuildingDefs[type];if(!this.game.resources.spend(d.cost)){this.committing=false;this.game.bus.emit("toast","⛔ Resources changed — check the cost again.");return false}let b=this.game.buildings.create(type,x,y);this.game.bus.emit("placement:confirmed",{building:b,type,cost:d.cost,hover:{x,y}});this.game.bus.emit("construction:started",b);this.game.bus.emit("toast",d.name+" construction started.");this.type=null;this.hover=null;this.lastValidation=null;this.committing=false;this.game.bus.emit("placement:end");return b}
};
