Settlement.PlacementSystem=class{
 constructor(game){this.game=game;this.type=null;this.hover=null;this.committing=false;this.lastValidation=null;this.moving=null;this.paintTiles=[];this.painting=false}
 isPaintType(type=this.type){return type==="road"||type==="wall"}
 start(type){if(!Settlement.BuildingDefs[type])return false;this.type=type;this.moving=null;this.hover=null;this.committing=false;this.lastValidation=null;this.paintTiles=[];this.painting=false;this.game.ui.closePanels();this.game.bus.emit("placement:start",{type,definition:Settlement.BuildingDefs[type]});return true}
 startMove(b){if(!b||!Settlement.BuildingDefs[b.type])return false;let d=Settlement.BuildingDefs[b.type];if((d.claimsTerritory||d.remoteClaim)&&b.type!=="archery"){this.game.bus.emit("toast","🏰 This territory anchor cannot be relocated. Demolish and rebuild it to move the frontier.");return false}this.type=b.type;this.moving=b;this.hover=null;this.committing=false;this.lastValidation=null;this.paintTiles=[];this.painting=false;this.game.ui.closePanels();this.game.bus.emit("placement:start",{type:b.type,definition:d,moving:b});return true}
 setPreviewTile(x,y){if(!this.type)return;let next={x,y};if(this.hover&&this.hover.x===x&&this.hover.y===y)return;this.hover=next;if(this.isPaintType()&&!this.moving&&!this.painting)this.paintTiles=[next];this.lastValidation=this.validateCurrent();this.game.bus.emit("placement:moved",{type:this.type,hover:this.hover,validation:this.lastValidation})}
 beginPaint(x,y){if(!this.isPaintType()||this.moving)return this.setPreviewTile(x,y);this.painting=true;this.paintTiles=[];this.appendPaint(x,y);return true}
 lineTiles(a,b){let out=[],x0=a.x,y0=a.y,x1=b.x,y1=b.y,dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;for(;;){out.push({x:x0,y:y0});if(x0===x1&&y0===y1)break;let e2=2*err;if(e2>=dy){err+=dy;x0+=sx}if(e2<=dx){err+=dx;y0+=sy}}return out}
 appendPaint(x,y){if(!this.isPaintType()||this.moving)return false;let next={x,y},last=this.paintTiles[this.paintTiles.length-1];if(last&&last.x===x&&last.y===y)return false;let add=last?this.lineTiles(last,next).slice(1):[next];for(const t of add){let i=this.paintTiles.findIndex(q=>q.x===t.x&&q.y===t.y);if(i>=0){this.paintTiles=this.paintTiles.slice(0,i+1);continue}this.paintTiles.push(t)}this.hover=next;this.lastValidation=this.validateCurrent();this.game.bus.emit("placement:moved",{type:this.type,hover:this.hover,validation:this.lastValidation,paint:true});return true}
 endPaint(){if(!this.painting)return;this.painting=false;this.lastValidation=this.validateCurrent();this.game.bus.emit("placement:moved",{type:this.type,hover:this.hover,validation:this.lastValidation,paint:true})}
 cancel(reason="cancelled"){if(!this.type)return;let previous={type:this.type,hover:this.hover};this.type=null;this.moving=null;this.hover=null;this.lastValidation=null;this.committing=false;this.paintTiles=[];this.painting=false;this.game.bus.emit("placement:cancelled",{...previous,reason});this.game.bus.emit("placement:end")}
 footprint(type,x,y){let d=Settlement.BuildingDefs[type],cells=[];for(let yy=y;yy<y+d.footprint[1];yy++)for(let xx=x;xx<x+d.footprint[0];xx++){let owner=this.game.grid.occupied.get(xx+","+yy),occupied=owner!==undefined&&owner!==this.moving?.id,territory=this.game.expansion.canBuild(type,xx,yy,1,1,this.moving);cells.push({x:xx,y:yy,occupied,territory,ok:!occupied&&territory})}return cells}
 entrance(type,x,y){let d=Settlement.BuildingDefs[type];if(d.road||d.wall||d.gate||type==="farm"||type==="archery"||d.remoteClaim)return null;let candidates=[{x:x+Math.floor(d.footprint[0]/2),y:y+d.footprint[1]},{x:x+d.footprint[0],y:y+Math.floor(d.footprint[1]/2)},{x:x-1,y:y+Math.floor(d.footprint[1]/2)},{x:x+Math.floor(d.footprint[0]/2),y:y-1}];return candidates.find(p=>this.game.grid.inBounds(p.x,p.y))||candidates[0]}
 roadAccess(type,x,y){let e=this.entrance(type,x,y);if(!e)return null;return [[1,0],[-1,0],[0,1],[0,-1],[0,0]].some(([dx,dy])=>this.game.roads?.isRoad(e.x+dx,e.y+dy))}
 affordability(cost){let missing=[];for(const[k,v]of Object.entries(cost||{})){let have=Math.floor(this.game.resources.v[k]||0);if(have<v)missing.push({resource:k,have,need:v,short:v-have})}return{ok:missing.length===0,missing}}
 paintPlan(){if(!this.isPaintType()||this.moving)return null;let d=Settlement.BuildingDefs[this.type],tiles=this.paintTiles.length?this.paintTiles:(this.hover?[this.hover]:[]),valid=[],invalid=[],skipped=[];for(const t of tiles){let owner=this.game.grid.occupied.get(t.x+","+t.y),b=owner!==undefined?this.game.buildings.byId(owner):null;if(b?.type===this.type){skipped.push(t);continue}let cells=this.footprint(this.type,t.x,t.y),ok=cells.every(c=>c.ok);(ok?valid:invalid).push({...t,cells})}let cost={};for(const[k,v]of Object.entries(d.cost||{}))cost[k]=v*valid.length;let money=this.affordability(cost);return{tiles,valid,invalid,skipped,cost,money,ok:valid.length>0&&invalid.length===0&&money.ok}}
 validateCurrent(){let plan=this.paintPlan();if(plan){let cells=[];for(const q of plan.valid)cells.push(...q.cells);for(const q of plan.invalid)cells.push(...q.cells);if(plan.invalid.length)return{ok:false,reason:`${plan.invalid.length} INVALID ${plan.invalid.length===1?"TILE":"TILES"}`,cells,paintPlan:plan};if(!plan.valid.length)return{ok:false,reason:"DRAG ACROSS EMPTY TILES TO DRAW",cells,paintPlan:plan};if(!plan.money.ok){let m=plan.money.missing[0],name=Settlement.ResourceDefs[m.resource]?.name||m.resource;return{ok:false,reason:"NEED "+m.short+" MORE "+String(name).toUpperCase(),cells,paintPlan:plan};return{ok:true,reason:`${plan.valid.length} ${this.type==="road"?"ROAD":"WALL"} ${plan.valid.length===1?"TILE":"TILES"} READY`,cells,paintPlan:plan}}
  return this.hover?this.validate(this.type,this.hover.x,this.hover.y):null}
 validate(type,x,y){let d=Settlement.BuildingDefs[type];if(!d)return{ok:false,reason:"UNKNOWN STRUCTURE",cells:[]};if(d.unique&&!this.moving&&this.game.buildings.list.some(b=>b.type===type))return{ok:false,reason:"THE SETTLEMENT HAS ONE "+String(d.name||type).toUpperCase(),cells:this.footprint(type,x,y)};if(this.moving?.type==="archery"){let rs=this.game.expansion.relocationStatus(this.moving,x,y),cells=this.footprint(type,x,y),blocked=cells.find(c=>c.occupied);if(blocked){let id=this.game.grid.occupied.get(blocked.x+","+blocked.y),b=id&&this.game.buildings.byId(id),name=b?Settlement.BuildingDefs[b.type]?.name:"structure";return{ok:false,reason:"BLOCKED BY "+String(name||"structure").toUpperCase(),cells}}if(!rs.ok)return{ok:false,reason:rs.reason,cells};return{ok:true,reason:rs.reason,cells}}
  let cells=this.footprint(type,x,y),outside=cells.find(c=>!c.territory);if(outside)return{ok:false,reason:(d.claimsTerritory||d.wall||d.gate||d.road)?"TOO FAR FROM YOUR BORDER":"OUTSIDE YOUR TERRITORY — BUILD AN ARCHERY TOWER",cells,entrance:this.entrance(type,x,y),roadAccess:this.roadAccess(type,x,y)};let blocked=cells.find(c=>c.occupied);if(blocked){let id=this.game.grid.occupied.get(blocked.x+","+blocked.y),b=id&&this.game.buildings.byId(id),name=b?Settlement.BuildingDefs[b.type]?.name:"structure";return{ok:false,reason:"BLOCKED BY "+String(name||"structure").toUpperCase(),cells,entrance:this.entrance(type,x,y),roadAccess:this.roadAccess(type,x,y)}}let money=this.moving?{ok:true,missing:[]}:this.affordability(d.cost);if(!money.ok){let m=money.missing[0],name=Settlement.ResourceDefs[m.resource]?.name||m.resource;return{ok:false,reason:"NEED "+m.short+" MORE "+name.toUpperCase(),cells,missing:money.missing,entrance:this.entrance(type,x,y),roadAccess:this.roadAccess(type,x,y)}}return{ok:true,reason:d.remoteClaim?"VALID DISTANT STRONGHOLD":"VALID LOCATION",cells,entrance:this.entrance(type,x,y),roadAccess:this.roadAccess(type,x,y)}}
 confirm(){if(!this.type||this.committing)return false;if(this.isPaintType()&&!this.moving)return this.confirmPaint();if(!this.hover)return false;this.committing=true;let type=this.type,{x,y}=this.hover,v=this.validate(type,x,y);this.lastValidation=v;if(!v.ok){this.committing=false;this.game.bus.emit("placement:validity",{type,hover:this.hover,validation:v});this.game.bus.emit("toast","⛔ "+v.reason);return false}if(this.moving){let b=this.moving;this.game.grid.free(b.id);b.x=x;b.y=y;this.game.grid.occupy(b.id,b.x,b.y,b.w,b.h);this.type=null;this.moving=null;this.hover=null;this.lastValidation=null;this.committing=false;this.game.housing?.reconcile();this.game.bus.emit("building:moved",b);this.game.bus.emit("toast",Settlement.BuildingDefs[b.type].name+" relocated.");this.game.bus.emit("placement:end");return b}let d=Settlement.BuildingDefs[type];if(!this.game.resources.spend(d.cost)){this.committing=false;this.game.bus.emit("toast","⛔ Resources changed — check the cost again.");return false}let b=this.game.buildings.create(type,x,y);this.game.bus.emit("placement:confirmed",{building:b,type,cost:d.cost,hover:{x,y}});this.game.bus.emit("construction:started",b);this.game.bus.emit("toast",d.name+" construction started.");this.type=null;this.hover=null;this.lastValidation=null;this.committing=false;this.game.bus.emit("placement:end");return b}
 confirmPaint(){let plan=this.paintPlan();if(!plan?.ok){this.lastValidation=this.validateCurrent();this.game.bus.emit("placement:validity",{type:this.type,hover:this.hover,validation:this.lastValidation});this.game.bus.emit("toast","⛔ "+(this.lastValidation?.reason||"INVALID PATH"));return false}this.committing=true;let type=this.type,d=Settlement.BuildingDefs[type];if(!this.game.resources.spend(plan.cost)){this.committing=false;this.game.bus.emit("toast","⛔ Resources changed — check the path cost again.");return false}let made=[];for(const t of plan.valid){let b=this.game.buildings.create(type,t.x,t.y);made.push(b);this.game.bus.emit("placement:confirmed",{building:b,type,cost:d.cost,hover:{x:t.x,y:t.y},batch:true});this.game.bus.emit("construction:started",b)}this.type=null;this.hover=null;this.paintTiles=[];this.painting=false;this.lastValidation=null;this.committing=false;this.game.bus.emit("toast",`${made.length} ${type==="road"?"road":"wall"} ${made.length===1?"tile":"tiles"} placed.`);this.game.bus.emit("placement:end");return made}
};