Settlement.PassiveProductionSystem=class{
 constructor(game){this.game=game}
 definition(b){let d=Settlement.BuildingDefs[b.type];if(!d)return null;let lv=Array.isArray(d.levels)?d.levels.find(x=>x.level===(b.level||1)):null;return(lv&&lv.production)||d.production||null}
 state(b){if(!b.passiveProduction)b.passiveProduction={progress:{}};if(!b.passiveProduction.progress)b.passiveProduction.progress={};return b.passiveProduction}
 baseRatePerDay(b,k){let d=this.definition(b);return d?(Number(d[k])||0)*Math.max(0,b.workers||0):0}
 productionFactor(){return this.game.happiness?.productionFactor()||1}
 ratePerDay(b,k){return this.baseRatePerDay(b,k)*this.productionFactor()}
 totalPerDay(){let out={};for(const b of this.game.buildings.list){let d=this.definition(b);if(!d||!b.complete||(b.workers||0)<=0)continue;for(const k of Object.keys(d))out[k]=(out[k]||0)+this.ratePerDay(b,k)}return out}
 status(b){let d=this.definition(b);if(!d)return{state:"NONE",label:"No passive production"};if(!b.complete)return{state:"CONSTRUCTION",label:"Under construction"};if((b.workers||0)<=0)return{state:"NEEDS_WORKER",label:"Needs worker"};let keys=Object.keys(d),open=keys.find(k=>!this.game.resources.isStoredResource(k)||this.game.resources.remainingCapacity(k)>0);if(!open)return{state:"STORAGE_FULL",label:keys.length===1?(Settlement.ResourceDefs[keys[0]]?.name||keys[0])+" storage full":"Output storage full"};let s=this.state(b),first=open,perDay=this.ratePerDay(b,first),frac=(s.progress[first]||0)%1,seconds=perDay>0?(1-frac)*Settlement.Config.DAY_SECONDS/perDay:Infinity;return{state:"WORKING",label:"Working",resource:first,perDay,progress:frac,secondsToNext:seconds}}
 update(dt){for(const b of this.game.buildings.list){let d=this.definition(b);if(!d||!b.complete||(b.workers||0)<=0)continue;let s=this.state(b);for(const k of Object.keys(d)){let perDay=this.ratePerDay(b,k),rate=perDay/Settlement.Config.DAY_SECONDS;if(rate<=0)continue;s.progress[k]=(s.progress[k]||0)+rate*dt;let units=Math.floor(s.progress[k]);if(units<1)continue;let accepted=this.game.resources.add({[k]:units}),made=Math.floor(accepted[k]||0);if(made>0){s.progress[k]-=made;this.game.bus.emit("passive:produced",{building:b,resource:k,amount:made,ratePerDay:perDay})}if(made<units)s.progress[k]=Math.min(s.progress[k],.999)}}}
};
