Settlement.EnemyDirector=class{
 constructor(game){this.game=game;this.list=[];this.next=1;this.timer=95}
 spawnTile(){let g=this.game,owned=g.expansion.claimedTiles(),dirs=[[1,0],[-1,0],[0,1],[0,-1]],pick=null,n=0;for(const key of owned){let[x,y]=key.split(",").map(Number);for(const[dx,dy]of dirs){if(g.expansion.isClaimed(x+dx,y+dy))continue;let sx=x+dx*4,sy=y+dy*4;if(!g.grid.inBounds(sx,sy)||g.expansion.isClaimed(sx,sy)||g.grid.occupied.has(sx+","+sy))continue;if(g.walls?.blocksWorld((sx+.5)*64,(sy+.5)*64))continue;n++;if(Math.random()*n<1)pick={x:sx,y:sy}}}return pick}
 spawn(){let p=this.spawnTile();if(!p)return false;let d=Settlement.EnemyDefs.bandit,e={id:this.next++,type:"bandit",x:(p.x+.5)*64,y:(p.y+.5)*64,hp:d.hp,maxHp:d.hp,state:"seeking",target:null,cargo:null,stealT:0,dead:false,rewarded:false,escape:{x:(p.x+.5)*64,y:(p.y+.5)*64}};this.list.push(e);this.game.bus.emit("enemy:spotted",e);this.game.bus.emit("toast","⚠️ Bandit raider spotted — protect your stores!");return e}
 targetFor(e){let g=this.game,prefs=[{type:"market",keys:["gold","tools","ironBar","bread"]},{type:"warehouse",keys:["stone","wood","food","ironOre","ironBar","tools","bread","cutStone"]},{type:"blacksmith",keys:["tools","ironBar"]},{type:"smelter",keys:["ironBar","ironOre"]},{type:"ironMine",keys:["ironOre"]},{type:"bakery",keys:["bread","food"]},{type:"quarry",keys:["stone","cutStone"]},{type:"lumber",keys:["wood"]},{type:"farm",keys:["food"]}];for(let p of prefs){let b=g.buildings.list.find(x=>x.complete&&x.type===p.type);if(!b)continue;let key=p.keys.find(k=>this.stealable(e,k)>0);if(key)return{building:b,resource:key}}return null}
 stealable(e,k){let g=this.game,d=Settlement.EnemyDefs[e.type],v=Math.max(0,Number(g.resources.v[k])||0),t=d.theft||{},reserve=k==="gold"?Math.max(40,t.reserve||0):(t.reserve||0),available=Math.max(0,v-reserve);return Math.max(0,Math.floor(Math.min(t.max||10,available*(t.percent||.08),available)))}
 move(e,tx,ty,dt){let d=Settlement.EnemyDefs[e.type],dx=tx-e.x,dy=ty-e.y,dist=Math.hypot(dx,dy)||1;if(dist<8)return true;let nx=e.x+dx/dist*d.speed*dt,ny=e.y+dy/dist*d.speed*dt;if(!this.game.walls?.blocksWorld(nx,ny)){e.x=nx;e.y=ny}return false}
 commitSteal(e){if(e.cargo||e.state!=="stealing"||!e.target)return false;let k=e.target.resource,n=this.stealable(e,k);if(n<=0)return false;let taken=this.game.resources.consume(k,n);if(taken<=0)return false;e.cargo={resource:k,amount:taken,recovered:false};e.state="escaping";let def=Settlement.ResourceDefs[k],name=def?.name||k;this.game.bus.emit("toast",`🏴 Raider stole ${taken} ${name}! Stop them!`);return true}
 recover(e){if(!e.cargo||e.cargo.recovered)return null;let c=e.cargo;c.recovered=true;this.game.resources.v[c.resource]=(this.game.resources.v[c.resource]||0)+c.amount;this.game.resources.changed();return c}
 rollLoot(e){let d=Settlement.EnemyDefs[e.type],table=(d.lootTable||[]).filter(x=>!x.requires||(this.game.resources.v[x.requires]||0)>0||this.game.buildings.list.some(b=>b.complete&&["bakery","mason","ironMine","smelter","blacksmith"].includes(b.type)));if(!table.length)return null;let total=table.reduce((n,x)=>n+x.weight,0),r=Math.random()*total,pick=table[0];for(let x of table){r-=x.weight;if(r<=0){pick=x;break}}let amount=pick.min+Math.floor(Math.random()*(pick.max-pick.min+1)),accepted=this.game.resources.add({[pick.resource]:amount}),got=accepted[pick.resource]||0;return got>0?{resource:pick.resource,amount:got}:null}
 kill(e){if(!e||e.dead)return;e.dead=true;if(e.rewarded)return;e.rewarded=true;let d=Settlement.EnemyDefs[e.type],cargo=this.recover(e),base=this.game.resources.add(d.reward),loot=this.rollLoot(e);if(cargo){let n=Settlement.ResourceDefs[cargo.resource]?.name||cargo.resource;this.game.bus.emit("toast",`🛡️ Recovered ${cargo.amount} ${n}.`);this.game.effects.float(e.x/64,e.y/64,`RECOVERED +${cargo.amount}`)}if(base.gold)this.game.effects.float(e.x/64,e.y/64,"+"+base.gold+" 🪙");if(loot){let n=Settlement.ResourceDefs[loot.resource]?.name||loot.resource;this.game.bus.emit("toast",`🎁 Spoils: +${loot.amount} ${n}`)}this.game.bus.emit("enemy:defeated",e);this.list=this.list.filter(x=>x!==e)}
 escape(e){if(e.dead)return;e.dead=true;e.state="escaped";if(e.cargo){let n=Settlement.ResourceDefs[e.cargo.resource]?.name||e.cargo.resource;this.game.bus.emit("toast",`🏴 Raider escaped with ${e.cargo.amount} ${n}.`)}this.game.bus.emit("enemy:escaped",e);this.list=this.list.filter(x=>x!==e)}
 update(dt){if(document.hidden)return;this.timer-=dt;if(this.timer<=0&&this.game.buildings.count("archery")>0){this.spawn();this.timer=80+Math.random()*80}for(let e of [...this.list]){if(e.dead)continue;if(e.state==="seeking"){e.target=this.targetFor(e);if(!e.target){e.state="escaping";continue}e.state="moving"}if(e.state==="moving"){let b=e.target?.building;if(!b||!b.complete||!this.game.buildings.list.includes(b)){e.target=null;e.state="seeking";continue}if(this.move(e,(b.x+b.w/2)*64,(b.y+b.h/2)*64,dt)){e.state="stealing";e.stealT=0}}else if(e.state==="stealing"){e.stealT+=dt;let d=Settlement.EnemyDefs[e.type];if(e.stealT>=(d.theft?.stealTime||2.4)){if(!this.commitSteal(e)){e.target=null;e.state="seeking"}}}else if(e.state==="escaping"){if(this.move(e,e.escape.x,e.escape.y,dt))this.escape(e)}}}
};
