Settlement.EnemyDirector=class{
 constructor(game){this.game=game;this.list=[];this.next=1;this.timer=80;this.raidIndex=0;this.bossCooldown=0;this.siegeCooldown=0;this.siegeRaids=new Set;this.factions=["Black Banner","Wolf Clan","Ashen Company","Hollow Men","Crimson Brotherhood"]}
 spawnTile(){let g=this.game,owned=g.expansion.claimedTiles(),dirs=[[1,0],[-1,0],[0,1],[0,-1]],pick=null,n=0;for(const key of owned){let[x,y]=key.split(",").map(Number);for(const[dx,dy]of dirs){if(g.expansion.isClaimed(x+dx,y+dy))continue;let sx=x+dx*4,sy=y+dy*4;if(!g.grid.inBounds(sx,sy)||g.expansion.isClaimed(sx,sy)||g.grid.occupied.has(sx+","+sy))continue;if(g.walls?.blocksWorld((sx+.5)*64,(sy+.5)*64))continue;n++;if(Math.random()*n<1)pick={x:sx,y:sy}}}return pick}
 threatScore(){let g=this.game,wealth=(g.resources.v.gold||0)/500+(g.resources.v.ironBar||0)/20+(g.resources.v.tools||0)/15,pop=g.citizens.list.length/12,lvl=(g.xp?.level||1)/4,def=(g.security?.summary?.().value||0)/35;return Math.max(1,wealth+pop+lvl-def*.45)}
 makeEnemy(type,p,ox=0,oy=0,meta={}){let d=Settlement.EnemyDefs[type]||Settlement.EnemyDefs.bandit,e={id:this.next++,type,x:(p.x+.5)*64+ox,y:(p.y+.5)*64+oy,hp:d.hp,maxHp:d.hp,state:"seeking",target:null,cargo:null,stealT:0,dead:false,rewarded:false,escape:{x:(p.x+.5)*64+ox,y:(p.y+.5)*64+oy},raidId:this.raidIndex,spawnedAt:performance.now(),faction:meta.faction||"Black Banner",siege:!!meta.siege};if(d.boss){let id=this.game.legends?.identity?.(e);if(id){e.displayName=id.name;e.trait=id.trait;e.faction=id.faction}}this.list.push(e);this.game.bus.emit("enemy:spotted",e);return e}
 spawn(type="bandit"){let p=this.spawnTile();if(!p)return false;let e=this.makeEnemy(type,p);this.game.bus.emit("toast",Settlement.EnemyDefs[type]?.boss?`☠️ ${e.displayName||"BLACK BANNER CAPTAIN"} SPOTTED — legendary loot if defeated!`:"⚠️ Raider spotted — protect your stores!");return e}
 spawnRaid(forceSiege=false){let p=this.spawnTile();if(!p)return false;this.raidIndex++;if(this.bossCooldown>0)this.bossCooldown--;if(this.siegeCooldown>0)this.siegeCooldown--;let score=this.threatScore(),faction=this.factions[(this.raidIndex+Math.floor(score))%this.factions.length],siege=!!forceSiege||(score>=7&&this.siegeCooldown<=0&&Math.random()<.12),count=Math.max(2,Math.min(siege?10:7,2+Math.floor(score/2))),types=[];if(siege){for(let i=0;i<count;i++)types.push(i===0?"siegeRam":i%4===0?"brute":"siegeRaider");this.siegeCooldown=5;this.siegeRaids.add(this.raidIndex)}else for(let i=0;i<count;i++)types.push(i===0&&score>4?"brute":i%3===0?"scout":"bandit");let boss=false;if(this.bossCooldown<=0&&score>=3&&(siege||Math.random()<.22)){types.push("raiderCaptain");boss=true;this.bossCooldown=3}let spawned=[];for(let i=0;i<types.length;i++){let a=i*.9,r=18+Math.floor(i/3)*13;spawned.push(this.makeEnemy(types[i],p,Math.cos(a)*r,Math.sin(a)*r,{faction,siege}))}let captain=spawned.find(e=>Settlement.EnemyDefs[e.type]?.boss);this.game.bus.emit("raid:started",{id:this.raidIndex,count:types.length,boss,siege,faction,captain});this.game.bus.emit("toast",siege?`🚨 SIEGE! ${faction} sends ${types.length} attackers${captain?` under ${captain.displayName}`:""}.`:boss?`☠️ ${faction} raid! ${types.length} hostiles under ${captain?.displayName||"a Captain"}.`:`⚔️ ${faction} raid! ${types.length} hostiles are probing the settlement.`);return true}
 defensePressureAt(x,y){let n=0;for(const b of this.game.buildings.list){if(!b.complete)continue;let d=Settlement.BuildingDefs[b.type];if(!(b.type==="archery"||d?.defenseTurret))continue;let r=((d.range||4)*64),dx=(b.x+b.w/2)*64-x,dy=(b.y+b.h/2)*64-y;if(dx*dx+dy*dy<=r*r)n++}return n}
 targetFor(e){let g=this.game,prefs=[{type:"hallOfLegends",keys:["gold","tools","ironBar"],value:11},{type:"market",keys:["gold","tools","ironBar","bread"],value:8},{type:"warehouse",keys:["stone","wood","food","ironOre","ironBar","tools","bread","cutStone"],value:7},{type:"blacksmith",keys:["tools","ironBar"],value:6},{type:"smelter",keys:["ironBar","ironOre"],value:5},{type:"ironMine",keys:["ironOre"],value:4},{type:"bakery",keys:["bread","food"],value:4},{type:"quarry",keys:["stone","cutStone"],value:3},{type:"lumber",keys:["wood"],value:3},{type:"farm",keys:["food"],value:2}],best=null,bestScore=-1e9;for(let p of prefs){for(let b of g.buildings.list){if(!b.complete||b.type!==p.type)continue;let key=p.keys.find(k=>this.stealable(e,k)>0);if(!key)continue;let x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64,dist=Math.hypot(x-e.x,y-e.y)/64,pressure=this.defensePressureAt(x,y),score=p.value*3-dist-pressure*4+Math.random()*2;if(score>bestScore){bestScore=score;best={building:b,resource:key}}}}return best}
 stealable(e,k){let g=this.game,d=Settlement.EnemyDefs[e.type],v=Math.max(0,Number(g.resources.v[k])||0),t=d.theft||{},reserve=k==="gold"?Math.max(40,t.reserve||0):(t.reserve||0),available=Math.max(0,v-reserve);return Math.max(0,Math.floor(Math.min(t.max||10,available*(t.percent||.08),available)))}
 move(e,tx,ty,dt){let d=Settlement.EnemyDefs[e.type],dx=tx-e.x,dy=ty-e.y,dist=Math.hypot(dx,dy)||1;if(dist<8)return true;let mult=this.game.frontier?.enemySpeedMultiplier?.(e)||1,nx=e.x+dx/dist*d.speed*mult*dt,ny=e.y+dy/dist*d.speed*mult*dt;if(!this.game.walls?.blocksWorld(nx,ny)){e.x=nx;e.y=ny}return false}
 commitSteal(e){if(e.cargo||e.state!=="stealing"||!e.target)return false;let k=e.target.resource,n=this.stealable(e,k);if(n<=0)return false;let taken=this.game.resources.consume(k,n);if(taken<=0)return false;e.cargo={resource:k,amount:taken,recovered:false};e.state="escaping";let def=Settlement.ResourceDefs[k],name=def?.name||k;this.game.bus.emit("toast",`🏴 ${e.faction||"Raider"} stole ${taken} ${name}! Stop them!`);return true}
 recover(e){if(!e.cargo||e.cargo.recovered)return null;let c=e.cargo;c.recovered=true;this.game.resources.v[c.resource]=(this.game.resources.v[c.resource]||0)+c.amount;this.game.resources.changed();return c}
 rollLoot(e){let d=Settlement.EnemyDefs[e.type],table=(d.lootTable||[]).filter(x=>!x.requires||(this.game.resources.v[x.requires]||0)>0||this.game.buildings.list.some(b=>b.complete&&["bakery","mason","ironMine","smelter","blacksmith"].includes(b.type)));if(!table.length)return null;let total=table.reduce((n,x)=>n+x.weight,0),r=Math.random()*total,pick=table[0];for(let x of table){r-=x.weight;if(r<=0){pick=x;break}}let amount=pick.min+Math.floor(Math.random()*(pick.max-pick.min+1)),accepted=this.game.resources.add({[pick.resource]:amount}),got=accepted[pick.resource]||0;return got>0?{resource:pick.resource,amount:got}:null}
 bossLoot(e){let d=Settlement.EnemyDefs[e.type];if(!d?.bossLoot?.length)return[];let picks=[...d.bossLoot].sort(()=>Math.random()-.5).slice(0,2),out=[];for(let p of picks){let amount=p.min+Math.floor(Math.random()*(p.max-p.min+1)),a=this.game.resources.add({[p.resource]:amount}),got=a[p.resource]||0;if(got)out.push({resource:p.resource,amount:got})}return out}
 kill(e){if(!e||e.dead)return;e.dead=true;if(e.rewarded)return;e.rewarded=true;let d=Settlement.EnemyDefs[e.type],cargo=this.recover(e),base=this.game.resources.add(d.reward),loot=this.rollLoot(e),bossLoot=d.boss?this.bossLoot(e):[];if(cargo){let n=Settlement.ResourceDefs[cargo.resource]?.name||cargo.resource;this.game.bus.emit("toast",`🛡️ Recovered ${cargo.amount} ${n}.`);this.game.effects.float(e.x/64,e.y/64,`RECOVERED +${cargo.amount}`)}if(base.gold)this.game.effects.float(e.x/64,e.y/64,"+"+base.gold+" 🪙");if(loot){let n=Settlement.ResourceDefs[loot.resource]?.name||loot.resource;this.game.bus.emit("toast",`🎁 Spoils: +${loot.amount} ${n}`)}if(bossLoot.length){let text=bossLoot.map(x=>`${x.amount} ${Settlement.ResourceDefs[x.resource]?.name||x.resource}`).join(" + ");this.game.bus.emit("toast",`🏆 BOSS LOOT: ${text}`);this.game.bus.emit("boss:defeated",{enemy:e,loot:bossLoot})}this.game.bus.emit("enemy:defeated",e);this.list=this.list.filter(x=>x!==e);this.checkSiegeVictory(e.raidId)}
 checkSiegeVictory(raidId){if(!this.siegeRaids.has(raidId)||this.list.some(x=>!x.dead&&x.raidId===raidId))return;this.siegeRaids.delete(raidId);this.game.stats.siegesWon=(this.game.stats.siegesWon||0)+1;this.game.legends?.record?.("A major siege was broken and the attackers driven from the frontier.","siege");this.game.bus.emit("toast","🎉 SIEGE BROKEN — the settlement celebrates!");this.game.bus.emit("celebration:legend",{siege:true})}
 escape(e){if(e.dead)return;e.dead=true;e.state="escaped";if(e.cargo){let n=Settlement.ResourceDefs[e.cargo.resource]?.name||e.cargo.resource;this.game.bus.emit("toast",`🏴 Raider escaped with ${e.cargo.amount} ${n}.`)}this.game.bus.emit("enemy:escaped",e);this.list=this.list.filter(x=>x!==e);if(!this.list.some(x=>!x.dead&&x.raidId===e.raidId))this.siegeRaids.delete(e.raidId)}
 shouldRetreat(e){if(Settlement.EnemyDefs[e.type]?.boss||e.siege)return false;let age=(performance.now()-e.spawnedAt)/1000,ratio=e.hp/e.maxHp,alive=this.list.filter(x=>!x.dead&&x.raidId===e.raidId).length;return age>18&&(ratio<.28||alive===1)&&!e.cargo}
 update(dt){if(document.hidden)return;this.timer-=dt;if(this.timer<=0&&this.game.buildings.list.some(b=>b.complete&&(b.type==="archery"||Settlement.BuildingDefs[b.type]?.defenseTurret))){this.spawnRaid();this.timer=95+Math.random()*95}for(let e of [...this.list]){if(e.dead)continue;if(this.shouldRetreat(e)&&e.state!=="escaping"){e.state="escaping";this.game.bus.emit("enemy:retreating",e)}if(e.state==="seeking"){e.target=this.targetFor(e);if(!e.target){e.state="escaping";continue}e.state="moving"}if(e.state==="moving"){let b=e.target?.building;if(!b||!b.complete||!this.game.buildings.list.includes(b)){e.target=null;e.state="seeking";continue}if(this.move(e,(b.x+b.w/2)*64,(b.y+b.h/2)*64,dt)){e.state="stealing";e.stealT=0}}else if(e.state==="stealing"){e.stealT+=dt;let d=Settlement.EnemyDefs[e.type];if(e.stealT>=(d.theft?.stealTime||2.4)){if(!this.commitSteal(e)){e.target=null;e.state="seeking"}}}else if(e.state==="escaping"){if(this.move(e,e.escape.x,e.escape.y,dt))this.escape(e)}}}
};
