Settlement.FrontierWarfareSystem=class{
 constructor(game){this.game=game;this.tick=.1;this.trapCool=new Map;this.alert=false;this.lastRaidToast=0;if(!game.stats.frontierZones)game.stats.frontierZones=[];game.bus.on("raid:started",r=>this.onRaid(r));game.bus.on("boss:defeated",x=>{game.stats.bossesDefeated=(game.stats.bossesDefeated||0)+1});game.bus.on("enemy:defeated",()=>this.refreshAlert())}
 zones(){return this.game.stats.frontierZones||[]}
 addZone(mode="HOLD"){let T=Settlement.Config.TILE,x=Math.floor(this.game.camera.x/T),y=Math.floor(this.game.camera.y/T),z={id:Date.now()+Math.floor(Math.random()*999),mode,x,y,radius:4};this.zones().push(z);this.game.guards?.routes?.clear?.();this.game.bus.emit("toast",`🛡️ ${mode} zone established.`);return z}
 removeZone(id){let a=this.zones(),i=a.findIndex(z=>z.id===Number(id));if(i<0)return false;a.splice(i,1);this.game.guards?.routes?.clear?.();this.game.bus.emit("toast","Defense zone removed.");return true}
 guardPoints(){let out=[];for(const z of this.zones()){let r=z.radius||4;out.push({x:z.x,y:z.y,zone:z.mode});out.push({x:z.x+r,y:z.y,zone:z.mode});out.push({x:z.x-r,y:z.y,zone:z.mode});out.push({x:z.x,y:z.y+r,zone:z.mode});out.push({x:z.x,y:z.y-r,zone:z.mode})}return out.filter(p=>this.game.grid.inBounds(p.x,p.y)&&this.game.expansion.isClaimed(p.x,p.y))}
 onRaid(r){this.alert=true;this.game.stats.raidsSeen=(this.game.stats.raidsSeen||0)+1;this.shelterFreeCitizens();if(r?.boss)this.game.stats.bossEncounters=(this.game.stats.bossEncounters||0)+1}
 refreshAlert(){this.alert=this.game.enemies.list.some(e=>!e.dead)}
 shelterFreeCitizens(){for(const c of this.game.citizens.list){if(c.job==="Guard"||c.job==="Archer")continue;let s=String(c.state||"").toUpperCase();if(!["WANDERING","SOCIALIZING","IDLE","LEISURE"].includes(s))continue;if(!c.home)continue;c.state="TRAVEL_HOME";c.frontierShelter=true;c.path=[];c.pathIndex=0;this.game.amenities?.releaseCitizen?.(c.id)}}
 nearbyDefense(type,x,y,rTiles){let T=64,r=rTiles*T,r2=r*r;return this.game.buildings.list.filter(b=>b.complete&&b.type===type&&(((b.x+b.w/2)*T-x)**2+((b.y+b.h/2)*T-y)**2<=r2))}
 enemySpeedMultiplier(e){let m=1;for(const b of this.game.buildings.list){if(!b.complete||!Settlement.BuildingDefs[b.type]?.defenseSlow)continue;let d=Settlement.BuildingDefs[b.type],x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64;if(Math.hypot(e.x-x,e.y-y)<=(d.slowRadius||1.25)*64)m=Math.min(m,d.slowFactor||.6)}return m}
 updateTraps(dt){for(const[id,v]of this.trapCool)this.trapCool.set(id,Math.max(0,v-dt));for(const b of this.game.buildings.list){let d=Settlement.BuildingDefs[b.type];if(!b.complete||!d?.defenseTrap||(this.trapCool.get(b.id)||0)>0)continue;let x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64,e=this.game.enemies.list.find(e=>!e.dead&&Math.hypot(e.x-x,e.y-y)<42);if(!e)continue;e.hp-=d.trapDamage||10;this.game.effects.float(e.x/64,e.y/64,`SPIKES -${d.trapDamage||10}`);this.game.bus.emit("defense:trap",{building:b,target:e});this.trapCool.set(b.id,d.trapCooldown||2.5);if(e.hp<=0)this.game.enemies.kill(e)}}
 update(dt){if(document.hidden)return;this.tick-=dt;if(this.tick>0)return;let step=.15;this.tick=step;this.updateTraps(step);this.refreshAlert();if(!this.alert){for(const c of this.game.citizens.list)if(c.frontierShelter)delete c.frontierShelter}}
 summary(){return{alert:this.alert,raids:this.game.stats.raidsSeen||0,bosses:this.game.stats.bossesDefeated||0,zones:this.zones().length}}
};
