Settlement.GuardSystem=class{
 constructor(game){this.game=game;this.states=new Map;this.routes=new Map;for(const ev of["building:created","building:removed","building:complete","building:moved","building:upgraded","territory:claimed"])game.bus.on(ev,()=>this.routes.clear())}
 guards(){return this.game.citizens.list.filter(c=>c.job==="Guard"&&c.workplace&&this.game.buildings.byId(c.workplace)?.type==="barracks")}
 capacity(b){if(!b||b.type!=="barracks")return 0;let d=Settlement.BuildingDefs.barracks,l=Math.max(1,Math.min(d.levels?.length||15,b.level||1));return d.levels?.[l-1]?.guardCapacity||1}
 assigned(b){return this.guards().filter(c=>c.workplace===b.id)}
 assign(b){if(!b?.complete||b.type!=="barracks"||this.assigned(b).length>=this.capacity(b))return false;let c=this.game.citizens.list.find(x=>x.job==="Unassigned");if(!c)return false;c.job="Guard";c.workplace=b.id;c.state="WORKING";c.path=[];c.pathIndex=0;b.workers=this.assigned(b).length;this.states.delete(c.id);this.game.bus.emit("citizens:changed");this.game.bus.emit("security:changed");return c}
 unassign(c){if(!c||c.job!=="Guard")return false;let b=this.game.buildings.byId(c.workplace);c.job="Unassigned";c.workplace=null;c.state="WANDERING";c.path=[];c.pathIndex=0;this.states.delete(c.id);if(b)b.workers=this.assigned(b).length;this.game.bus.emit("citizens:changed");this.game.bus.emit("security:changed");return true}
 state(c){let s=this.states.get(c.id);if(!s){s={mode:"muster",path:[],pathIndex:0,waypoint:0,targetId:null,attack:0,decision:Math.random()*.35};this.states.set(c.id,s)}return s}
 tile(c){let T=Settlement.Config.TILE;return{x:Math.floor(c.x/T),y:Math.floor(c.y/T)}}
 setPath(c,s,target,mode){if(!target)return false;let start=this.tile(c);s.mode=mode;s.target=target;s.path=[];s.pathIndex=0;if(start.x===target.x&&start.y===target.y)return true;let p=this.game.pathfinding.find(start,target);if(!p?.length)return false;s.path=p;s.pathIndex=Math.min(1,p.length-1);return true}
 move(c,s,dt){let T=Settlement.Config.TILE,p=s.path?.[s.pathIndex];if(!p)return true;let tx=(p.x+.5)*T,ty=(p.y+.5)*T,dx=tx-c.x,dy=ty-c.y,d=Math.hypot(dx,dy);if(d<5){s.pathIndex++;if(s.pathIndex>=s.path.length){s.path=[];return true}}else{let road=this.game.roads.isRoad(Math.floor(c.x/T),Math.floor(c.y/T))?this.game.roads.speedMultiplier:1,relic=this.game.legends?.relicBonus?.(c)||{speed:1};c.x+=dx/d*c.speed*road*(relic.speed||1)*dt;c.y+=dy/d*c.speed*road*(relic.speed||1)*dt}return false}
 patrolPoints(b){if(this.routes.has(b.id))return this.routes.get(b.id);let g=this.game,types=["gate","market","warehouse","mainHall","hallOfLegends","archery","watchBeacon"],pts=[],home=g.roads.entrance(b);if(home)pts.push(home);for(const p of g.frontier?.guardPoints?.()||[])pts.push({x:p.x,y:p.y});for(let type of types){for(let x of g.buildings.list){if(!x.complete||x.type!==type)continue;let p=g.roads.entrance(x)||{x:Math.floor(x.x+x.w/2),y:Math.floor(x.y+x.h/2)};if(p)pts.push(p);if(pts.length>=12)break}if(pts.length>=12)break}if(pts.length<2){let p=g.roads.nearestRoadTarget();if(p)pts.push(p)}this.routes.set(b.id,pts);return pts}
 threatFor(c){let range=this.game.security.responseRange(),current=[];for(let e of this.game.enemies.list){if(e.dead)continue;let d=Math.hypot(e.x-c.x,e.y-c.y);if(d<=range)current.push({e,d,priority:Settlement.EnemyDefs[e.type]?.boss?6:e.cargo?4:e.state==="stealing"?3:e.type==="brute"||e.type==="siegeRam"?2:1})}if(!current.length)return null;let counts=new Map;for(let s of this.states.values())if(s.targetId)counts.set(s.targetId,(counts.get(s.targetId)||0)+1);current.sort((a,b)=>b.priority-a.priority||((counts.get(a.e.id)||0)-(counts.get(b.e.id)||0))||a.d-b.d);return current[0].e}
 activeHour(){return true}
 decide(c,s){let b=this.game.buildings.byId(c.workplace);if(!b?.complete){this.unassign(c);return}let threat=this.threatFor(c);if(threat){s.targetId=threat.id;if(!this.setPath(c,s,{x:Math.floor(threat.x/64),y:Math.floor(threat.y/64)},"responding"))s.targetId=null;return}let pts=this.patrolPoints(b);if(!pts.length)return;s.targetId=null;s.waypoint=(s.waypoint+1)%pts.length;this.setPath(c,s,pts[s.waypoint],this.game.frontier?.alert?"alert-patrol":"patrolling")}
 combat(c,s,dt){let e=s.targetId&&this.game.enemies.list.find(x=>x.id===s.targetId&&!x.dead);if(!e){s.targetId=null;return false}let d=Math.hypot(e.x-c.x,e.y-c.y);if(d>30){if(!s.path.length||s.pathIndex>=s.path.length){if(!this.setPath(c,s,{x:Math.floor(e.x/64),y:Math.floor(e.y/64)},"responding")){s.targetId=null;return false}}return false}s.mode="engaging";s.path=[];if(s.attack<=0){let rank=this.game.legends?.rank?.(c)||"Recruit",rankBonus=rank==="Champion"?2:rank==="Elite"?1.3:rank==="Veteran"?.7:0,relic=this.game.legends?.relicBonus?.(c)||{combat:0};s.attack=Math.max(.72,1.25-rankBonus*.08);let dmg=(Settlement.EnemyDefs[e.type]?.boss?4:3)+rankBonus+(relic.combat||0);e.hp-=dmg;this.game.effects.float(e.x/64,e.y/64,`⚔ -${Math.round(dmg*10)/10}`);if(e.hp<=0){this.game.enemies.kill(e);this.game.legends?.credit?.(c,"Guard");s.targetId=null;this.game.bus.emit("guard:intercepted",c);return true}}return false}
 update(dt){if(document.hidden)return;for(let c of this.guards()){let s=this.state(c);s.decision-=dt;s.attack=Math.max(-1,s.attack-dt);if(s.targetId)this.combat(c,s,dt);if(!s.targetId&&s.decision<=0){s.decision=this.game.security.decisionInterval()+Math.random()*.15;this.decide(c,s)}let arrived=this.move(c,s,dt);if(arrived)s.decision=0;c.state="WORKING"}let live=new Set(this.guards().map(c=>c.id));for(let id of this.states.keys())if(!live.has(id))this.states.delete(id)}
 presentation(c){let s=this.states.get(c.id);return s?{mode:s.mode,targetId:s.targetId,rank:this.game.legends?.rank?.(c)||"Recruit"}:null}
};
