Settlement.SaveManager=class{
 constructor(game){this.game=game;this.key="theSettlement.save.v1";this.status="Ready";this.timer=0;this.hydrated=false;this.backgroundAt=null;document.addEventListener("visibilitychange",()=>{if(!document.hidden)this.resumeBackground()})}
 save(){if(!this.hydrated)return false;if(document.hidden&&this.backgroundAt==null)this.backgroundAt=Date.now();try{localStorage.setItem(this.key,JSON.stringify(Settlement.SaveSchema.create(this.game)));this.status="Saved "+new Date().toLocaleTimeString();this.game.bus.emit("save:status",this.status);return true}catch(e){this.status="Save failed";console.error(e);return false}}
 load(){let raw=localStorage.getItem(this.key);if(!raw){this.hydrated=true;return null}try{let parsed=JSON.parse(raw),migrated=Settlement.MigrationManager.migrate(parsed);if(!migrated)throw new Error("Unsupported save version: "+parsed?.saveVersion);return migrated}catch(e){console.error(e);this.status="Save load failed";return null}}
 storeOfflineGain(gain={}){let r=this.game.resources,stored=[],other={},total=0;for(const[k,raw]of Object.entries(gain)){let v=Number(raw)||0;if(!v)continue;if(v>0&&r.isStoredResource(k)){stored.push({k,v});total+=v}else other[k]=v}let room=Math.max(0,Math.floor(r.remainingCapacity()));if(total<=room){for(const x of stored)other[x.k]=x.v;return r.add(other)}if(room>0&&total>0){let shares=stored.map((x,i)=>{let exact=x.v*room/total,take=Math.floor(exact);return{...x,i,take,frac:exact-take}}),used=shares.reduce((n,x)=>n+x.take,0),left=room-used;shares.slice().sort((a,b)=>b.frac-a.frac||a.i-b.i).forEach(x=>{if(left>0&&x.take<x.v){x.take++;left--}});for(const x of shares)if(x.take>0)other[x.k]=x.take}return r.add(other)}
 applyOfflineSince(last,show=true){let g=this.game,off=Settlement.OfflineProgress.calculate(g,last),stored=this.storeOfflineGain(off.gain);off.gain=stored;if(show&&off.seconds>60)g.ui.showOffline(off);return off}
 resumeBackground(){if(!this.hydrated||this.backgroundAt==null)return null;let last=this.backgroundAt;this.backgroundAt=null;let off=this.applyOfflineSince(last,true);this.save();return off}
 apply(s){let g=this.game;if(!s||s.saveVersion!==Settlement.SaveSchema.version)return false;g.resources.v={...g.resources.v,...s.resources};g.xp.xp=s.xp?.xp||0;g.xp.level=s.xp?.level||1;Object.assign(g.clock,s.clock||{});g.buildings.list=s.buildings||[];g.buildings.next=Math.max(1,...g.buildings.list.map(b=>b.id+1));g.grid.occupied.clear();g.buildings.list.forEach(b=>g.grid.occupy(b.id,b.x,b.y,b.w,b.h));g.citizens.list=s.citizens||[];g.citizens.next=Math.max(1,...g.citizens.list.map(c=>c.id+1));g.farms.plots=new Map(s.farms||[]);g.quests.index=s.quests?.index||0;if(s.expansion){g.expansion.claimedRects=s.expansion.claimedRects||g.expansion.claimedRects;g.expansion.claimed=s.expansion.claimed||0;g.expansion.invalidate?.()}g.stats={...g.stats,...s.stats};if(g.immigration)Object.assign(g.immigration,s.immigration||{});g.housing?.reconcile();if(g.commerce)g.commerce.apply(s.commerce);this.applyOfflineSince(s.savedAt||Date.now(),true);if(!g.expansion.claimed)g.expansion.tryClaim();this.hydrated=true;this.backgroundAt=null;this.save();return true}
 update(dt){if(!this.hydrated||document.hidden)return;this.timer+=dt;if(this.timer>12){this.timer=0;this.save()}}
 reset(){localStorage.removeItem(this.key);location.reload()}
};
