Settlement.FarmSystem=class{
 constructor(game){this.game=game;this.plots=new Map}
 normalize(building){let p=this.plots.get(building.id);if(!p){p={crop:null,progress:0,state:"empty",tended:false,fertility:100,plantedSeason:null};this.plots.set(building.id,p)}if(p.fertility==null)p.fertility=100;if(p.tended==null)p.tended=false;if(p.plantedSeason==null)p.plantedSeason=null;if(!p.state)p.state=p.crop?"growing":"empty";return p}
 availableCrops(){return Object.values(Settlement.CropDefs).filter(c=>(c.unlockTownLevel||1)<=this.game.xp.level)}
 plant(building,cropId="wheat"){if(!building||!building.complete||building.type!=="farm")return false;let p=this.normalize(building);if(p.state!=="empty"){this.game.bus.emit("toast","This field is already in use.");return false}let crop=Settlement.CropDefs[cropId];if(!crop)return false;if((crop.unlockTownLevel||1)>this.game.xp.level){this.game.bus.emit("toast",crop.name+" unlocks at Town Level "+crop.unlockTownLevel+".");return false}if(!this.game.resources.spend(crop.plantCost)){this.game.bus.emit("toast","Not enough supplies to plant "+crop.name+".");return false}p.crop=cropId;p.progress=0;p.state="growing";p.tended=false;p.plantedSeason=this.game.clock.season;this.game.bus.emit("toast",crop.icon+" "+crop.name+" planted.");this.game.bus.emit("farm:changed",{building,plot:p});return true}
 tend(building){if(!building||building.type!=="farm")return false;let p=this.normalize(building);if(p.state!=="growing")return false;if(p.tended){this.game.bus.emit("toast","This crop has already been tended.");return false}if(p.progress<.15){this.game.bus.emit("toast","Let the crop establish before tending it.");return false}p.tended=true;this.game.xp.add(3);this.game.effects.float(building.x,building.y,"Tended +3 XP");this.game.bus.emit("toast","🌿 Crop tended — harvest yield improved.");this.game.bus.emit("farm:changed",{building,plot:p});return true}
 growthMultiplier(crop){let season=this.game.clock.season;if(crop.preferredSeason===season)return 1.15;if(season==="Winter")return .72;return .92}
 update(dt){let daySeconds=Settlement.Config.DAY_SECONDS;for(const[id,p]of this.plots){if(p.fertility==null)p.fertility=100;if(p.state==="empty"){p.fertility=Math.min(100,p.fertility+dt/daySeconds*5);continue}if(p.state!=="growing")continue;let crop=Settlement.CropDefs[p.crop];if(!crop)continue;p.progress+=dt/(daySeconds*crop.growDays)*this.growthMultiplier(crop);if(p.progress>=1){p.progress=1;p.state="ready";this.game.bus.emit("toast",crop.icon+" "+crop.name+" is ready to harvest!");this.game.bus.emit("farm:changed",{id,plot:p})}}}
 harvest(building){if(!building||building.type!=="farm")return false;let p=this.normalize(building);if(p.state!=="ready")return false;let c=Settlement.CropDefs[p.crop];if(!c)return false;let fertilityFactor=.65+(Math.max(0,Math.min(100,p.fertility))/100)*.35,tendingFactor=p.tended?1.20:1,seasonFactor=c.preferredSeason===p.plantedSeason?1.10:1,amount=Math.max(1,Math.round(c.yield*fertilityFactor*tendingFactor*seasonFactor)),gain={[c.id]:amount},food=Math.round(amount*(c.foodValue||0));if(food>0)gain.food=food;this.game.resources.add(gain);this.game.stats.harvests++;this.game.xp.add(c.xpReward||12);p.fertility=Math.max(20,p.fertility-(c.fertilityCost||8));p.crop=null;p.state="empty";p.progress=0;p.tended=false;p.plantedSeason=null;this.game.effects.float(building.x,building.y,"+"+amount+" "+c.icon+(food>0?"  +"+food+" 🍲":""));this.game.bus.emit("farm:harvest",{building,crop:c,amount,food});this.game.bus.emit("farm:changed",{building,plot:p});return true}
};
