Settlement.FrontierWarfareSystem=Settlement.FrontierWarfareSystem||class{
 constructor(game){this.game=game;this.tick=.1;this.casualtyTick=2;this.casualtyRaids=new Set;this.trapCool=new Map;this.alert=false;if(!game.stats.frontierZones)game.stats.frontierZones=[];game.bus.on("raid:started",r=>this.onRaid(r));game.bus.on("boss:defeated",()=>{game.stats.bossesDefeated=(game.stats.bossesDefeated||0)+1});game.bus.on("enemy:defeated",()=>this.refreshAlert())}
 zones(){return this.game.stats.frontierZones||[]}
 addZone(mode="HOLD"){let T=Settlement.Config.TILE,x=Math.floor(this.game.camera.x/T),y=Math.floor(this.game.camera.y/T),z={id:Date.now()+Math.floor(Math.random()*999),mode,x,y,radius:4};this.zones().push(z);this.game.guards?.routes?.clear?.();this.game.bus.emit("toast",`🛡️ ${mode} zone established.`);return z}
 removeZone(id){let a=this.zones(),i=a.findIndex(z=>z.id===Number(id));if(i<0)return false;a.splice(i,1);this.game.guards?.routes?.clear?.();this.game.bus.emit("toast","Defense zone removed.");return true}
 guardPoints(){let out=[];for(const z of this.zones()){let r=z.radius||4;if(z.mode==="HOLD"){let q=Math.max(1,Math.floor(r/2));out.push({x:z.x,y:z.y,zone:z.mode},{x:z.x+q,y:z.y,zone:z.mode},{x:z.x-q,y:z.y,zone:z.mode},{x:z.x,y:z.y+q,zone:z.mode},{x:z.x,y:z.y-q,zone:z.mode})}else if(z.mode==="PROTECT"){out.push({x:z.x,y:z.y,zone:z.mode},{x:z.x+1,y:z.y,zone:z.mode},{x:z.x-1,y:z.y,zone:z.mode},{x:z.x,y:z.y+1,zone:z.mode},{x:z.x,y:z.y-1,zone:z.mode})}else{out.push({x:z.x+r,y:z.y,zone:z.mode},{x:z.x,y:z.y+r,zone:z.mode},{x:z.x-r,y:z.y,zone:z.mode},{x:z.x,y:z.y-r,zone:z.mode},{x:z.x+r,y:z.y+r,zone:z.mode},{x:z.x-r,y:z.y-r,zone:z.mode})}}return out.filter(p=>this.game.grid.inBounds(p.x,p.y)&&this.game.expansion.isClaimed(p.x,p.y))}
 onRaid(r){this.alert=true;this.game.stats.raidsSeen=(this.game.stats.raidsSeen||0)+1;this.shelterFreeCitizens();if(r?.boss)this.game.stats.bossEncounters=(this.game.stats.bossEncounters||0)+1}
 refreshAlert(){this.alert=this.game.enemies.list.some(e=>!e.dead)}
 shelterFreeCitizens(){for(const c of this.game.citizens.list){if(c.job==="Guard"||c.job==="Archer")continue;let s=String(c.state||"").toUpperCase();if(!["WANDERING","SOCIALIZING","IDLE","LEISURE"].includes(s)||!c.home)continue;c.state="TRAVEL_HOME";c.frontierShelter=true;c.path=[];c.pathIndex=0;this.game.amenities?.releaseCitizen?.(c.id)}}
 enemySpeedMultiplier(e){let m=1;for(const b of this.game.buildings.list){let d=Settlement.BuildingDefs[b.type];if(!b.complete||!d?.defenseSlow)continue;let x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64;if(Math.hypot(e.x-x,e.y-y)<=(d.slowRadius||1.25)*64)m=Math.min(m,d.slowFactor||.6)}return m}
 updateTraps(dt){for(const[id,v]of this.trapCool)this.trapCool.set(id,Math.max(0,v-dt));for(const b of this.game.buildings.list){let d=Settlement.BuildingDefs[b.type];if(!b.complete||!d?.defenseTrap||(this.trapCool.get(b.id)||0)>0)continue;let x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64,e=this.game.enemies.list.find(e=>!e.dead&&Math.hypot(e.x-x,e.y-y)<42);if(!e)continue;e.hp-=d.trapDamage||10;this.game.effects.float(e.x/64,e.y/64,`SPIKES -${d.trapDamage||10}`);this.game.bus.emit("defense:trap",{building:b,target:e});this.trapCool.set(b.id,d.trapCooldown||2.5);if(e.hp<=0)this.game.enemies.kill(e)}}
 blockedBetween(ax,ay,bx,by){let dist=Math.hypot(bx-ax,by-ay),steps=Math.max(1,Math.ceil(dist/24));for(let i=1;i<steps;i++){let t=i/steps;if(this.game.walls?.blocksWorld(ax+(bx-ax)*t,ay+(by-ay)*t))return true}return false}
 updateCasualties(dt){this.casualtyTick-=dt;if(this.casualtyTick>0)return;this.casualtyTick=2;for(const e of this.game.enemies.list){if(e.dead||e.type!=="siegeRam"||this.casualtyRaids.has(e.raidId))continue;let c=this.game.citizens.list.filter(c=>String(c.state||"").toUpperCase()!=="SLEEPING").sort((a,b)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(b.x-e.x,b.y-e.y))[0];if(!c||Math.hypot(c.x-e.x,c.y-e.y)>70||this.blockedBetween(e.x,e.y,c.x,c.y)||Math.random()>=.025)continue;this.casualtyRaids.add(e.raidId);this.game.citizens.fall(c);this.game.bus.emit("toast",`🕯️ ${c.name} fell during the siege. Their name has been entered in the memorial book.`);break}}
 update(dt){if(document.hidden)return;this.tick-=dt;if(this.tick>0)return;let step=.15;this.tick=step;this.updateTraps(step);this.updateCasualties(step);this.refreshAlert();if(!this.alert)for(const c of this.game.citizens.list)if(c.frontierShelter)delete c.frontierShelter}
 summary(){return{alert:this.alert,raids:this.game.stats.raidsSeen||0,bosses:this.game.stats.bossesDefeated||0,zones:this.zones().length}}
};

Settlement.Game=class{
 constructor(canvas,uiroot){this.canvas=canvas;this.bus=new Settlement.EventBus;this.stats={harvests:0,flourProduced:0,breadProduced:0};this.quality=new Settlement.QualityManager(this);this.grid=new Settlement.Grid;this.camera=new Settlement.Camera(canvas);this.chunks=new Settlement.ChunkManager(this);this.expansion=new Settlement.ExpansionManager(this);this.buildings=new Settlement.BuildingManager(this);this.resources=new Settlement.ResourceManager(this);this.pathfinding=new Settlement.PathfindingSystem(this);this.roads=new Settlement.RoadSystem(this);this.citizens=new Settlement.CitizenManager(this);this.housing=new Settlement.HousingSystem(this);this.immigration=new Settlement.ImmigrationSystem(this);this.farms=new Settlement.FarmSystem(this);this.production=new Settlement.ProductionSystem(this);this.passiveProduction=new Settlement.PassiveProductionSystem(this);this.commerce=new Settlement.CommerceSystem(this);this.unlocks=new Settlement.UnlockSystem(this);this.xp=new Settlement.XPSystem(this);this.quests=new Settlement.QuestSystem(this);this.clock=new Settlement.Clock(this);this.effects=new Settlement.Effects(this);this.audio=new Settlement.AudioManager(this);this.juice=new Settlement.JuiceSystem(this);this.walls=new Settlement.WallSystem(this);this.towers=new Settlement.TowerSystem(this);this.enemies=new Settlement.EnemyDirector(this);this.security=new Settlement.SecuritySystem(this);this.guards=new Settlement.GuardSystem(this);this.frontier=new Settlement.FrontierWarfareSystem(this);this.legends=new Settlement.LegendsSystem(this);this.beauty=new Settlement.BeautySystem(this);this.happiness=new Settlement.HappinessSystem(this);this.livingTown=new Settlement.LivingTownSystem(this);this.gothicWorld=new Settlement.GothicWorldSystem(this);this.placement=new Settlement.PlacementSystem(this);this.construction=new Settlement.ConstructionSystem(this);this.upgrades=new Settlement.UpgradeSystem(this);this.renderer=new Settlement.Renderer(this,canvas);this.ui=new Settlement.UIManager(this,uiroot);this.placementUI=new Settlement.PlacementUI(this,uiroot);this.celebrations=new Settlement.CelebrationSystem(this);this.input=new Settlement.InputManager(this,canvas);this.save=new Settlement.SaveManager(this);this.last=performance.now();this.fps=60;this.running=true;addEventListener("resize",()=>this.renderer.resize());document.addEventListener("visibilitychange",()=>{if(document.hidden)this.save.save()});this.loop()}
 update(dt){this.camera.update(dt);this.chunks.update();this.expansion.update(dt);this.construction.update(dt);this.housing.update(dt);this.upgrades.update(dt);this.immigration.update(dt);this.farms.update(dt);this.production.update(dt);this.passiveProduction.update(dt);this.commerce.update(dt);this.citizens.update(dt);this.enemies.update(dt);this.frontier.update(dt);this.guards.update(dt);this.towers.update(dt);this.clock.update(dt);this.effects.update(dt);this.juice.update(dt);this.legends.update(dt);this.happiness.update(dt);this.quests.update();this.save.update(dt);this.quality.update(dt,this.fps);this.ui.updateDebug()}
 loop(){let now=performance.now(),dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.fps=this.fps*.92+(1/Math.max(.001,dt))*.08;try{this.update(dt);this.renderer.draw()}catch(e){if(!this.loopErrorAt||now-this.loopErrorAt>1000){this.loopErrorAt=now;console.error("Game loop error (frame skipped):",e)}}finally{requestAnimationFrame(()=>this.loop())}}
};
