/* Optional GPU presentation over the authoritative Canvas2D world. */
import * as THREE from "../../vendor/three/three.module.min.js";
const KEY="theSettlement.settings.v1",T=64,CAPS={LOW:[180,40,10,1],MEDIUM:[340,80,18,1.25],HIGH:[560,140,28,1.5],ULTRA:[760,200,38,1.5]};
const CHIMNEY=new Set(["cottage","bakery","blacksmith","smelter","mason","hall","tavern"]),WATER=new Set(["pond","villagePond","fountain","grandFarmstead"]),FIRE=new Set(["brazier","firePit","blacksmith","smelter"]);
class Pool{constructor(n){this.a=Array.from({length:n},()=>({on:false}));this.i=0}get(v){for(let n=0;n<this.a.length;n++){let i=(this.i+n)%this.a.length,p=this.a[i];if(!p.on){this.i=(i+1)%this.a.length;Object.assign(p,v,{on:true});return p}}}clear(){this.a.forEach(p=>p.on=false)}}
function texture(streak=false){let c=document.createElement("canvas"),x=c.getContext("2d");c.width=c.height=64;if(streak){x.strokeStyle="#fff";x.lineWidth=3;x.beginPath();x.moveTo(43,3);x.lineTo(21,61);x.stroke()}else{let g=x.createRadialGradient(32,32,0,32,32,31);g.addColorStop(0,"#fff");g.addColorStop(.4,"#ffffffaa");g.addColorStop(1,"#ffffff00");x.fillStyle=g;x.fillRect(0,0,64,64)}return new THREE.CanvasTexture(c)}
class Batch{constructor(scene,n,map,blend=THREE.NormalBlending){this.n=n;this.p=new Float32Array(n*3);this.c=new Float32Array(n*3);this.s=new Float32Array(n);this.g=new THREE.BufferGeometry;this.g.setAttribute("position",new THREE.BufferAttribute(this.p,3));this.g.setAttribute("color",new THREE.BufferAttribute(this.c,3));this.g.setAttribute("size",new THREE.BufferAttribute(this.s,1));this.m=new THREE.ShaderMaterial({transparent:true,depthTest:false,depthWrite:false,blending:blend,uniforms:{map:{value:map}},vertexShader:"attribute float size;varying vec3 v;void main(){v=color;gl_PointSize=size;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}",fragmentShader:"uniform sampler2D map;varying vec3 v;void main(){vec4 t=texture2D(map,gl_PointCoord);gl_FragColor=vec4(v,t.a);}"});this.o=new THREE.Points(this.g,this.m);this.o.frustumCulled=false;scene.add(this.o)}update(a,screen){let n=0,col=new THREE.Color;for(const q of a){if(!q.on||n>=this.n)continue;let p=q.screen?q:screen(q.x,q.y);this.p[n*3]=p.x;this.p[n*3+1]=p.y;col.set(q.color||0xffffff);this.c[n*3]=col.r;this.c[n*3+1]=col.g;this.c[n*3+2]=col.b;this.s[n]=q.size||5;n++}this.g.setDrawRange(0,n);Object.values(this.g.attributes).forEach(x=>x.needsUpdate=true)}dispose(){this.g.dispose();this.m.dispose()}}
export class Three2DEffectsManager{
 constructor(game){this.game=game;this.last=performance.now();this.scan=0;this.weather="clear";this.dead=false}
 init(){if(Settlement.renderer3dEnabled)throw Error("Canvas2D view inactive");let shell=document.querySelector("#game-shell"),ui=document.querySelector("#ui-root");if(!shell||!ui)throw Error("render layers unavailable");this.canvas=document.createElement("canvas");this.canvas.id="three2d-effects";this.canvas.setAttribute("aria-hidden","true");shell.insertBefore(this.canvas,ui);this.r=new THREE.WebGLRenderer({canvas:this.canvas,alpha:true,antialias:false,powerPreference:"low-power"});this.r.setClearColor(0,0);this.scene=new THREE.Scene;this.cam=new THREE.OrthographicCamera(0,1,0,1,-2,2);this.tex=[texture(true),texture()];this.quality();this.build();this.resize();this.seed();this.events();this.on=true;this.loop();return true}
 quality(){let q=CAPS[this.game.quality?.tier]||CAPS.MEDIUM;[this.wcap,this.pcap,this.gcap,this.dpr]=q;this.r?.setPixelRatio(Math.min(devicePixelRatio||1,this.dpr))}
 build(){this.wp=new Pool(this.wcap);this.pp=new Pool(this.pcap);this.gp=new Pool(this.gcap);this.wb=new Batch(this.scene,this.wcap,this.tex[0]);this.pb=new Batch(this.scene,this.pcap,this.tex[1]);this.gb=new Batch(this.scene,this.gcap,this.tex[1],THREE.AdditiveBlending)}
 events(){this._resize=()=>this.resize();addEventListener("resize",this._resize,{passive:true});this.canvas.addEventListener("webglcontextlost",e=>{e.preventDefault();this.disable("context lost")});this.game.bus.on("tower:fired",e=>this.combat(e));this.game.bus.on("raid:started",e=>{if(e?.boss&&e.captain)this.burst("boss",e.captain.x,e.captain.y,12)});this.game.bus.on("quality:changed",()=>this.rebuild())}
 rebuild(){this.wb.dispose();this.pb.dispose();this.gb.dispose();this.quality();this.build();this.seed();this.resize()}
 resize(){let w=this.canvas.clientWidth||innerWidth,h=this.canvas.clientHeight||innerHeight;this.r.setSize(w,h,false);this.cam.left=0;this.cam.right=w;this.cam.top=0;this.cam.bottom=h;this.cam.updateProjectionMatrix()}
 screen=(x,y)=>{let c=this.game.camera,z=c.zoom||1;return{x:(x-c.x)*z+innerWidth/2,y:(y-c.y)*z+innerHeight/2}}
 visible(x,y,m=140){let p=this.screen(x,y);return p.x>-m&&p.y>-m&&p.x<innerWidth+m&&p.y<innerHeight+m}
 state(){let g=this.game,d=Math.max(1,Math.floor(g.clock?.day||1)),s=g.clock?.seasonIndex||0,b=Math.floor(((g.clock?.t||0)/(Settlement.Config.DAY_SECONDS||300))*2),n=((d*37+s*71+b*19)%100+100)%100;if(s===3)return n<48?"snow":n<68?"fog":"clear";if(s===0)return n<42?"rain":n<62?"fog":"clear";return n<(s===1?22:34)?"rain":n<(s===1?36:55)?"fog":"clear"}
 seed(){this.wp.clear();for(let i=0;i<this.wcap;i++)this.wp.get({screen:true,x:Math.random()*innerWidth,y:Math.random()*innerHeight,layer:i%3})}
 weatherStep(dt,now){let type=this.game.quality?.get("weather")===false?"clear":this.state();if(type!==this.weather){this.weather=type;this.seed()}let ratio=type==="clear"?0:type==="fog"?.16:type==="snow"?.72:1;for(let i=0;i<this.wp.a.length;i++){let p=this.wp.a[i];p.on=i<this.wcap*ratio;if(!p.on)continue;let z=[.45,.7,1][p.layer];if(type==="rain"){p.vx=4*z;p.vy=(310+p.layer*155)*z;p.size=11+p.layer*10;p.color=0xa9cad8}else if(type==="snow"){p.vx=(Math.sin(now*.0007+i)*18+3)*z;p.vy=(22+p.layer*20)*z;p.size=4+p.layer*4;p.color=0xf5f1e5}else{p.vx=(7+p.layer*5)*z;p.vy=Math.sin(now*.0003+i)*2;p.size=70+p.layer*70;p.color=0xcdd1c8}p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.y>innerHeight+50||p.x>innerWidth+100){p.x=-Math.random()*100;p.y=-Math.random()*innerHeight*.2}}}
 burst(kind,x,y,n=1){let st={smoke:[0xb8b4aa,15],spark:[0xffc45b,6],ember:[0xff8b38,7],dust:[0xb69b72,9],water:[0x9de4ef,8],impact:[0xffd28b,8],boss:[0xb57bd7,12],leaf:[0x78894b,7]}[kind]||[0xffffff,6];for(let i=0;i<n;i++){let life=.5+Math.random()*1.2;this.pp.get({kind,x:x+Math.random()*12-6,y:y+Math.random()*8-4,vx:Math.random()*30-15+(kind==="smoke"?5:0),vy:kind==="smoke"?-15-Math.random()*20:Math.random()*32-22,life,size:st[1]+Math.random()*5,color:st[0]})}}
 emitters(now){if(now<this.scan)return;this.scan=now+(this.game.quality?.tier==="LOW"?900:500);let a=[];for(const b of this.game.buildings?.list||[]){let x=(b.x+b.w/2)*T,y=(b.y+b.h/2)*T;if(!b.complete){if(this.visible(x,y)&&Math.random()<.35)this.burst("dust",x,y);continue}if(this.visible(x,y,180))a.push([b,x,y])}a.sort((u,v)=>Math.hypot(u[1]-this.game.camera.x,u[2]-this.game.camera.y)-Math.hypot(v[1]-this.game.camera.x,v[2]-this.game.camera.y));let lim=this.game.quality?.tier==="LOW"?10:30;for(const[b,x,y]of a.slice(0,lim)){if(CHIMNEY.has(b.type)&&Math.random()<.38)this.burst("smoke",x+b.w*12,y-b.h*25);if(FIRE.has(b.type)){if(Math.random()<.5)this.burst("ember",x,y-b.h*10);this.gp.get({x,y,life:.65,size:b.type==="blacksmith"?76:54,color:0xff9b45})}if(b.type==="blacksmith"&&Math.random()<.55)this.burst("spark",x+18,y,2);if(WATER.has(b.type)&&Math.random()<.35){this.burst("water",x+Math.random()*40-20,y);this.gp.get({x,y,life:.45,size:28,color:0x88dbe5})}if(b.type==="grandFarmstead"&&Math.random()<.45)this.burst(Math.random()<.5?"dust":"leaf",x+Math.random()*b.w*T-b.w*T/2,y+Math.random()*b.h*T-b.h*T/2)}}
 combat(e){let b=e?.building,t=e?.target;if(!b||!t)return;let x=(b.x+b.w/2)*T,y=(b.y+b.h/2)*T;this.burst("spark",x,y,e.projectile==="arrow"?2:4);for(let i=1;i<=5;i++)this.pp.get({x:x+(t.x-x)*i/6,y:y+(t.y-y)*i/6,vx:0,vy:0,life:.18,size:5,color:0xf4ddb0});this.burst("impact",t.x,t.y,4)}
 particles(dt,now){this.emitters(now);for(const p of this.pp.a){if(!p.on)continue;if((p.life-=dt)<=0){p.on=false;continue}p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.kind==="spark"||p.kind==="impact")p.vy+=28*dt;if(p.kind==="smoke")p.size*=1.006}for(const p of this.gp.a)if(p.on&&(p.life-=dt)<=0)p.on=false;for(const e of this.game.enemies?.list||[])if(Settlement.EnemyDefs?.[e.type]?.boss&&this.visible(e.x,e.y)){this.gp.get({x:e.x,y:e.y,life:.08,size:66+Math.sin(now*.005)*8,color:0x8d4fa5});if(Math.random()<.08)this.burst("boss",e.x,e.y)}}
 loop=()=>{if(!this.on||this.dead)return;this.raf=requestAnimationFrame(this.loop);if(document.hidden||Settlement.renderer3dEnabled)return;let now=performance.now(),dt=Math.min(.05,(now-this.last)/1000);this.last=now;try{this.weatherStep(dt,now);this.particles(dt,now);this.wb.update(this.wp.a,this.screen);this.pb.update(this.pp.a,this.screen);this.gb.update(this.gp.a,this.screen);this.r.render(this.scene,this.cam)}catch(e){console.warn("2D+ frame failed; Canvas2D continues",e);this.disable("render failure")}}
 disable(reason="disabled"){this.on=false;cancelAnimationFrame(this.raf);this.canvas?.remove();console.info("Three.js 2D+ effects off: "+reason)}
 dispose(){this.dead=true;this.disable();removeEventListener("resize",this._resize);this.wb?.dispose();this.pb?.dispose();this.gb?.dispose();this.tex?.forEach(t=>t.dispose());this.r?.dispose()}
}
function pref(){try{return JSON.parse(localStorage.getItem(KEY)||"{}").effects2dplus!==false}catch(e){return true}}function save(on){try{let s=JSON.parse(localStorage.getItem(KEY)||"{}");s.effects2dplus=!!on;localStorage.setItem(KEY,JSON.stringify(s))}catch(e){}}
async function ready(){for(let i=0;i<400;i++){if(window.game)return game;await new Promise(r=>setTimeout(r,25))}}
async function start(){try{let g=await ready(),settings={};try{settings=JSON.parse(localStorage.getItem(KEY)||"{}")}catch(e){}if(!g||settings.renderer3d===true||Settlement.renderer3dEnabled||!pref())return;let fx=new Three2DEffectsManager(g);fx.init();Settlement.three2dEffects=fx;console.info("Optional Three.js 2D+ presentation active")}catch(e){Settlement.three2dEffects=null;console.warn("Optional Three.js 2D+ unavailable; Canvas2D continues",e)}}
Settlement.three2dEffectsEnabled=pref();Settlement.setThree2DEffects=on=>{save(on);Settlement.three2dEffectsEnabled=!!on;if(on&&!Settlement.three2dEffects)start();else if(!on){Settlement.three2dEffects?.dispose();Settlement.three2dEffects=null}};if(pref())start();
