/* Canvas2D decoration over the proven renderer; never changes world geometry. */
(()=>{const E=Settlement.CivilizationEras,P=Settlement.MedievalWorldArt?.prototype;if(!E||!P)return;const base=P.drawBuilding;
P.era= function(){return E.current(this.game)};
P.eraRoad=function(b){let c=this.ctx,e=this.era(),n=this.neighbors(b,'road'),T=this.T,x=b.x*T,y=b.y*T,cx=x+T/2,cy=y+T/2,th=e.number<3?26:30;c.fillStyle='#61734a55';c.fillRect(x,y,T,T);c.fillStyle=e.p.road;c.beginPath();c.rect(cx-th/2,cy-th/2,th,th);if(n.l)c.rect(x,cy-th/2,T/2,th);if(n.r)c.rect(cx,cy-th/2,T/2,th);if(n.u)c.rect(cx-th/2,y,th,T/2);if(n.d)c.rect(cx-th/2,cy,th,T/2);c.fill();if(e.number>=3){c.strokeStyle=e.p.edge;c.lineWidth=e.number>=5?3:2;for(const px of [cx-th/2,cx+th/2]){c.beginPath();c.moveTo(px,cy-th/2);c.lineTo(px,cy+th/2);c.stroke()}}if(e.number>=5){c.fillStyle='#d1c9b344';for(let i=0;i<4;i++)c.fillRect(cx-th/2+3+i*7,cy-2,5,4)}};
P.eraWall=function(b){let c=this.ctx,e=this.era(),T=this.T,x=b.x*T,y=b.y*T,n=this.neighbors(b,'wall','gate'),h=n.l||n.r;if(e.number<3){this.wall(b,x,y,T,T);return}c.fillStyle=e.p.stone;if(h)c.fillRect(x,y+18,T,30);else c.fillRect(x+17,y,30,T);c.fillStyle='#4a494b';for(let i=0;i<4;i++)if(h)c.fillRect(x+i*18,y+12,12,9);else c.fillRect(x+11,y+i*18,9,12);if(e.number>=5){c.fillStyle=e.p.accent;c.fillRect(h?x+27:x+38,h?y+22:y+27,6,16)}};
P.eraGate=function(b){let c=this.ctx,e=this.era(),T=this.T,x=b.x*T,y=b.y*T;if(e.number<3){this.gate(x,y,T,T);return}c.fillStyle=e.p.stone;c.fillRect(x+2,y+7,18,T-8);c.fillRect(x+T-20,y+7,18,T-8);c.fillRect(x+2,y+7,T-4,15);c.fillStyle='#443125';c.beginPath();c.arc(x+T/2,y+T*.62,T*.22,Math.PI,0);c.lineTo(x+T*.72,y+T);c.lineTo(x+T*.28,y+T);c.fill();c.fillStyle=e.p.metal;for(let i=0;i<4;i++)c.fillRect(x+T*.3+i*7,y+T*.58,3,T*.38);if(e.number>=5){c.fillStyle=e.p.roof;for(const px of [x+2,x+T-20]){c.beginPath();c.moveTo(px-3,y+9);c.lineTo(px+9,y-5);c.lineTo(px+21,y+9);c.fill()}}};
P.eraFarm=function(b){let c=this.ctx,e=this.era(),T=this.T,x=b.x*T,y=b.y*T,w=b.w*T,h=b.h*T;if(e.number<2)return;c.save();c.strokeStyle=e.number<4?e.p.metal:e.p.stone;c.lineWidth=e.number>=5?4:2;c.strokeRect(x+5,y+7,w-10,h-12);if(e.number>=3){c.fillStyle=e.p.edge;for(let i=0;i<4;i++)c.fillRect(x+12+i*(w-24)/3,y+10,3,h-20)}if(e.number>=6){c.fillStyle=e.p.accent;c.fillRect(x+w-18,y+8,5,18)}c.restore()};
P.eraDetails=function(b){let c=this.ctx,e=this.era(),t=E.tierNumber(b.level||1),T=this.T,x=b.x*T,y=b.y*T,w=b.w*T,h=b.h*T,q=this.game.quality?.get('decor')??1;c.save();if(e.number>=2){c.strokeStyle=e.p.metal;c.lineWidth=2;c.strokeRect(x+7,y+h*.36,w-14,h*.45)}if(e.number>=3&&t>=2){c.fillStyle=e.p.stone;c.fillRect(x+7,y+h*.75,w-14,7)}if(e.number>=4&&t>=3){c.fillStyle=e.p.roof;c.beginPath();c.moveTo(x+4,y+h*.34);c.lineTo(x+w/2,y+3);c.lineTo(x+w-4,y+h*.34);c.fill()}if(e.number>=5&&t>=3){c.fillStyle=e.p.accent;c.fillRect(x+w*.72,y+h*.2,5,20);c.beginPath();c.moveTo(x+w*.77,y+h*.2);c.lineTo(x+w*.88,y+h*.25);c.lineTo(x+w*.77,y+h*.3);c.fill()}if(e.number>=6&&t>=4&&q>.5){c.strokeStyle=e.p.metal;c.lineWidth=2;c.strokeRect(x+3,y+3,w-6,h-6)}c.restore()};
P.eraHall=function(b){let c=this.ctx,e=this.era(),T=this.T,x=b.x*T,y=b.y*T,w=b.w*T,h=b.h*T,q=this.game.quality?.get('decor')??1;c.save();if(e.number>=2){c.fillStyle=e.p.stone;c.fillRect(x+w*.1,y+h*.7,w*.8,h*.14)}if(e.number>=3){for(const px of [x+w*.08,x+w*.77])c.fillRect(px,y+h*.35,w*.15,h*.42)}if(e.number>=4){c.fillStyle=e.p.roof;for(const px of [x+w*.08,x+w*.77]){c.beginPath();c.moveTo(px-5,y+h*.36);c.lineTo(px+w*.075,y+h*.17);c.lineTo(px+w*.15+5,y+h*.36);c.fill()}}if(e.number>=5){c.fillStyle=e.p.roof;c.beginPath();c.moveTo(x+w*.42,y+h*.27);c.lineTo(x+w*.5,y+h*.04);c.lineTo(x+w*.58,y+h*.27);c.fill();c.strokeStyle=e.p.edge;c.lineWidth=4;for(const px of [x+w*.155,x+w*.845]){c.beginPath();c.moveTo(px,y+h*.42);c.lineTo(px,y+h*.76);c.stroke()}}if(e.number>=6&&q>.5){c.fillStyle=e.p.metal;for(const px of [x+w*.18,x+w*.5,x+w*.82]){c.beginPath();c.arc(px,y+h*.76,5,0,7);c.fill()}}if(e.number>=7){c.strokeStyle=e.p.metal;c.lineWidth=3;c.beginPath();c.moveTo(x+w*.5,y+h*.05);c.lineTo(x+w*.5,y-2);c.stroke();c.fillStyle=e.p.accent;c.beginPath();c.moveTo(x+w*.5,y-2);c.lineTo(x+w*.62,y+5);c.lineTo(x+w*.5,y+11);c.fill()}c.restore()};
P.drawBuilding=function(b,a=1){if(b.type==='road'||b.type==='wall'||b.type==='gate'){this.ctx.save();this.ctx.globalAlpha=a;this[b.type==='road'?'eraRoad':b.type==='wall'?'eraWall':'eraGate'](b);this.ctx.restore();return}base.call(this,b,a);this.ctx.save();this.ctx.globalAlpha=a;if(b.type==='mainHall')this.eraHall(b);else if(b.type==='farm')this.eraFarm(b);else this.eraDetails(b);this.ctx.restore()};})();
