Settlement.JuiceSystem=class{
 constructor(game){this.game=game;this.particles=[];this.ambient=[];this.bubbles=[];this.time=0;this.wind=0;this.maxParticles=140;this.maxAmbient=14;this.reduced=matchMedia?.("(prefers-reduced-motion: reduce)")?.matches||false;this.bind()}
 bind(){let b=this.game.bus;b.on("building:complete",x=>this.burstBuilding(x));b.on("placement:confirmed",e=>this.placementConfirmed(e));b.on("placement:cancelled",()=>this.game.audio?.play("tap"));b.on("farm:harvest",e=>this.harvest(e));b.on("farm:changed",e=>this.farmChanged(e));b.on("production:complete",e=>this.production(e));b.on("passive:produced",e=>this.passiveProduction(e));b.on("enemy:spotted",e=>this.alert(e));b.on("enemy:defeated",e=>this.defeat(e));b.on("territory:claimed",()=>this.celebrate("NEW TERRITORY CLAIMED","🏰"));b.on("town:levelup",e=>this.celebrate("TOWN LEVEL "+e.level,"✨"));b.on("quest:complete",e=>this.celebrate("QUEST COMPLETE","📜"));b.on("citizen:arrived",e=>{this.celebrate("NEW SETTLER — "+e.name,"🏡");this.say(e,"Home at last.")})}
 placementConfirmed(e){let b=e?.building;if(!b)return;let x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64;this.emit("dust",x,y,8);this.emit("spark",x,y,3);for(const[k,v]of Object.entries(e.cost||{}))this.game.effects.float(b.x,b.y,"-"+v+" "+(Settlement.ResourceDefs[k]?.icon||k));this.game.audio?.play("complete");let nearby=this.game.citizens.list.find(c=>Math.hypot(c.x-x,c.y-y)<260);if(nearby&&Math.random()<.55)this.say(nearby,["A new building!","More work!","That will help."][Math.floor(Math.random()*3)])}
 emit(kind,x,y,n=5){if(this.reduced)n=Math.ceil(n*.4);for(let i=0;i<n&&this.particles.length<this.maxParticles;i++){let a=Math.random()*Math.PI*2,s=8+Math.random()*24,life=.55+Math.random()*.8;this.particles.push({kind,x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-(kind==="smoke"?18:4),life,max:life,size:2+Math.random()*4})}}
 burstBuilding(b){let x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64;this.emit("dust",x,y,10);this.emit("spark",x,y,6);this.game.audio?.play("complete")}
 farmChanged(e){if(!e?.building)return;let x=(e.building.x+1)*64,y=(e.building.y+1)*64;this.emit(e.plot?.tended?"leaf":"dust",x,y,5);this.game.audio?.play(e.plot?.tended?"tend":"plant")}
 harvest(e){let x=(e.building.x+1)*64,y=(e.building.y+1)*64;this.emit("leaf",x,y,12);this.game.audio?.play("harvest")}
 production(e){if(!e?.building)return;let b=e.building,x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64;this.emit(b.type==="quarry"||b.type==="mason"?"stone":"dust",x,y,7);this.game.audio?.play(b.type==="quarry"||b.type==="mason"?"stone":"produce")}
 passiveProduction(e){if(!e?.building||!e.amount)return;let b=e.building,x=(b.x+b.w/2)*64,y=(b.y+b.h/2)*64,kind=b.type==="quarry"?"stone":"dust";this.emit(kind,x,y,5);this.game.effects.float(b.x,b.y,"+"+e.amount+" "+(Settlement.ResourceDefs[e.resource]?.icon||e.resource));this.game.audio?.play(b.type==="quarry"?"stone":"produce")}
 alert(){this.game.audio?.play("alert")}
 defeat(e){if(e)this.emit("dust",e.x,e.y,7)}
 celebrate(text,icon){this.game.bus.emit("celebration",{text,icon});this.game.audio?.play("celebrate")}
 say(c,text){if(!c||this.bubbles.length>=4)return;this.bubbles.push({citizen:c,text,t:2.4})}
 contextualSpeech(){let visible=this.game.citizens.list.filter(c=>c.state!=="SLEEPING");if(!visible.length||this.bubbles.length>=3)return;let c=visible[Math.floor(Math.random()*visible.length)],h=this.game.clock.t/Settlement.Config.DAY_SECONDS*24,msg=c.job==="Baker"?"Fresh bread!":c.job==="Stonecutter"?"Stone for the town.":c.job==="Stonemason"?"Good stonework.":h<9?"Morning!":h>18?"Home at last.":c.state==="WORKING"?"Work begins.":"Beautiful day.";this.say(c,msg)}
 ambientSpawn(){if(this.ambient.length>=this.maxAmbient)return;let cam=this.game.camera,kind=Math.random()<.65?"bird":"butterfly",life=kind==="bird"?8:5;this.ambient.push({kind,x:cam.x-420+Math.random()*100,y:cam.y-260+Math.random()*520,vx:kind==="bird"?55+Math.random()*30:8+Math.random()*10,vy:kind==="bird"?(Math.random()-.5)*8:0,life,phase:Math.random()*6})}
 buildingAmbience(dt){for(let b of this.game.buildings.list){if(!b.complete)continue;let d=Settlement.BuildingDefs[b.type],active=d.recipe?this.game.production?.normalize(b)?.active:d.production?(b.workers||0)>0:true;if(!active)continue;if((b.type==="bakery"||b.type==="cottage")&&Math.random()<dt*.45)this.emit("smoke",(b.x+b.w*.72)*64,b.y*64+12,1);if((b.type==="quarry"||b.type==="mason")&&Math.random()<dt*.35)this.emit("stone",(b.x+b.w/2)*64,(b.y+b.h*.65)*64,1);if(b.type==="mill"&&Math.random()<dt*.18)this.emit("dust",(b.x+b.w/2)*64,(b.y+b.h*.65)*64,1)}}
 update(dt){this.time+=dt;this.wind=Math.sin(this.time*.32);for(let p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.kind==="smoke"){p.vx+=this.wind*dt*5;p.vy-=dt*2}}this.particles=this.particles.filter(p=>p.life>0);for(let a of this.ambient){a.life-=dt;a.phase+=dt*4;a.x+=a.vx*dt;a.y+=a.vy*dt+(a.kind==="butterfly"?Math.sin(a.phase)*10*dt:0)}this.ambient=this.ambient.filter(a=>a.life>0);for(let b of this.bubbles)b.t-=dt;this.bubbles=this.bubbles.filter(b=>b.t>0);if(Math.random()<dt*.08)this.ambientSpawn();if(Math.random()<dt*.018)this.contextualSpeech();this.buildingAmbience(dt)}
};
