(()=>{
 const proto=Settlement.Renderer?.prototype;if(!proto)return;const base=proto.draw;
 proto.draw=function(){base.call(this);this.drawPlacementOverlay()};
 proto.drawPlacementOverlay=function(){let g=this.game,p=g.placement;if(!p?.type||!p.hover)return;let d=Settlement.BuildingDefs[p.type],v=p.validate(p.type,p.hover.x,p.hover.y),ctx=this.ctx,cam=g.camera,T=Settlement.Config.TILE||64,D=this.dpr||1,W=this.c.width,H=this.c.height,worldToScreen=(x,y)=>({x:(x-cam.x)*cam.zoom*D+W/2,y:(y-cam.y)*cam.zoom*D+H/2}),tile=T*cam.zoom*D,t=performance.now()/700,pulse=.78+Math.sin(t)*.08;ctx.save();ctx.globalAlpha=pulse;
  if(p.type==="archery"){let center=worldToScreen((p.hover.x+.5)*T,(p.hover.y+.5)*T),r=(d.range||5)*T*cam.zoom*D;ctx.beginPath();ctx.arc(center.x,center.y,r,0,Math.PI*2);ctx.fillStyle="#d8c66b20";ctx.fill();ctx.strokeStyle="#eadb8dbb";ctx.lineWidth=2*D;ctx.setLineDash([7*D,6*D]);ctx.stroke();ctx.setLineDash([])}
  for(let c of v.cells||[]){let s=worldToScreen(c.x*T,c.y*T);ctx.fillStyle=c.ok?"#a9df6a55":"#d95b4f66";ctx.fillRect(s.x,s.y,tile,tile);ctx.strokeStyle=c.ok?"#e5f7a5dd":"#ffb0a5ee";ctx.lineWidth=2*D;ctx.strokeRect(s.x+1,s.y+1,tile-2,tile-2);ctx.fillStyle=c.ok?"#f3ffd0":"#ffe1dc";ctx.font=`bold ${Math.max(11,14*cam.zoom)*D}px Georgia`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(c.ok?"✓":"✕",s.x+tile/2,s.y+tile/2)}
  let a=worldToScreen(p.hover.x*T,p.hover.y*T),fw=d.footprint[0]*tile,fh=d.footprint[1]*tile;ctx.globalAlpha=.62;ctx.fillStyle=v.ok?"#f2df9b99":"#d77a7399";ctx.fillRect(a.x+fw*.12,a.y+fh*.12,fw*.76,fh*.76);ctx.font=`${Math.max(24,38*cam.zoom)*D}px serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(d.icon,a.x+fw/2,a.y+fh/2);
  if(v.entrance){let e=worldToScreen((v.entrance.x+.5)*T,(v.entrance.y+.5)*T);ctx.globalAlpha=1;ctx.beginPath();ctx.arc(e.x,e.y,10*D,0,Math.PI*2);ctx.fillStyle="#f6d980";ctx.fill();ctx.strokeStyle="#4b321d";ctx.lineWidth=2*D;ctx.stroke();ctx.fillStyle="#3e2a17";ctx.font=`bold ${10*D}px Arial`;ctx.fillText("DOOR",e.x,e.y-16*D)}ctx.restore()};
})();
