/* Persistent settlement history, boss identities, relic trophies and veteran defenders.
 * Data lives inside existing stats/citizen save payloads; no SaveSchema bump.
 */
Settlement.LegendsSystem=class{
 constructor(game){
  this.game=game;let s=game.stats;
  s.chronicle=Array.isArray(s.chronicle)?s.chronicle:[];s.bossRecords=Array.isArray(s.bossRecords)?s.bossRecords:[];s.relics=Array.isArray(s.relics)?s.relics:[];s.memorials=Array.isArray(s.memorials)?s.memorials:[];s.siegesWon=s.siegesWon||0;s.citizensLost=s.citizensLost||0;s.highestPopulation=s.highestPopulation||0;s.goldRecord=s.goldRecord||0;s.greatestRaid=s.greatestRaid||0;
  this.first=["Roderic","Maraud","Ulric","Veyra","Aldren","Seraph","Corvin","Maela","Garrick","Ysabet","Osric","Thorne"],this.last=["Black-Eye","the Ashen","Crowbane","Ironhand","the Red","Grave-Walker","Wolfscar","the Hollow","Nightcloak","Stonejaw"];
  this.traits=["Armored","Swift","Berserker","Plunderer","Commander","Relentless"];
  this.relicNames=["Black Banner Sword","Wolfskin Cloak","Iron Crown","Raider's Longbow","Ashen Signet","Crowguard Buckler","Captain's War Horn","Grimsteel Dagger"];
  this.relicDefs={"Black Banner Sword":{combat:1.4,label:"+1.4 Guard damage"},"Wolfskin Cloak":{speed:1.12,label:"+12% Guard movement"},"Iron Crown":{combat:.8,label:"+0.8 Guard damage"},"Raider's Longbow":{archery:1.22,label:"+22% Archer tower damage"},"Ashen Signet":{combat:1,label:"+1 Guard damage"},"Crowguard Buckler":{combat:.6,label:"+0.6 Guard damage"},"Captain's War Horn":{combat:1.2,label:"+1.2 Guard damage"},"Grimsteel Dagger":{combat:1.3,label:"+1.3 Guard damage"}};
  game.bus.on("raid:started",r=>{let stats=this.game.stats;stats.greatestRaid=Math.max(stats.greatestRaid||0,r?.count||0);this.record(`${r?.faction||"Raiders"} sent ${r?.count||0} hostiles against the settlement${r?.boss?", led by an infamous captain":""}${r?.siege?" in a major siege":""}.`,r?.siege?"siege":"raid")});
  game.bus.on("boss:defeated",r=>this.bossDefeated(r));game.bus.on("tower:fired",r=>{if(r?.target?.hp<=0&&r.building?.type==="archery"){let c=game.citizens.list.find(x=>x.workplace===r.building.id&&x.job==="Archer");if(c)this.credit(c,"Archer")}});
  game.bus.on("territory:claimed",r=>{if(r?.building?.type==="hallOfLegends")this.record(`The Hall of Legends founded a distant stronghold and secured ${r.tiles} new tiles.`,"land")});
  game.bus.on("building:complete",b=>{if(b?.type==="hallOfLegends"){this.record("The Hall of Legends was raised as a fortified monument to the settlement's history.","hall");game.bus.emit("celebration",{icon:"👑",text:"THE HALL OF LEGENDS STANDS"})}});
  game.bus.on("citizen:fallen",c=>this.memorialize(c));
 }
 seed(e){return((e?.id||1)*97+(this.game.clock?.day||1)*31+(this.game.stats.bossEncounters||0)*13)>>>0}
 wanted(){let s=this.game.stats;if(s.wantedCaptain)return s.wantedCaptain;let n=((this.game.clock?.day||1)*53+(s.bossesDefeated||0)*29)>>>0;s.wantedCaptain={name:`${this.first[n%this.first.length]} ${this.last[Math.floor(n/5)%this.last.length]}`,trait:this.traits[Math.floor(n/9)%this.traits.length],faction:["Black Banner","Wolf Clan","Ashen Company","Hollow Men","Crimson Brotherhood"][Math.floor(n/13)%5],rewardHint:this.relicNames[Math.floor(n/17)%this.relicNames.length]};return s.wantedCaptain}
 identity(e){if(e.legendIdentity)return e.legendIdentity;let w=this.game.stats.wantedCaptain;if(w&&!w.claimed){w.claimed=true;e.faction=w.faction;return e.legendIdentity={name:w.name,trait:w.trait,faction:w.faction}}let n=this.seed(e),name=`${this.first[n%this.first.length]} ${this.last[Math.floor(n/7)%this.last.length]}`,trait=this.traits[Math.floor(n/11)%this.traits.length],factions=["Black Banner","Wolf Clan","Ashen Company","Hollow Men","Crimson Brotherhood"],faction=e.faction||factions[Math.floor(n/17)%factions.length];return e.legendIdentity={name,trait,faction}}
 record(text,type="event",extra={}){let a=this.game.stats.chronicle||(this.game.stats.chronicle=[]);a.unshift({id:Date.now()+Math.random(),day:this.game.clock?.day||1,season:this.game.clock?.season||"",type,text,...extra});if(a.length>80)a.length=80;this.game.bus.emit("legends:changed")}
 bossDefeated(r){let e=r?.enemy;if(!e)return;let id=this.identity(e),relic=this.relicNames[(this.seed(e)+3)%this.relicNames.length],def=this.relicDefs[relic]||{label:"Legendary trophy"},record={name:id.name,trait:id.trait,faction:id.faction,day:this.game.clock?.day||1,relic,loot:r.loot||[]};this.game.stats.bossRecords.unshift(record);if(this.game.stats.bossRecords.length>40)this.game.stats.bossRecords.length=40;this.game.stats.relics.unshift({id:Date.now()+Math.random(),name:relic,source:id.name,day:record.day,rarity:"Legendary",bonus:def.label,equippedTo:null});if(this.game.stats.relics.length>60)this.game.stats.relics.length=60;this.game.stats.wantedCaptain=null;this.record(`${id.name}, ${id.trait} captain of the ${id.faction}, was defeated. The ${relic} was claimed as a trophy.`,"boss",record);this.game.bus.emit("toast",`🏆 LEGENDARY TROPHY: ${relic}`);this.game.bus.emit("celebration",{icon:"🏆",text:`${id.name.toUpperCase()} DEFEATED — ${relic.toUpperCase()} CLAIMED`})}
 memorialize(c){if(!c)return;let m={name:c.name||"Unknown Citizen",job:c.job||"Citizen",day:this.game.clock?.day||1,kills:c.combatKills||0};this.game.stats.memorials.unshift(m);this.game.stats.citizensLost=(this.game.stats.citizensLost||0)+1;for(const r of this.game.stats.relics||[])if(r.equippedTo===c.id)r.equippedTo=null;this.record(`${m.name}, ${m.job}, was lost in defense of the settlement.`,"memorial",m)}
 rank(c){let xp=c.combatXP||0;return xp>=240?"Champion":xp>=110?"Elite":xp>=40?"Veteran":"Recruit"}
 credit(c,kind="Defender"){if(!c)return;c.combatKills=(c.combatKills||0)+1;c.combatXP=(c.combatXP||0)+(kind==="Archer"?9:12);let old=c.legendRank||"Recruit",now=this.rank(c);c.legendRank=now;if(now!==old){this.record(`${c.name} rose to ${now} ${kind} after surviving the frontier fighting.`,"hero",{citizenId:c.id,name:c.name,rank:now});this.game.bus.emit("toast",`⭐ ${c.name} is now a ${now}!`);this.game.bus.emit("celebration",{icon:"⭐",text:`${c.name.toUpperCase()} — ${now.toUpperCase()} ${kind.toUpperCase()}`})}}
 heroes(){return this.game.citizens.list.filter(c=>(c.combatXP||0)>=40).sort((a,b)=>(b.combatXP||0)-(a.combatXP||0)).slice(0,12)}
 relicFor(c){return c&&(this.game.stats.relics||[]).find(r=>r.equippedTo===c.id)||null}
 relicBonus(c){let r=this.relicFor(c),d=r&&this.relicDefs[r.name];return{combat:d?.combat||0,archery:d?.archery||1,speed:d?.speed||1,relic:r}}
 equipRelic(index,citizenId){let relic=(this.game.stats.relics||[])[Number(index)],c=this.game.citizens.list.find(x=>x.id===Number(citizenId));if(!relic||!c||this.rank(c)==="Recruit")return false;for(const r of this.game.stats.relics)if(r.equippedTo===c.id)r.equippedTo=null;relic.equippedTo=c.id;this.game.bus.emit("toast",`🏆 ${c.name} equipped ${relic.name}.`);this.game.bus.emit("legends:changed");return true}
 unequipRelic(index){let relic=(this.game.stats.relics||[])[Number(index)];if(!relic)return false;relic.equippedTo=null;this.game.bus.emit("legends:changed");return true}
 reputation(){let s=this.game.stats,b=this.game.buildings,p=this.game.citizens.list.length;if((s.bossesDefeated||0)>=5)return"Bandit's Bane";if(b.count("wall")>=20&&b.count("gate")>=2)return"The Walled Haven";if(b.count("market")>=1&&(this.game.resources.v.gold||0)>=5000)return"Merchant Hold";if((s.relics||[]).length>=3)return"The Storied Keep";if(p>=60)return"Great Settlement";return"Rising Haven"}
 update(){let s=this.game.stats;s.highestPopulation=Math.max(s.highestPopulation||0,this.game.citizens.list.length);s.goldRecord=Math.max(s.goldRecord||0,Math.floor(this.game.resources.v.gold||0))}
 summary(){let s=this.game.stats;return{title:this.reputation(),bosses:s.bossRecords||[],relics:s.relics||[],memorials:s.memorials||[],chronicle:s.chronicle||[],heroes:this.heroes(),wanted:this.wanted(),highestPopulation:s.highestPopulation||0,goldRecord:s.goldRecord||0,greatestRaid:s.greatestRaid||0,siegesWon:s.siegesWon||0}}
};
