/* THE SETTLEMENT — Roads-only finger painting bridge.
 * Additive wrapper around the proven placement/input stack. It never changes
 * normal building placement, walls, gates, tower relocation, saves or economy.
 */
(()=>{
 const P=Settlement.PlacementSystem?.prototype,I=Settlement.InputManager?.prototype,U=Settlement.PlacementUI?.prototype,R=Settlement.Renderer?.prototype;
 if(!P||!I||!U||!R||P.__roadPaintBridge)return;
 P.__roadPaintBridge=true;
 const states=new WeakMap();
 const state=g=>{let s=states.get(g);if(!s){s={tiles:[],drawing:false,pointer:null};states.set(g,s)}return s};
 const reset=g=>{let s=state(g);s.tiles=[];s.drawing=false;s.pointer=null};
 const isRoad=p=>p?.type==="road"&&!p.moving;
 const key=t=>t.x+","+t.y;
 function line(a,b){let out=[],x=a.x,y=a.y,dx=Math.abs(b.x-x),sx=x<b.x?1:-1,dy=-Math.abs(b.y-y),sy=y<b.y?1:-1,err=dx+dy;for(;;){out.push({x,y});if(x===b.x&&y===b.y)break;let e=2*err;if(e>=dy){err+=dy;x+=sx}if(e<=dx){err+=dx;y+=sy}}return out}
 function tileFor(input,e){let p=input.pos(e),w=input.game.camera.screenToWorld(p.x,p.y);return{x:Math.floor(w.x/64),y:Math.floor(w.y/64)}}
 function append(g,t){let s=state(g),last=s.tiles[s.tiles.length-1],add=last?line(last,t).slice(1):[t];for(const q of add){let at=s.tiles.findIndex(v=>v.x===q.x&&v.y===q.y);if(at>=0){s.tiles=s.tiles.slice(0,at+1);continue}s.tiles.push(q)}g.placement.hover=t;g.placement.lastValidation=plan(g);g.bus.emit("placement:moved",{type:"road",hover:t,validation:g.placement.lastValidation,roadPaint:true})}
 function plan(g){let s=state(g),d=Settlement.BuildingDefs.road,valid=[],invalid=[],skipped=[];for(const t of s.tiles){let id=g.grid.occupied.get(key(t)),b=id!==undefined?g.buildings.byId(id):null;if(b?.type==="road"){skipped.push(t);continue}let v=g.placement.validate("road",t.x,t.y);(v.ok?valid:invalid).push({x:t.x,y:t.y,validation:v})}let cost={};for(const[k,v]of Object.entries(d.cost||{}))cost[k]=v*valid.length;let affordable=g.resources.has(cost);return{tiles:s.tiles.slice(),valid,invalid,skipped,cost,ok:valid.length>0&&invalid.length===0&&affordable,affordable}}
 P.roadPaintPlan=function(){return isRoad(this)?plan(this.game):null};
 const start=P.start;P.start=function(type){let r=start.call(this,type);reset(this.game);return r};
 const cancel=P.cancel;P.cancel=function(reason){reset(this.game);return cancel.call(this,reason)};
 const confirm=P.confirm;P.confirm=function(){if(!isRoad(this))return confirm.call(this);let s=state(this.game);if(!s.tiles.length)return confirm.call(this);let q=plan(this.game);if(!q.ok){let reason=q.invalid.length?`${q.invalid.length} ROAD TILE${q.invalid.length===1?"":"S"} BLOCKED`:!q.affordable?"NOT ENOUGH GOLD FOR THIS ROAD":"DRAW ROAD ON OPEN SECURED LAND";this.lastValidation={ok:false,reason,roadPaintPlan:q};this.game.bus.emit("placement:validity",{type:"road",hover:this.hover,validation:this.lastValidation});this.game.bus.emit("toast","⛔ "+reason);return false}if(this.committing)return false;this.committing=true;if(!this.game.resources.spend(q.cost)){this.committing=false;this.game.bus.emit("toast","⛔ Resources changed — check road cost again.");return false}let made=[],d=Settlement.BuildingDefs.road;for(const t of q.valid){let b=this.game.buildings.create("road",t.x,t.y);made.push(b);this.game.bus.emit("placement:confirmed",{building:b,type:"road",cost:d.cost,hover:{x:t.x,y:t.y},batch:true});this.game.bus.emit("construction:started",b)}reset(this.game);this.type=null;this.hover=null;this.lastValidation=null;this.committing=false;this.game.bus.emit("toast",`🛤️ ${made.length} road tile${made.length===1?"":"s"} placed.`);this.game.bus.emit("placement:end");return made};
 // Keep original input listeners. Capture-phase listeners intercept only active road strokes.
 const bind=I.bind;I.bind=function(){bind.call(this);let c=this.canvas,g=this.game;
  const active=()=>isRoad(g.placement);
  c.addEventListener("pointerdown",e=>{if(!active()||e.pointerType==="mouse"&&e.button!==0||e.isPrimary===false)return;let s=state(g);s.tiles=[];s.drawing=true;s.pointer=e.pointerId;append(g,tileFor(this,e));c.setPointerCapture?.(e.pointerId);e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false});
  c.addEventListener("pointermove",e=>{let s=state(g);if(!active()||!s.drawing||s.pointer!==e.pointerId)return;append(g,tileFor(this,e));e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false});
  c.addEventListener("pointerup",e=>{let s=state(g);if(!active()||!s.drawing||s.pointer!==e.pointerId)return;append(g,tileFor(this,e));s.drawing=false;s.pointer=null;g.placement.lastValidation=plan(g);g.bus.emit("placement:moved",{type:"road",hover:g.placement.hover,validation:g.placement.lastValidation,roadPaint:true});e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false});
  c.addEventListener("pointercancel",e=>{let s=state(g);if(s.pointer!==e.pointerId)return;s.drawing=false;s.pointer=null;e.stopImmediatePropagation()},{capture:true,passive:false});
 };
 const render=U.render;U.render=function(){let p=this.game.placement,q=p?.roadPaintPlan?.();if(!q||!q.tiles.length)return render.call(this);let d=Settlement.BuildingDefs.road,count=q.valid.length,ready=q.ok,reason=q.invalid.length?`${q.invalid.length} blocked tile${q.invalid.length===1?"":"s"}`:!q.affordable?"Not enough Gold":`${count} road tile${count===1?"":"s"} ready`,cost=Object.entries(q.cost).map(([k,v])=>{let have=Math.floor(this.game.resources.v[k]||0),ok=have>=v;return `<span class="placement-cost ${ok?"ok":"short"}">${Settlement.ResourceDefs[k]?.icon||k} ${have}/${v}</span>`}).join("");this.el.innerHTML=`<div class="placement-info"><div class="placement-title"><span>${d.icon}</span><b>Draw ${d.name}</b><small>${count} new tile${count===1?"":"s"}${q.skipped.length?` • ${q.skipped.length} existing skipped`:""}</small></div><div class="placement-costs">${cost}</div><div class="placement-status ${ready?"valid":"invalid"}">${ready?"✓ ":"✕ "}${reason}</div></div><div class="placement-actions"><button type="button" class="placement-cancel" data-place-act="cancel">✕ CANCEL</button><button type="button" class="placement-confirm" data-place-act="confirm" ${ready&&!p.committing?"":"disabled"}>✓ BUILD ROAD</button></div>`;this.el.classList.remove("hidden")};
 const draw=R.draw;R.draw=function(){draw.call(this);let p=this.game.placement,q=p?.roadPaintPlan?.();if(!q||q.tiles.length<2)return;let ctx=this.ctx,cam=this.game.camera,D=this.dpr,T=64,W=this.c.width,H=this.c.height;ctx.save();ctx.translate(W/2,H/2);ctx.scale(cam.zoom*D,cam.zoom*D);ctx.translate(-cam.x,-cam.y);for(const t of q.tiles){let id=this.game.grid.occupied.get(key(t)),b=id!==undefined?this.game.buildings.byId(id):null,existing=b?.type==="road",blocked=q.invalid.some(v=>v.x===t.x&&v.y===t.y);if(existing){ctx.fillStyle="rgba(220,200,140,.18)";ctx.strokeStyle="rgba(240,220,160,.45)"}else if(blocked){ctx.fillStyle="rgba(200,70,70,.28)";ctx.strokeStyle="rgba(255,150,140,.8)"}else{ctx.fillStyle="rgba(166,205,101,.27)";ctx.strokeStyle="rgba(220,245,160,.85)"}ctx.lineWidth=2/Math.max(.25,cam.zoom);ctx.fillRect(t.x*T+5,t.y*T+5,T-10,T-10);ctx.strokeRect(t.x*T+5,t.y*T+5,T-10,T-10)}ctx.restore()};
})();
